### ISSUE TITLE
Security Dashboard Zapi Rest Diff

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1010]
Zapi rest diff against Infinity cluster has identified below gaps for security dashboard.

################## Missing Labels ##############
security_account_labels [svm]
security_certificate_labels [svm]
security_labels [uuid]

################## Missing Metrics by Object in prometheus ##############
security [security_audit_destination_status]

**Comment by cgrinds** [comment]
Verified on `release/22.08.0` a05a0279

on `infinity`
```
curl -s http://localhost:12992/metrics | rg "security_account_labels|security_certificate_labels|security_labels" | rg -o "^.*?\{" | sort | uniq
security_account_labels{
security_certificate_labels{
security_labels{
```

on `mobility`
```
curl -s http://localhost:12991/metrics | rg "security_audit_destination_status"
security_audit_destination_status{datacenter="nane1",cluster="ocum-mobility-01-02",protocol="udp_unencrypted"} 0
```
