### ISSUE TITLE
Creating dashboard for Headroom with Prometheus

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#1039]
**Is your feature request related to a problem? Please describe.**
We would like to have a headroom dashboard. Until I know the metrics are gathered with the current version 22.05.

**Describe the solution you'd like**
A dashboard for headroom working with Prometheus DB.

**Comment by cgrinds** [comment]
Verified on `release/22.08.0` a05a0279

**Comment by faguayot** [comment]
Hello @rahulguptajss,
Apologize because I forgot to check this. I was checking now and I found some errors (I guess). 

- Firstly, the units for **`Current throughtput`** and **`Current utilization`** (in _**aggregate**_ section and _**cpu**_ too) are wrong. I saw an issue for correcting the current utilization but not the others ([https://github.com/NetApp/harvest/issues/1288]).
![image](https://user-images.githubusercontent.com/85484449/193021045-efb829ea-4ffd-419b-90e4-8d0e59d6e14c.png)

- Secondly, in the graph where use percentage I think you need to define the mininum and the maxixum because the visual the scale isn't right. An exmaple of the view:
![image](https://user-images.githubusercontent.com/85484449/193021216-33c4173a-de68-4f44-bb65-cf1ed2a7da25.png)

- What is "Optimal Point and EWMA"? Could you share information where both points are explained for understanding.
- Without having clear what it is **Optimal Point** we have a node (AFF300) with a ssd aggregate which is showing the optimal point throughput bigger than a new node (AFF400) with nvme. That makes sense for you? In both nodes the capacity is almost the same, even the new node .has 3-4TB more.

![image](https://user-images.githubusercontent.com/85484449/193020919-39f26619-f58e-48a1-b501-7875121f8832.png)


Thanks.

**Comment by faguayot** [comment]
1. Yes, the issue about units seems to be solved but I saw a negative values in the "**Available Ops : Aggregate**" and in the "**Available Ops: CPU**"

![image](https://user-images.githubusercontent.com/85484449/193050408-1d491bf4-ed36-4804-9c3a-f4de6609b463.png)

2. Ok
3. Using the commands provided to try understand the metrics.
4. I need time to check and understand if I have doubts.

**Comment by cgrinds** [comment]
Spoke to Rusty, who helped create these. I'll update the information on these panels to include something like this:

> This graph displays the difference between CPU Utilization and Peak Performance (Optimal Point) as Available Ops (aka Headroom). If the current Available utilization is very low or negative for an extended time, a performance remediation plan might be appropriate. A performance remediation plan might include setting QoS workload limits, moving volumes or LUNs to another storage controller, or expanding the storage cluster.

**Comment by cgrinds** [comment]
The doc update is missing. PR #1469 includes the doc updates.
I'll move this to `status/done` once that PR is merged

**Comment by cgrinds** [comment]
Verified on 22.11
