### ISSUE TITLE
Ensure collectors and pollers recover panics

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#105]
Code review collectors and pollers to make sure they recover from all panics

Related to Martin Möbius's message on slack
> I have an issue that the pollers just stop running without any log output. Any ideas how to troubleshoot that?
> Happens after running for some days

* [ ] Add more unit tests to cover panics in poller/collectors
* [x] Include more longevity testing in lab that monitors for this
* [ ] Update [Troubleshooting](https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest) to include details

**Comment by cgrinds** [comment]
Related #107

**Comment by mamoep** [comment]
I checked again. After doing "switchdisable" of a MCC backend FC switch, the poller stopped. Last message with loglevel 0:
`2021/06/07 13:02:45  (debug  ) (collector) (ZapiPerf:Path): fetching data of instance [node-01:kernel:0g.210000108663aec8]` I guess that won't help much.

**Comment by rahulguptajss** [comment]
@cgrinds  Should this be in testme or done?
