### ISSUE TITLE
Compliance & Security Dashboard - Text not readable with Light Theme

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#1078]
**Describe the bug**
- In the Compliance Dashboard and the Security Dashboard the uncolored Text fields are unreadable when Grafana Light theme is used.
- Datacenter variable is not sorted
- NTP server number higher as 3 is not green (Compliance)

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 22.05.0-1 (commit 2bc2942) (build date 2022-05-11T07:56:11-0400) linux/amd64
- ONTAP Version: 9.9.1P9
- Other: Grafana 8.3.3

**To Reproduce**
- activate Grafana light theme
- navigate to Compliance dashboard

**Expected behavior**
Readable text

**Actual behavior**
white text on white background

**Additional context**
![grafik](https://user-images.githubusercontent.com/26142342/172621994-ba6e62e2-fea4-4b46-a000-7f09e6c3ae54.png)

**Comment by cgrinds** [comment]
thanks @mamoep too many of us run with the dark theme. As a temporary workaround you can switch to dark theme, but we'll get this fixed

**Comment by mamoep** [comment]
Same issue applies to Data Protection and Data Protection SnapMirror dashboards.

**Comment by Hardikl** [comment]
For Data Protection Snapshot and SnapMirror dashboards.
