### ISSUE TITLE
Improve color consistency and hover info on Compliance dashboard

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1083]
Update hover info to make the three state distinction clearer

Thanks to Rene Meier for reporting on Slack

Conversation copied below
---

[Rene Meier](https://app.slack.com/team/U01NC6PCXE2) [Yesterday at 9:05 AM](https://netapppub.slack.com/archives/C02072M1UCD/p1654693547455989)
Harvest - cDOT -> NetApp Detail: Compliance
Last 4 columns (ldap Users | Certificate Users | Local Users | Certificate Issuer Type ) are not colored with green (good) or orange (not so good).
image.png 
image.png

5 replies

[Chris Grindstaff](https://app.slack.com/team/U01SXH43FG9):netapp-black:  [24 hours ago](https://netapppub.slack.com/archives/C02072M1UCD/p1654694011768239?thread_ts=1654693547.455989&cid=C02072M1UCD)
hi [@Rene Meier](https://netapppub.slack.com/team/U01NC6PCXE2) - yes, a consistency problem slipped through. Would you rather see the cells in the last four columns a) colored green when they are correctly configured or b) no green and orange when something is incorrectly configured. Option b seems less noisy, what do you think?

[Rene Meier](https://app.slack.com/team/U01NC6PCXE2)  [22 hours ago](https://netapppub.slack.com/archives/C02072M1UCD/p1654699139546859?thread_ts=1654693547.455989&cid=C02072M1UCD)
All columns in this table, exept this four, are colored in green if they are correctly configured and colored in orange if not. Option B sounds good for me. If you go with the option B, please for the whole dashboard.

[Chris Grindstaff](https://app.slack.com/team/U01SXH43FG9):netapp-black:  [22 hours ago](https://netapppub.slack.com/archives/C02072M1UCD/p1654699281550779?thread_ts=1654693547.455989&cid=C02072M1UCD)
there are really 3 states, compliant, not compliant, not used to determine compliance. Compliant is green, not compliant is orange, information but not used to determine compliance is transparent

[Rene Meier](https://app.slack.com/team/U01NC6PCXE2)  [5 hours ago](https://netapppub.slack.com/archives/C02072M1UCD/p1654761326079789?thread_ts=1654693547.455989&cid=C02072M1UCD)
ok. Let's go with this 3 states for the whole dashboard.

[Chris Grindstaff](https://app.slack.com/team/U01SXH43FG9):netapp-black:  [3 minutes ago](https://netapppub.slack.com/archives/C02072M1UCD/p1654778435373489?thread_ts=1654693547.455989&cid=C02072M1UCD)
will do, we're going to improve the hover info for these panels to make the distinction more clear also. Thanks for raising :thumbsup:

**Comment by cgrinds** [comment]
Notes from meeting
- drop green from tables since red communicates non-compliance
- use red fro non-compliance
- update hover info to reflect these changes

**Comment by Hardikl** [comment]
- dropped background colors(green/orange) and added ❌ (as text) before non compliant value
- updated hover info to reflect these changes

This would looks like this:
![image](https://user-images.githubusercontent.com/83282894/176915792-38884142-cec5-4ee0-9e50-677229b58b16.png)

![image](https://user-images.githubusercontent.com/83282894/176915808-06b18247-4543-46e5-bb63-03eb893f8bfb.png)
