### ISSUE TITLE
Revisit logs in plugins

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1094]
As reported in slack by `Martin Mobius`, we should revisit all of the plugin logs and update the log level accordingly.

`[Martin Möbius](https://app.slack.com/team/U022GLC8D55)  [1:34 PM](https://netapppub.slack.com/archives/C02072M1UCD/p1654848275095899)
I get an error about collecting disk data. Failed to collect disk data error="no instances"
I saw in the code you do a disk-encrypt-get-iter request. This doesn't return any disks if the disks have no encryption capability. I am not sure if this is intended. getDiskData function name and the error messages don't imply that the lookup is about encryption disks.`

**Comment by cgrinds** [comment]
Verified Martin's issue is addressed in `release/22.08.0` a05a0279. Also verified the other plugin logger changes.
