### ISSUE TITLE
Vscan Connections Active Panel Issue

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1101]
As reported in slack.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/25551691/173834083-f3fcbd2a-b35c-4ebd-aed8-89cf7b3aff9f.png">

**Comment by cgrinds** [comment]
Verified on `release/22.08.0` a05a0279 that `Virus Scan Connections Active` uses log base 2 axis and no decimals in panel.
