### ISSUE TITLE
Quota report dashboard 

### ISSUE THREAD

**Issue by ev1963** [NetApp/harvest#1111]
looking for quota report dashboard for volume, qtree and user.

**Comment by cgrinds** [comment]
hi @ev1963 the May release of Harvest includes some improvements to the Qtree dashboard and a couple of weeks ago we fixed #1079 for qtrees (image below). Do these address your ask?  If not, can you add a few more words about what you're looking for?

Are you interested in contributing these panels or dashboard?


![image](https://user-images.githubusercontent.com/242252/175108012-015b87df-92ba-4a42-8ae4-701952ebd4a8.png)

**Comment by ev1963** [comment]
yes, this is exactly what I am looking for.
