### ISSUE TITLE
ZapiPerf reports error with Volume and VolumeNode

### ISSUE THREAD

**Issue by PegasusPrime** [NetApp/harvest#116]
**Describe the bug**
The harvest log is reporting errors with the Volume and VolumeNode zapiperf plugin

2021/06/04 20:45:12  (error  ) (collector) (ZapiPerf:Volume): api request rejected => Incorrect counter list: "timestamp", non-existent counters are not allowed.
2021/06/04 20:45:12  (error  ) (collector) (ZapiPerf:VolumeNode): api request rejected => Incorrect counter list: "timestamp", non-existent counters are not allowed.

**Environment**

- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:29:32+0530) linux/amd64
- Command line arguments used:  bin/poller --poller rome --loglevel 2 --promPort 12990 --config /opt/harvest/harvest.yml --daemon
- OS: CentOS 7.9
- Install method: native
- ONTAP Version: 9.1P20 cmode

**Comment by vgratian** [comment]
Hi, thanks for reporting this. Do you use a custom template for the Volume/VolumeNode objects or is it the default one?

**Comment by vgratian** [comment]
I think I know more or less what's the problem here: when building a ZAPI request, the ZapiPerf collector includes all metrics in the request (including internally generated metrics, such as "timestamp"). For recent ONTAP versions this is not an issue, only metrics that are known to ZAPI are included in the response, older ONTAPs reject the request.

We can fix this by adding a special tags to all ZAPI counters to include only those in the request.

**Comment by PegasusPrime** [comment]
Hi, thanks for looking into this! To answer your previous question, no I am not using anything custom. I am using the defaults from the release tarball.

**Comment by rajeshl8** [comment]
Verified on latest harvest build and did not observe above mentioned errors.
[root@scspa2398581002 harvest]# /opt/harvest/bin/harvest -v
harvest version 21.06.1121-nightly (commit 1524ebb) (build date 2021-06-11T21:11:15+0530) linux/amd64
[root@scspa2398581002 harvest]# pwd
/var/log/harvest
[root@scspa2398581002 harvest]# grep -ir "api request rejected => Incorrect counter list: "timestamp"" .
[root@scspa2398581002 harvest]#

**Comment by cgrinds** [comment]
Commit `4ae5b920fdf1`

4:01PM ERR goharvest2/cmd/poller/collector/collector.go:303 >  error="configuration error => missing timestamp metric" Poller=F2240-127-26 collector=ZapiPerf:TokenManager stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*ZapiPerf).PollData","line":"174","source":"zapiperf.go"},{"func":"(*task).Run","line":"60","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"269","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]

```
Pollers:
  F2240-127-26:
    datacenter: F2240-127-26
    addr: 10.193.6.61
    auth_style: password
    username: -REDACTED-
    password: -REDACTED-
    exporters:
      - prometheus1
```

**Comment by cgrinds** [comment]
Comment [above](https://github.com/NetApp/harvest/issues/116#issuecomment-868807027) is for a different issue closing
