### ISSUE TITLE
Some graphs show "no data"

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#119]
**Describe the bug**
Some graphs show "no data"

**Environment**
- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64
- Command line arguments used: using provided systemctl-unit-file
- OS: Red Hat Enterprise Linux release 8.3 (Ootpa)
- Install method: native-rhel-package
- ONTAP Version: several (from 9.5 upwards)

**To Reproduce**
Steps to reproduce the behavior: just open any dashboard

**Expected behavior**
Want to see graphs

**Actual behavior**
Graph shows - no-data

**Possible solution, workaround, fix**
Nothing found

**Additional context**
![image](https://user-images.githubusercontent.com/33655308/120981221-bc5a4400-c777-11eb-9b78-4dd43aec5128.png)

**Comment by cgrinds** [comment]
Do you see the data in Prometheus?

**Comment by florianmulatz** [comment]
Reinstallation solved problem. Guess where some leftovers from old installation maybe

**Comment by cgrinds** [comment]
Thanks for acknowledging and glad it's working now
