### ISSUE TITLE
Data Protection Snapmirror - Unprotected

### ISSUE THREAD

**Issue by Falcon667** [NetApp/harvest#1192]
**Describe the bug**
In the Data Protection Snapmirror almost every volumes has the status unprotected even if there is a snapmirror relation to the backup site.
If I look in Prometheus the volume_labels metric I see that the status of  protectedBy is not_applicable. If the source and destination volume is on the same cluster I see protectedBy  is snapmirror.

![image](https://user-images.githubusercontent.com/99657787/183384120-a52a7def-a404-4522-b497-f6e29f0903cf.png)

**Environment**
Production

- Harvest version: 22.05
- OS: 3.1.1
- Install method: NABox
- ONTAP Version: 9.9.1 P9

**Expected behavior**
That every volume which have a snapmirror relationship is on the dahsboard 

**Actual behavior**
There is only one volume which have a SnapMirror relationship

**Additional context**
SnapMirror overview
![image](https://user-images.githubusercontent.com/99657787/183386421-0b30cd57-e4ba-4e7f-ae4e-ca343eb18358.png)

**Comment by Hardikl** [comment]
I am looking into it and trying to reproduce inter-cluster relationships locally.

@Falcon667 
Could you confirm these:
- The mentioned behavior would be seen only when snapmirror relationships are inter-clustered ?
- The above dashboard view(in screenshot) would be seen when you choose specific cluster(sourceCluster or destinationCluster) in drop down or both clusters would have same view?

**Comment by Falcon667** [comment]
Hi @Hardikl,
Yes the behavior is only when the snapmirror relationship is between two clusters.
There are no entries in the dashboard no matter if source or destination cluster (We are doing the vault to a secondary destination)

**Comment by Falcon667** [comment]
Hi @Hardikl 
Thank you for your analysis.
I see it is tricky since the poller are independent and cannot share the data. Since Harvest collect the snapmirror metric would it be possible like doing a sort of matching between the volume and the snapmirror relationship?

**Comment by mamoep** [comment]
I want to make a remark regarding getting information about the source cluster. Snapmirror relationships require peering of source and destination cluster & vserver. The snapmirror relation shows the source vserver. With help of the peering information it can be mapped to the source cluster.
```
dest_cluster::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
svm_dest    svm_source  peered       source_cluster    snapmirror     svm_source
```

ZAPI: `vserver-peer-get-iter`
REST: `/svm/peers`

**Comment by Hardikl** [comment]
Build 22.08

Tested on 10.231.176.53 cluster
Here is different count which are from destination side and no differentiation between local/remote detail.
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/83282894/202164439-110276c6-e16c-4de2-aec8-f766054e2f02.png">

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/83282894/202164613-50157ad0-a049-450f-abb2-c349c3eee349.png">



Build 22.11.0
Tested on 10.231.176.53 same cluster
Here is different count which are from source side and we have column shows local/remote detail.
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/83282894/202170275-746c96f0-79a0-403a-baee-69bba9e40711.png">

Unprotected volume panel
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/83282894/202170545-86e39860-11e6-4eb0-b2e8-2825094924e2.png">



Tested on 10.226.207.154 cluster as well where now we do show 4 remote SM relationship as well.
