### ISSUE TITLE
Add Grafana tags on default dashboards

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#1219]
**Is your feature request related to a problem? Please describe.**
It can be difficult to identify default dashboards when using custom dashboards in the same folder.

**Describe the solution you'd like**
Having a tag on the stock dashboards would make it easier to clean and reimport.

**Describe alternatives you've considered**
Identifying stock dashboards by name helps, but if the name changes in the distribution then it's no longer valid. Tags provide a unique identifier that clearly identifies dashboards distributed with Harvest

**Additional context**
This specific requests is done with NAbox in mind to help implement a quick way to update the dashboards witht he ones from harvest distribution, but can be useful also without NAbox to clean up dashboard folders when shared with user dashboards.

One thing to consider is, are the tags preserved when "Save as" is used to customize a given dashboard. In that case, the user would have to be mindful of removing the tag when saving.

**Comment by cgrinds** [comment]
Verified with 22.11 build commit b666d732
Dashboards are tagged from the set of:
- 7mode
- cdot
- storagegrid
- fsx
- harvest
- meta
- ontap
