### ISSUE TITLE
Duplicate Instance Issue Quota

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1224]
As reported by @Falcon667 over discord.

`[36mnabox-harvest2        |[0m [90m1:48PM[0m [1m[31mERR[0m[0m [1mcollector/collector.go:393[0m[36m >[0m plugin [Qtree]:  [36merror=[0m[31m"duplicate instance key => *****"[0m [36mPoller=[0mss009104 [36mcollector=[0mZapi:Qtree [36mstack=[0m"goroutine 623 [running]:\ngithub.com/netapp/harvest/v2/pkg/logging.MarshalStack({0xb8b8c0?, 0xc0021c0ee0?})\n\tgithub.com/netapp/harvest/v2/pkg/logging/logger.go:152 +0x89\ngithub.com/rs/zerolog.(*Event).Err(0xc000906240, {0xb8b8c0, 0xc0021c0ee0})\n\tgithub.com/rs/zerolog@v1.27.0/event.go:381 +0x63\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start(0xc000362f70, 0x0?)\n\tgithub.com/netapp/harvest/v2/cmd/poller/collector/collector.go:393 +0x17ae\ncreated by main.(*Poller).Start\n\t./poller.go:399 +0x2c5\n"`

**Comment by cgrinds** [comment]
No duplicate instances on .74 system monitoring four clusters.
Verified on 22.11 build 44549cd

```bash
rg -z "Qtree" /var/log/harvest/ | rg ERR
```
