### ISSUE TITLE
Harvest 21.05.2(Build#75) after fresh installation fails to start Poller umeng_aff300 (ONTAP 9.7P7)

### ISSUE THREAD

**Issue by sridevimm** [NetApp/harvest#123]
**Describe the bug**
Harvest 21.05.2(Build#75) after fresh installation fails to start Poller umeng_aff300 (ONTAP 9.7P7)

**Environment**
- Harvest version: harvest-21.06.0801-nightly build#75
- Command line arguments used: 
   On Debian 10: sudo apt install ./harvest-21.06.0801-nightly.amd64.deb 
  On RHEL8 : tar xvf harvest-21.06.0801-nightly_linux_amd64.tar.gz 
- OS: Debian 10 and RHEL 8
- Install method: listed above
- ONTAP Version: 9.7P7
- Other:

**To Reproduce**
Install .deb no Debian 10 or tar.gz on RHEL8 system using above commands
Edit harvest.yml file by adding 2 clusters
Restart harvest and check status

**Expected behavior**
Pollers should run without any issues

**Actual behavior**
root@scspa2380901004:/opt/harvest# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300          11947                      unknown: os: process already finished
F2240-127-26          F2240-127-26          11956      12991           running             
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
root@scspa2380901004:/opt/harvest# 

**Possible solution, workaround, fix**
Tried restarting and didn't help. 
Tried adding the IP and port to Prometheus and restarted harvest to see if that helps and it didn't.

**Additional context**
poller_umeng_aff300.log: 
{"level":"fatal","Poller":"umeng_aff300","exporter":"prometheus1","caller":"/tmp/build/opt/harvest/cmd/exporters/prometheus/httpd.go:28","time":"2021-06-07T18:00:15-04:00","message":"(httpd) listen tcp :12990: bind: address already in use"}

**Comment by sridevimm** [comment]
More info from the poller_unix.log

{"level":"warn","Poller":"unix","collector":"Unix:poller","caller":"/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/collectors/unix/main.go:362","time":"2021-06-07T17:31:30-04:00","message":"skip instance [umeng_aff300], process: process not found => stat /proc/23273: no such file or directory"}
{"level":"error","Poller":"unix","collector":"Unix:poller","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*AbstractCollector).Start.func1","line":"241","source":"collector.go"},{"func":"gopanic","line":"965","source":"panic.go"},{"func":"goPanicIndex","line":"88","source":"panic.go"},{"func":"(*MetricUint8).SetValueUint8","line":"79","source":"metric_uint8.go"},{"func":"(*Matrix).LazySetValueUint8","line":"76","source":"lazy.go"},{"func":"(*Unix).PollData","line":"340","source":"main.go"},{"func":"(*task).Run","line":"60","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"270","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}],"error":"goroutine panic => goroutine 13 [running]:\nruntime/debug.Stack(0xc000065140, 0xab9203, 0x0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start.func1(0xc00009c4d0)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/collector/collector.go:241 +0x9d\npanic(0xab92c0, 0xc00002a4c8)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngoharvest2/pkg/matrix.(*MetricUint8).SetValueUint8(0xc0001ecea0, 0xc00000ea08, 0x7f48d2dd6e01, 0x6, 0xc000200508)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/pkg/matrix/metric_uint8.go:79 +0x6a\ngoharvest2/pkg/matrix.(*Matrix).LazySetValueUint8(0xc00006e820, 0x7f48d2dd6efc, 0x6, 0xc0002da900, 0xc, 0x1, 0x0, 0x0)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/pkg/matrix/lazy.go:76 +0x20d\ngoharvest2/cmd/collectors/unix.(*Unix).PollData(0xc00005eee0, 0x0, 0x0, 0x0)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/collectors/unix/main.go:340 +0x4fe\ngoharvest2/cmd/poller/schedule.(*task).Run(0xc000062f40, 0x12a5ac662f, 0xe2cd40, 0x254b16324)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/schedule/schedule.go:60 +0x5a\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start(0xc00009c4d0, 0xc0001eaf44)\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/collector/collector.go:270 +0x1b5\ncreated by main.(*Poller).Start\n\t/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/poller.go:313 +0x225\n","caller":"/var/jenkins_home/workspace/BuildHarvestArtifacts/harvest/cmd/poller/collector/collector.go:241","time":"2021-06-07T17:31:30-04:00","message":"Collector panicked"}

**Comment by sridevimm** [comment]
Forgot to add system details: 

IP: 10.193.114.99 (root/netapp) - Debian 10
IP: 10.193.115.7 (root/netapp) - RHEL 8

**Comment by rahulguptajss** [comment]
@sridevimm You may be hitting issue #20 . Before editing Harvest.yml, harvest needs to be stopped currently.

**Comment by cgrinds** [comment]
`Machine X.99`

```
ll /var/run/harvest/
total 8
-rw-rw-rw- 1 root root 5 Jun  7 18:04 F2240-127-26.pid
-rw-rw-rw- 1 root root 5 Jun  7 18:00 umeng_aff300.pid

bin/harvest status
Datacenter            Poller                PID        PromPort        Status
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300          11947                      unknown: os: process already finished
F2240-127-26          F2240-127-26          12034      12991           running
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++

ps aux | grep poller
root     12034  0.7  1.1 1235500 94148 ?       Sl   Jun07   6:16 bin/poller --poller F2240-127-26 --loglevel 2 --promPort 12991 --config ./harvest.yml --daemon
```

This is a stale pidfile issue. The pidfiles were created yesterday. Two pollers should be running but only one is. 
`start` needs to detect when the process isn't running but a pidfile is present

**Comment by sridevimm** [comment]
Validated the fix on a fresh installed Debian system with harvest-21.06.1121-nightly build. Marking this as status/done.

root@scspa2380901005:/opt/harvest# vi harvest.yml
root@scspa2380901005:/opt/harvest# 
root@scspa2380901005:/opt/harvest# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300                                     not running         
F2240-127-26          F2240-127-26                                     not running         
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
root@scspa2380901005:/opt/harvest# bin/harvest start
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300          16741      12990           running             
F2240-127-26          F2240-127-26          16750      12991           running             
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
root@scspa2380901005:/opt/harvest# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300          16741      12990           running             
F2240-127-26          F2240-127-26          16750      12991           running             
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
root@scspa2380901005:/opt/harvest# 
root@scspa2380901005:/opt/harvest# ps aux | grep poller
harvest  16741  5.9  1.0 1234720 84412 ?       Sl   15:09   0:00 bin/poller --poller umeng_aff300 --loglevel 2 --promPort 12990 --config ./harvest.yml --daemon
harvest  16750  7.3  1.1 1234464 91616 ?       Sl   15:09   0:01 bin/poller --poller F2240-127-26 --loglevel 2 --promPort 12991 --config ./harvest.yml --daemon
root     16768  0.0  0.0   6144   884 pts/0    S+   15:09   0:00 grep poller
root@scspa2380901005:/opt/harvest# 
root@scspa2380901005:/opt/harvest#
