### ISSUE TITLE
Possible Issue with the api tool?

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#1230]
If I run rest show data, it works. But If I try to GET param or other attributes of api, it fails with below message. 

Is there a CLI document for this tool?

_bin/harvest rest show models --poller mypoller --api cluster --max-records 2
Using downloaded file /tmp/mypoller_fqdn-swagger.yaml with timestamp 2022-08-23 11:58:42.692790756 -0700 PDT
error unmarshalling swagger file=[ /tmp/mypoller_fqdn-swagger.yaml] err=yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `<!DOCTY...` into map[string]interface {}_

**Comment by Hardikl** [comment]
@jmg011 

These are the example of CLI usage
```
Examples:
  harvest rest -p infinity show apis                                        Query cluster infinity for available APIs
  harvest rest -p infinity show params --api svm/svms                       Query cluster infinity for svm parameters. These query parameters are used
                                                                            to filter requests.
  harvest rest -p infinity show models --api svm/svms                       Query cluster infinity for svm models. These describe the REST response
                                                                            received when sending the svm/svms GET request.
  harvest rest -p infinity show data --api svm/svms --field "state=stopped" Query cluster infinity for stopped svms.

  harvest rest -p infinity show data --api storage/volumes \                Query cluster infinity for all volumes where
      --field "space.physical_used_percent=>70" \                               physical_used_percent is > 70% and
      --field "space.total_footprint=>400G" \                                   total_footprint is > 400G
      --fields "name,svm,space"                                             The response should contain name, svm, and space attributes of matching volumes.

  harvest rest -p infinity show data --api storage/volumes \                Query cluster infinity for all volumes where the name of any volume or child
      --query-field "name" --query-value "io_load|scale"                         resource matches io_load or scale.
```

I ran the models CLI and I could able to get the appropriate response.
```
[root@scspo2663212001 harvest]# ./bin/harvest rest -p cluster-01 show models --api cluster --max-records 2
```

Let us know if you still get any errors while invoking the above CLI on your poller.

**Comment by cgrinds** [comment]
hi @jmg011 before deleting `/tmp/mypoller_fqdn-swagger.yaml`, please email it to us so we can make sure there isn't a schema change Harvest needs to accommodate.

**Comment by jmg011** [comment]
@cgrinds  @rahulguptajss - Sent an email with the details

@Hardikl Thanks for that help output. I use that but I was wondering if there is any detailed documentation for this.

**Comment by cgrinds** [comment]
@jmg011 thanks for the email. @rahulguptajss found the issue, this is a known ONTAP bug [(1342377)](https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1342377) that prevents access to the swagger file Harvest is trying to download when the user has a non-admin role.

There is a workaround to add the non-admin user to the web service listed [here](https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/ONTAP-REST-docs-api-permissions/m-p/158286#M86%3Fref_source=cty-other%20campaign%20%7Budf%7D--1957).

**Comment by jmg011** [comment]
@cgrinds @rahulguptajss 

Thank you for looking into this and pointing me to the work around. 

The workaround fixed the issue. Appreciate your help.

**Comment by cgrinds** [comment]
Closing with workaround
