### ISSUE TITLE
FlashCache Dashboard (found in 22.08 - ONTAP:Disk), 

### ISSUE THREAD

**Issue by KlausHub** [NetApp/harvest#1265]
**Describe the bug**
- FlashCache Graph is wrong valuetype on y-axis (µs, but should be percent), see attached Graph
- Disk Throughput Graph show 800kB/s, but should be 800MB/s (Faktor 1000 misaligned?)

**Environment**
- Harvest version: 22.08.0-1
   harvest version 22.08.0-1 (commit 93db10a) (build date 2022-08-19T09:09:07-0400) linux/amd64
- OS: RHEL 8.4
- Install method: native
- ONTAP Version:9.8
- Other:

**To Reproduce**
easy to reproduce, check the Graph in Harvest_22_08 / Ontap: Disk Dashboard, 
could be also seen on other of our Filers

![Harvest_22_08_ONTAP_Disk_Dashboard_BUG](https://user-images.githubusercontent.com/97510878/189127080-f5fb8084-e653-4704-a8a3-c8bea53f4a7a.PNG)

Many Thanks for this good piece of Software, it is very helpful in Performance Debugging.

Cheers,
Klaus

**Comment by cgrinds** [comment]
Thanks @KlausHub

**Comment by cgrinds** [comment]
Hi Klaus - Thanks again for raising. Should be fixed in #1268. If you want, you can apply the [changes](https://github.com/NetApp/harvest/pull/1268/files). Edits are needed in the `zapiperf` template and the dashboard.

**Comment by cgrinds** [comment]
Verified with 22.11 build commit 6d5f6a48
`Flash Cache` and `Disk Throughput` have the correct units
