### ISSUE TITLE
Always start harvest as harvest user in rpm/deb

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#129]
There are 2 ways user can start harvest on rpm/deb as below

1. Systemctl start harvest
2. bin/harvest start

Case 1: starts Harvest as user "harvest". 
Case 2: If this command is executed as root then systemctl command will not be able to stop such pollers and may create issues where some of the pollers never get started.

Proposed solution: Make sure harvest always gets started as "harvest" in rpm/deb

**Comment by sridevimm** [comment]
Validated the fix in harvest-21.06.1121-nightly. Marking this as status/done.

[root@scspa2385980001 harvest]# ps aux | grep poller
root        28  0.0  0.0      0     0 ?        I<   May20   0:00 [edac-poller]
harvest  27762  2.5  1.1 1241188 91732 ?       Sl   13:56   1:01 bin/poller --poller F2240-127-26 --loglevel 2 --promPort 12991 --config /opt/harvest/harvest.yml --daemon
harvest  28188 14.6  1.0 1166880 85896 ?       Sl   14:37   0:00 bin/poller --poller umeng_aff300a --loglevel 2 --promPort 12990 --config ./harvest.yml --daemon
root     28197  0.0  0.0 221860  1096 pts/0    R+   14:37   0:00 grep --color=auto poller


[root@scspa2385980001 ~]# systemctl stop harvest
[root@scspa2385980001 ~]# cd /opt/harvest/
[root@scspa2385980001 harvest]# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300a         umeng_aff300a                                    not running         
F2240-127-26          F2240-127-26                                     not running         
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
[root@scspa2385980001 harvest]#

[root@scspa2385980001 harvest]# systemctl start harvest
[root@scspa2385980001 harvest]# bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300a         umeng_aff300a         28285      12990           running             
F2240-127-26          F2240-127-26          28292      12991           running             
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
[root@scspa2385980001 harvest]#
