### ISSUE TITLE
Improve config tool

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#13]
The config tool helps configure pollers that monitor ONTAP clusters.

The tool should:
- [ ] validate harvest configuration flie (`harvest.yml`)

Implemented, but needs more testing:
- [ ] create a client certificate on the local system
- [ ] create a read-only harvest user for ONTAP
- [ ] install client certificate on ONTAP

Known issues
- client certificate is re-generated each time

We may want to integrate this tool with the Zapi tool

**Comment by vgratian** [comment]
working on this

**Comment by cgrinds** [comment]
Not needed
