### ISSUE TITLE
7mode bin/zapi cli is failing

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1315]
This is a regression caused by #1170. Workaround pass `--max 0` in cli.

![image](https://user-images.githubusercontent.com/25551691/192590075-37a6896c-5260-41b7-a21b-43de833fe46b.png)

**Comment by Hardikl** [comment]
verified on 22.11

```
% ./bin/zapi -p cluster-11 show data --object nic_common
connected to fas2240-2 (NetApp Release 8.2.5P3 7-Mode: Tue Jul 16 01:37:24 PDT 2019)
<root>
...
...
...
</root>
```
