### ISSUE TITLE
Prometheus potentially collects duplicate EMS events in a period of time

### ISSUE THREAD

**Issue by pilot7777** [NetApp/harvest#1324]
We have a use case that requires Prometheus alerts if wafl.memory.statusLowMemory happens more than once in 10 minutes. But using sum_over_time(ems_events{name="wafl.memory.statusLowMemory"}[10m]) > 1 or count_over_time may cause false alarm. 

Let's say our prometheus scrape interval is 15 sec and given harvest will keep this event in cache for 3 minutes then we'll have this entry 12 times in prometheus. In that case, this statement will be greater than 1 even if the ems was raised only once. 

Thanks!

James

**Comment by pilot7777** [comment]
Hi Harddikl,
Thank you very much for the suggestion. Is it possible this counts wafl.memory.statusLowMemory from different nodes?  I tried with last_over_time(ems_events{message="wafl.vol.autoSize.done"}[10h]) and it counted all events for different volumes. 
Maybe this will work?
count(count(last_over_time(ems_events{message="wafl.memory.statusLowMemory"}[10m])) by (node)) > 1

**Comment by Hardikl** [comment]
Yes @pilot7777 , 
This `count(last_over_time(ems_events{message="wafl.memory.statusLowMemory"}[10m])) by (node) > 1` query would provide ems events count at node level which are more than one in the provided time range.

**Comment by pilot7777** [comment]
Closing because using count with last_over_time works.
