### ISSUE TITLE
Grafana Panel Titles in the Aggregate Dashboard don't accurately reflect info being displayed.

### ISSUE THREAD

**Issue by matt-nelson-netapp** [NetApp/harvest#133]
**Describe the bug**
Panel Titles in the Aggregate Dashboard don't accurately reflect info being displayed.

**Environment**
Linux/docker

- OS: [e.g. RHEL 7.6, ]
- Install method: [ docker]
- ONTAP Version: [e.g. 9.7, 9.8, 9.9,]

**To Reproduce**
Install Harvest & Grafana with ONTAP 9.7+ collectors. Go to the stock Aggregate dashboard.  look at panels titled "Space Used", "inode used %" (there are 2), "files", etc.... 

These panels are actually querying for data based on snapshot info but the titles do not reflect that.

**Expected behavior**
Panel Titles reflect query used.

**Actual behavior**
Tell us what happens instead

**Possible solution, workaround, fix**
Change Panel Titles to reflect the query being used.

**Comment by vgratian** [comment]
thanks, I am working on the dashboards, I'll make sure that this is corrected as well.

if you noticed any other errors, or you have suggestions for improvement let us know!

**Comment by matt-nelson-netapp** [comment]
one other suggestion is some panels with tables do not have "green-yellow-red (by value)" set for color scheme in the fields tab where many others do. I had to fix one manually yesterday which I think was volumes in cluster but i cant remember exactly.

**Comment by vgratian** [comment]
no need to test, I've tested
