### ISSUE TITLE
Zapi CLI timeout

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1342]
`bin/zapi -p u2 show data --object volume --config harvest_openlab.yml --max 1000 | dasel -r xml -w json > d.json
connected to umeng-aff300-05-06 (NetApp Release 9.9.1P9X3: Tue Apr 19 19:05:24 UTC 2022)
2022/10/11 21:02:34 context deadline exceeded (Client.Timeout or context cancellation while reading body)`

**Comment by cgrinds** [comment]
`bin/zapi` should handle pagination and allow us to set a timeout

**Comment by cgrinds** [comment]
Verified in `24.02` 84e2f7ca

```bash
bin/harvest zapi -p u2 show data --object volume --max-records 1000 --timeout 1s
connected to umeng-aff300-05-06 (NetApp Release 9.9.1P9X3: Tue Apr 19 19:05:24 UTC 2022)
2024/02/12 10:09:54 connection error => Post "https://10.193.48.11:443/servlets/netapp.servlets.admin.XMLrequest_filer": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
