### ISSUE TITLE
Check Rest Aggr counter

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1365]
Recheck the mapping mentioned [here](https://github.com/NetApp/harvest/blob/main/conf/rest/9.12.0/aggr.yaml#L14)

Check also in 9.10 folder.

**Comment by cgrinds** [comment]
Verify if this counter is the one we want to collect
`- space.cloud_storage.used                                       => space_capacity_tier_used`

**Comment by Hardikl** [comment]
Checked on mobility (9.8P2), zapi and rest values are matching.

<img width="1766" alt="image" src="https://user-images.githubusercontent.com/83282894/201056985-496cc011-28a5-4281-a93e-59abb244acdc.png">

For other clusters which are 9.10 or higher, they don't have data for this counter.
