### ISSUE TITLE
Compatibility with InfluxDB v1.8

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#1370]
Hello, 

I have a doubt about the compatibility of Harvest 2.0 with InfluxDB v1.8. Does it support it?

Thanks.
Best regards!

**Comment by cgrinds** [comment]
It does not support 1.8. The [README.md](https://github.com/NetApp/harvest#requirements) mentions v2 is required. There were big changes on InfluxData's side that made compatibility between the two difficult.

**Comment by faguayot** [comment]
Hello @cgrinds 

I remember that in the past, you were valuing the possibility of support InfluxDB v1 but I don't know what happened with that. In our environment we don't know when our monitoring team will go to the InfluxDB V2 but it won't be in a short time. My query was because we can't integrate alerts/events in our stack.

I understand that time consumption of adapting this and maintenance is biggen than the use.

Thank you.

**Comment by cgrinds** [comment]
That's right, we made a change last year so Harvest could communicate with `1.8`. https://github.com/NetApp/harvest/issues/63 Not sure if you've tried using the `1.8` friendly URL form or if you've hit a different compatibility issue with InfluxDB. 

We can address small issues similar to #63, but it is not on our roadmap to test/validate/support InfluxDB 1.8

**Comment by faguayot** [comment]
Hello @cgrinds 

I didn't know this feature or functionality for compatibility of InfluxDB v1.8. I have tested and it works.

Thanks for share this. I understand this isn't in your roadmap and it isn't a priority.

**Comment by cgrinds** [comment]
Awesome, glad it worked for you 👍
