### ISSUE TITLE
Disk dashboard "Raid Groups" and "Plexes" panels in Highlights section are incorrect

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1374]
Caused by recent disk template change

**Comment by Hardikl** [comment]
Verified in 22.11
![image](https://user-images.githubusercontent.com/83282894/201887325-4d0cfc45-1159-48f8-a754-77dc53b60efb.png)

plex count:
![image](https://user-images.githubusercontent.com/83282894/201887422-5c588de1-0eff-4911-aa5d-b3078b8f5ea6.png)

raid group count:
![image](https://user-images.githubusercontent.com/83282894/201887497-7ab908fc-57f5-47f7-9043-27c4212af97b.png)
