### ISSUE TITLE
svm_labels are not matching Zapi/Rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1396]
Tested on AFF250

![image](https://user-images.githubusercontent.com/25551691/199531902-82da8621-ad5e-4879-bc4b-6af585a09241.png)

![image](https://user-images.githubusercontent.com/25551691/199531957-995d3b69-9ccd-41a6-b9d9-a293e0db3b40.png)

**Comment by Hardikl** [comment]
Issue1: `cifs_ntlm_enabled` label not found in REST

`cifs-security-get-iter` ZAPI mapped to `api/protocols/cifs/services` REST api as per the docs: https://library.netapp.com/ecm/ecm_download_file/ECMLP2882104
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/83282894/199923568-6dec9666-7fe1-45a1-b28a-e2ed8a7b4f4a.png">

For AFF250, 
ZAPI response: out of 7 records, 3 records have required field in it
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/83282894/199924330-c114b401-0d2c-4f01-b08e-89c7078c57ff.png">

REST response: 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/83282894/199924465-3908899f-7f51-4e3e-934a-b88cf3cd48ea.png">

Issue2: #records don't match
`vserver-get-iter` ZAPI gives all vservers [admin,system,node,data] whereas `api/svm/svms` REST gives only data svms. 
In ZAPI we have 7 records admin-1, system-1, node-2 and data-3 where REST has only 3 records.
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/83282894/199931662-c2a90a6a-ba74-46f9-beae-7ab93e236321.png">

**Comment by cgrinds** [comment]
svm_labels contains newlines
```
svm_labels{anti_ransomware_state="disabled",audit_protocol_enabled="",cifs_ntlm_enabled="",cifs_protocol_enabled="",ciphers="aes256_ctr,aes192_ctr,aes128_ctr,aes128_gcm,aes256_gcm",cluster="A250-41-42-43",datacenter="nane",fpolicy_enabled="",fpolicy_name="",iscsi_authentication_type="",iscsi_service_enabled="",ldap_session_security="",nfs_kerberos_protocol_enabled="",nfs_protocol_enabled="",nis_authentication_enabled="false",nis_domain="",ns_db="group,passwd,netgroup,namemap,hosts",ns_source="\n          files\n        ,\n          files\n        ,\n          files\n        ,\n          files\n        ,\n          files,\n          dns\n        ",smb_encryption_required="",smb_signing_required="",state="running",svm="vmware_vm"} 1.0
```

**Comment by cgrinds** [comment]
#1448 is similar to this one - that issue was about the number of `svm_labels` differing between REST and ZAPI. While that issue is fixed, if it needs to be reopened, we'll handle in this issue

**Comment by Hardikl** [comment]
**REST has the following labels that ZAPI does not have.**
Done

**REST has a different order than ZAPI for the ns_db label - these should be sorted so they match**
Done

**ZAPI and REST labels don't match**
- cifs_ntlm_enabled: Reason is `api/protocols/cifs/services` don't give data in REST
- ns_source (mentioned above)  -> Done

**Comment by cgrinds** [comment]
Confirmed all fields but `cifs_ntlm_enabled` match. Not needed for 22.08. See #1509
Verified with 22.11 build commit b37df8eb

## REST
```
svm_labels{
  anti_ransomware_state = "disabled",
  audit_protocol_enabled = "",
  cifs_ntlm_enabled = "",
  cifs_protocol_enabled = "",
  ciphers = "aes256_ctr,aes192_ctr,aes128_ctr,aes128_gcm,aes256_gcm",
  cluster = "A250-41-42-43",
  datacenter = "rest",
  fpolicy_enabled = "",
  fpolicy_name = "",
  iscsi_authentication_type = "",
  iscsi_service_enabled = "",
  ldap_session_security = "",
  nfs_kerberos_protocol_enabled = "",
  nfs_protocol_enabled = "",
  nis_authentication_enabled = "false",
  nis_domain = "",
  ns_db = "group,hosts,namemap,netgroup,passwd",
  ns_source = "dns,files,files,files,files,files",
  smb_encryption_required = "",
  smb_signing_required = "",
  state = "running",
  svm = "vmware_vm",
} 1.0
```

## ZAPI
```
svm_labels{
  anti_ransomware_state = "disabled",
  audit_protocol_enabled = "",
  cifs_ntlm_enabled = "lm_ntlm_ntlmv2_krb",
  cifs_protocol_enabled = "",
  ciphers = "aes256_ctr,aes192_ctr,aes128_ctr,aes128_gcm,aes256_gcm",
  cluster = "A250-41-42-43",
  datacenter = "rest",
  fpolicy_enabled = "",
  fpolicy_name = "",
  iscsi_authentication_type = "",
  iscsi_service_enabled = "",
  ldap_session_security = "",
  nfs_kerberos_protocol_enabled = "",
  nfs_protocol_enabled = "",
  nis_authentication_enabled = "false",
  nis_domain = "",
  ns_db = "group,hosts,namemap,netgroup,passwd",
  ns_source = "dns,files,files,files,files,files",
  smb_encryption_required = "",
  smb_signing_required = "",
  state = "running",
  svm = "vmware_vm",
} 1.0
```
