### ISSUE TITLE
missing protectedBy protectionRole labels in volume_labels Rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1397]
Tested with AFF250

![image](https://user-images.githubusercontent.com/25551691/199532510-c7e04c55-ac0a-4a32-b91b-5ac3c6b1db82.png)

![image](https://user-images.githubusercontent.com/25551691/199532725-8663bb0a-1cb8-4cd3-9f0f-6d39dbe01d38.png)

**Comment by Hardikl** [comment]
As part of the snapmirror source_cluster view, we have removed snapmirror api call from volume plugin and moved these labels [protectionRole, protectedBy, all_sm_healthy] from volume to snapmirror labels. 
https://github.com/NetApp/harvest/commit/4d7c5a7cf49c674a28fe40a49a69d873d41a46af#diff-eb14ea86460068481a9995da11e93dbd70ac14a1592722286a5bc76d22b743b1

Rest plugin have those changes but missed from zapi. 

Working on them.
