### ISSUE TITLE
missing aggr metrics in Rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1401]
Possibly verified earlier but needs to be rechecked with AFF250 9.12

aggr_hybrid_cache_size_total 
aggr_snapshot_inode_used_percent  (used in dashboard)
aggr_space_reserved 
aggr_space_used_percent (used in dashboard)

**Comment by cgrinds** [comment]
Check if `aggr_snapshot_inode_used_percent` or `aggr_space_reserved` are available via private CLI. If not, close.

**Comment by Hardikl** [comment]
Checked on 9.12.1 cluster `10.193.48.154`, 
Both the above fields `aggr_snapshot_inode_used_percent` and `aggr_space_reserved` aren't available via private CLI (api/private/cli/storage/aggregate).
