### ISSUE TITLE
History and Metrics for Snapmirror Relationships

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1408]
### Discussed in https://github.com/NetApp/harvest/discussions/1402

<div type='discussions-op-text'>

<sup>Originally posted by **KlausHub** November  2, 2022</sup>
Hi again,
i am running on 22.08 and tried to get some more info on specific (XDP-Volume) Snapmirror Relations.
![image](https://user-images.githubusercontent.com/97510878/199542536-14d0f038-72c8-4820-a213-bd7e0dc5087f.png)

After clicking on one off  the Relationsships/Volumes, i get a not found error/info.
![image](https://user-images.githubusercontent.com/97510878/199541857-d5bbd137-12a7-4924-b31b-c876a1e4da89.png)

many thanks in advance for your Feedback and Help on that.

Best Regards,
Klaus</div>

**Comment by cgrinds** [comment]
Verified with 22.11 build commit 6d5f6a48
The SnapMirror dashboard `Last Transfers` table
- includes `Source Cluster` and `Destination Cluster` columns
- does not have an `ID` column
