### ISSUE TITLE
InvokeRequestString method should only be used for cluster scoped zapi request

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1419]
Shelf plugin uses InvokeRequestString method which doesn't do batching. This will impact shelf metrics. We should also check any other place for similiar issue.

https://github.com/NetApp/harvest/blob/main/cmd/collectors/zapi/plugins/shelf/shelf.go#L158

**Comment by Hardikl** [comment]
we will remove `InvokeRequest` as well which also doesn't do batching.

**Comment by cgrinds** [comment]
Verified with 22.11 build commit 6d5f6a48

`shelf.go` now calls the batching InvokeZapiCall method
