### ISSUE TITLE
Add information about the resources defined by every policy-group (QoS)

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#1426]
**Is your feature request related to a problem? Please describe.**

We would like to have the QoS policy-group information in the database that information we will give us the possibility of alerting when the file are reaching the limit of IOPS assigned for that workload. Additionally, it is possible to create a percentage of the use of every workload?

**Describe the solution you'd like**

The query from ONTAP CLI for get the information requested is:
`qos policy-group show
`

![image](https://user-images.githubusercontent.com/85484449/200574090-7cb40c30-bcca-4c82-b546-38a11a407742.png)

For the "**Throughput**" would be desirable to have split this field in two, one for mininum IOPS assigned (it is the first number) and the another for the maximum IOPS assigned (it is the second number after the hyphen)

**Comment by cgrinds** [comment]
hi @faguayot yes, we'll add that and yes, the xput and iops will be separated into their own fields. Can you add more details on what you mean by 
>  it is possible to create a percentage of the use of every workload?

**What are the numerator and denominator of this percentage?**

This object requires a bit more work than some of the others because of how qos polices are split between adaptive and fixed. Harvest will handle both, but we may deliver the changes in stages. **If we do deliver in stages - does fixed, adaptive, or both best match you current needs?** 

Here's our current thinking. On the ZAPI side, there are two different ZAPIs: `qos-policy-group-get-iter` and `qos-adaptive-policy-group-get-iter`. REST combines both of those together into `qos/policies`. Adaptive and fixed SLOs are mutually exclusive on the ONTAP side.

Harvest will export two metrics: `qosp_fixed` and `qosp_adaptive`. There will be two ZAPI templates with a plugin to format the xput and iops, and there will be one REST template that publishes identical metrics.

**Comment by faguayot** [comment]
Hello @cgrinds,

I'm going to use an example to explain you how we would like to have the field "**Throughput**"  splitted in two fields. Take a look of my previous image and see the first qos **policy-group** named `openstack-059...` if you check the field "**Throughput**" will be the following value: `0-9600IOPS` and my question was if it is possible to split that value into two for example like this: mininumIOPS = 0 and maxixumIOPS = 9600.  (don't use my horribles names for that purpose :))

Related to my other question about the calculation of percentage **QOS** used, the way to obtain the % is using the `qos_ops` metric (get when we activate the workload objects in harvest) and the qos defined in the policy applied to that workload which we will get with: `qos policy-group show`.

**_Percentage calculation_** =  `currentiops_byworkload x 100 / maxiops_byworkload`

If it is possible to have the percentage of workload use, in which metric do you think it will better to have? Because in my mind, it will be easier to have for future use in the same metric that `qos_ops`.

For us I guess that both qos are useful but maybe in a first step we were thinking on the `qosp_fixed`.

Let me know if I explained better or if you need any other clarification by my side. Thanks so much for you continue help and your open mind for the new integrations.

**Comment by cgrinds** [comment]
Thanks! That helps.

In terms of splitting, I don't think that's necessary since ZAPI and REST return a `min-throughput` and a `max-throughput`. My guess is the CLI output chose a different format to communicate the same thing. Just checked, and yeah, that seems to be the case if you ask for min and max individually.
```
ocum-infinity::> qos policy-group show -fields "policy-group,class,min-throughput,max-throughput,throughput-policy"
policy-group           class        max-throughput min-throughput throughput-policy
---------------------- ------------ -------------- -------------- -------------------
NSLM_LUN_1579633498796 user-defined 61388IOPS      14400IOPS      14400IOPS-61388IOPS
NSLM_LUN_1579633499146 user-defined 57062IOPS      13945IOPS      13945IOPS-57062IOPS
NSLM_VOL_1571973651802 user-defined 601IOPS        0              0-601IOPS
```

Either way, we'll make it work and align ZAPI and REST. The plan is to use the same "shape" as [REST](https://library.netapp.com/ecmdocs/ECMLP2882307/html/#/storage/qos_policy_collection_get) (pasted below). 

The ZAPI collector will use the same shape and names as the REST collector, that way Harvest will export the exact same metric.

Appreciate the details on % calculation, that makes sense, and yeah I like `qos_ops` too. We'll need to take a look. Since this calculation requires several ZAPI calls to calculate, we'll probably need to build a plugin that does that.

```json
# Adaptive Example
{
      "svm": {
        "name": "vs5_nfs_cifs"
      },
      "name": "NSLM_vs5_nfs_cifs_Value_17_0",
      "adaptive": {
        "expected_iops": 128,
        "peak_iops": 512,
        "absolute_min_iops": 59,
        "block_size": "any",
        "expected_iops_allocation": "allocated_space",
        "peak_iops_allocation": "used_space"
      },
      "object_count": 6,
      "policy_class": "user_defined",
      "scope": "svm",
}

# Fixed Example
{
      "svm": {
        "name": "vs3_cifs"
      },
      "name": "pg_nfs_17",
      "fixed": {
        "max_throughput_iops": 56808,
        "min_throughput_iops": 15126,
      },
      "object_count": 0,
      "policy_class": "user_defined",
      "scope": "svm",
}
```

**Comment by faguayot** [comment]
Hello @cgrinds, 

I would like to add some example that we have in our storage array, if you see the first line appear the **throughput** and the **IOPS**

```
qos policy-group show -fields min-throughput,max-throughput,throughput-policy,pgid,num-workloads,policy-group,class
policy-group  class        pgid max-throughput     min-throughput num-workloads throughput-policy    
------------- ------------ ---- ------------------ -------------- ------------- -------------------- 
extreme-fixed user-defined 557  50000IOPS,1.53GB/s 0              0             0-50000IOPS,1.53GB/s 
openstack-059790fd-36e5-4648-91b8-fbe69d3f30ec user-defined 9178 9600IOPS 0 1   0-9600IOPS           
openstack-07e3d197-d3be-4f20-aaef-03f7f12b92d6 user-defined 593 2880IOPS 0 0    0-2880IOPS           
openstack-0a99711a-ea01-4059-8951-060b4e86f1a8 user-defined 9112 960IOPS 0 1    0-960IOPS            
openstack-0b2d71c0-70fa-4358-a7ad-5a4366fd5d2c user-defined 10886 6144IOPS 0 1  0-6144IOPS           
openstack-0b6d365f-dea0-4399-8a7e-7e8da4bbbaa5 user-defined 13002 1200IOPS 0 1  0-1200IOPS 
```

We don't use that but it is possible to have a qos-policy taking into account both parameters. Only as a informational, maybe it is helpful for you when you can work in this.

Thank you Chris.

**Comment by cgrinds** [comment]
hi @faguayot yes we'll handle both forms and align with REST

**Comment by faguayot** [comment]
Hello @cgrinds, 
How this issue is going? 
I want to ask you if there is the adaptative qos policies enabled on the last release 23.02 or how can we enable to have values from this metric?

**Comment by cgrinds** [comment]
hi @faguayot these changes did not make the 23.02 release, but will be included in 23.05. If you're able to try a nightly, we can get you something sooner. Would that work?

**Comment by faguayot** [comment]
Hello @cgrinds,

Yes, I could try with the nightly deployment in a machine dedicate for the previous environment (development). Let me know when you have the implementation available and I will try it. 

Thanks for your quick response.

**Comment by cgrinds** [comment]
@faguayot changes for fixed QoS policy groups are delivered in #1831 - this includes the parsing and publishing of fixed as discussed above.

These changes will be included in nightly after 2023-03-21 1am EDT. When you get a chance, please take a look. This does not yet include any percentage calculation.

**Comment by faguayot** [comment]
Hello @cgrinds 

I am testing the nightly release, it is appear a new metric: `qos_policy_fixed_labels` and on the other hand existing metrics:  `qos_ops`, `qos_total_data` and `qos_detail_volume_resource_latency` are collecting new information (policy-group, worload,wid,etc).

**Fixed QoS**
![image](https://user-images.githubusercontent.com/85484449/226879985-9c7f3a32-b587-40d7-85e0-c27beca51a69.png)

**Adaptative QoS**
![image](https://user-images.githubusercontent.com/85484449/226879812-ccd46726-e7b6-45e9-87c5-2406a27f03cc.png)

This is the new metric information for this example:
![image](https://user-images.githubusercontent.com/85484449/226878160-f2c2f30a-45f1-47e5-806b-69c6d974726c.png)

It looks great in general (thanks @cgrinds, @rahulguptajss and the rest of the team), but I am missing information from some clusters which have enabled the adaptative QoS but I can't find the information in `qos_policy_fixed_labels` for those clusters. The differences between the other cluster which are working and those are the ONTAP version 9.7 vs 9.10.1 (in the cluster which are working). Do I have to make any additional modification?

![image](https://user-images.githubusercontent.com/85484449/226886646-bfd195c8-ea3f-47cc-bde3-28cde042864e.png)

I have another doubt related with the REST and ZAPI, I would prefer to use REST when it is possible instead of ZAPI on every cluster. Do I have to put the collectors in my **harvest.yml** right? 

```
cluster-1:
    datacenter: dc-1
    addr: 10.1.1.1
    collectors:
        - Zapi
        - Rest
```

**Comment by faguayot** [comment]
Ohhh you are right, sorry I didn't realize about the **fixed** that you mentioned. My fault becauseI was happy and excited with the news that I didn't read correctly.

Thanks for clarify me, I read that in the documentation but I wanted to be sure abour the "**`Collectors`**" section since I didn't have that information in my previous harvest.yml file.

Related with the **adaptative-qos**, we aren't collecting yet the limits for every policy but with the new  nightliy version we are gathering the adaptative-policies or these were working from previous version? Because I am not sure now what were the changes here? There was any additional implementation to the new metric "**`qos_policy_fixed_labels`**"? 

Thank you for your help.

**Comment by faguayot** [comment]
Yes chris, that is what I understood in the last message but I wanted to be sure. Thanks.

Please, when you have prepared the same metrics por the **`adaptative`** QoS advice me and I will deploy again the version with the changes for trying.

**Comment by faguayot** [comment]
Hello @cgrinds ,

These information for us it's very valuable, but now I am trying to display on a Grafana dashboard. 

![image](https://user-images.githubusercontent.com/85484449/228193617-902b6916-12e2-4521-b112-791334c51034.png)

I don't know how to join the information of **`qos_ops`** with the information of the **`qos_policy_adaptive_labels`** or **`qos_policy_fixed_labels`** in a table and a graph. My intention is to look for the **_top workloads_** and draw the behaviour for those workloads and with the limit. With this graph I can check if any workload  exceeds the load allowed by the limit (qos). Additionally I would like to have in a table the max values for the top workloads and the maximum value allow for that workload. This information is neccesary to check if we are falling short with the QoS allocation or the opposite. With this feature we can adjust a new workload in accurate way.

Thanks.

**Comment by cgrinds** [comment]
hi @faguayot @rahulguptajss took a look at this join yesterday and came up with this. Can you give this a try? 

```
qos_ops * on(svm,cluster,policy_group) group_left(max_throughput_iops,max_throughput_mbps,min_throughput_iops,min_throughput_mbps) label_replace(qos_policy_fixed_labels, "policy_group", "$1", "name", "(.*)")
```

Another thing to try since you mentioned top workloads. We recently added (March 22) a `Workload` dashboard that includes top workloads.

**Comment by faguayot** [comment]
Hello @cgrinds, 

Thanks for your help, I was struggling with the query because I've never used union of two different metric which additionally have to replace a label by the policy to fint the match between both metrics. I was really close of the success, so with your help I could draw a table with all the information. I need to check in more detail, because probably I am not sure which information will be more useful to use for filter and to show (peak, avg,etc).

Also, I would like to have the topk for some file or lun with the limit by every file or lun in a graph.

Related to the workload: Yes, I have the **`Delay Center`** dashboard that I think it is the same that **`Workload`**.

**Comment by cgrinds** [comment]
hi @faguayot were you able to make progress on the join or any other thoughts on the functionality provided so far? I think everything is included except for the percentage calculation. Do you see any other gaps?

**Comment by faguayot** [comment]
Hi @cgrinds 
I didn't do anything else because I didn't have time to review this. I would like to check when I can, how can I get a query which show the peak information for a workload and its maximum performance assign in the policy for the specific workload.

Thanks.

**Comment by Hardikl** [comment]
Hi @faguayot 

We do have all the required labels in `qos_ops` and `qos_policy_adaptive_labels` metric for QoS calculations which you are interested for. And all the arithmetic operations on labels are working in Grafana. 

Just for example of arithmetic operations in Grafana by applying transformations, I have used `expected_iops` and `peak_iops` labels for calculation. And yes, we can change the formula as per the use-case and need. 

```
qos_ops{datacenter=~"$Datacenter", cluster=~"$Cluster", svm=~"$SVM"} * on(cluster,svm,policy_group) group_left(peak_iops,expected_iops) label_replace(qos_policy_adaptive_labels{datacenter=~"$Datacenter", cluster=~"$Cluster", svm=~"$SVM"}, "policy_group", "$1", "name", "(.*)")
```

Screenshot1: Query with result
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/83282894/236176532-cb9ec255-83bc-4a28-a05c-d00d451a722c.png">


Screenshot2: Transformations detail
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/83282894/236176736-ba407808-16f5-40fb-9d62-89ab5ad95a1c.png">

If you would like to check this example changes in your system, then [Here](https://gist.github.com/Hardikl/653cfd033828e7f732aac9241ccab14b) is the panel json changes for that.

**Comment by faguayot** [comment]
Hello @rahulguptajss, 

Sorry I was out of office. I was checking with my colleague and I think your proposal is good for achieve the information that we required to draw in graphs.
Let me know when you can implemented to have the chance to try and show you the information.

Thanks so much for your comprenhension.

Best regards!

**Comment by faguayot** [comment]
I am trying to test the new metrics in qos, here an example of the qos_ops for different workloads (files), in the graph you can see a workload with exceeds the maximum limit for a while.

**EXAMPLE**:
![image](https://github.com/NetApp/harvest/assets/85484449/6b392a98-6a65-42f2-bf89-32a38ee1a050)

This type of behaviour are that we want to find with these parameters. We will continue testing and creating new dashboard with relevant information for us, but we need time to think how we can watch the information.

**Comment by faguayot** [comment]
Hello @rahulguptajss 

Sorry, I didn't have time to work in this recently so I couldn't design new dashboards with value for us to share. Apologize for that.

Today, I was checking and it came a doubt to me, it is possible to have the file name in the new metrics created like we have the **policy_group** (called name)? This request is because in our use case sometimes we managed migrations of the files (cinder volumes) that trigger a change and the matching between the policy_group and the file stop to exist.
 a so the policy_group and the file name don't match.

Let me show you an example:

![image](https://github.com/NetApp/harvest/assets/85484449/d74dc4a2-47cf-4959-8968-01230f41ffb5)

If you review both files (the lines in the screenshot), in one case the name for the file/volume is the same that the policy `openstack-...` and in the other no. So if we don't have the equivalence between file and policy_group in the same metric, we can't use it. In our plafform we require to use the file instead the policy_group to filter or find the behavior for the resource.

Excuse me if I extended

Thanks.

**Comment by faguayot** [comment]
@rahulguptajss The problem is we need to filter the queries using the **file** information and that information doesn't exist on the **qos_policy_fixed_max_throughput_iops**. 

![image](https://github.com/NetApp/harvest/assets/85484449/9d6c9ba1-b6f1-4eb8-987a-68b34fa646e1)

If you check the name for the `cinder-volume` (is an alias for the **file**) and the `policy`, it should be the same `ID` in all the cases but it isn't like that in many because different reasons, so it would be helpful if you add the file information in the new metrics like `qos_policy_fixed_max_throughput_iops`. Sorry because maybe I am not explaining very well.

**Comment by faguayot** [comment]
Hello @rahulguptajss 

I understood what you said, sorry I was thinking in our current scenary which the relationship of a qos_policy is one per resource/workload (1:1) and I didn't realize that wasn't the norm for every use. 

Now I achieved what I was looking for (thanks for your help)

- Table for fixed and adaptative (I need some help for improve the gauge, if you see the dashboard doesn't fill the area correspondant with the percent used)
![image](https://github.com/NetApp/harvest/assets/85484449/5f60f539-3d55-422b-976d-80150a1ab25d)

- Example of fixed qos for a file with infinitive qos, another with a specific qos and the last a file which the name for the file and policy doesn't match.
![image](https://github.com/NetApp/harvest/assets/85484449/6ca6f4ae-b5a6-4443-a771-29055bda54f2)

- Example of adaptative qos
![image](https://github.com/NetApp/harvest/assets/85484449/640e31ec-a72f-4228-999b-e764e0f4c37f)

Take a look and let me know if this information could be helpful for you since it is something customized for our env and use. If you want the dashboard, how can I share with you?

**Comment by faguayot** [comment]
Great. I have sent the email with the dashboard.

**Comment by cgrinds** [comment]
We'll open a separate issue for incorporating the dashboard @faguayot contributed. This issue can be closed

**Comment by faguayot** [comment]
Hello    @rahulguptajss 

As you can appreciate in this image, we get the result that we were looking for. We have found and instance (VM) which is consuming the whole provisioned policy of IOPS (QoS). 

![image](https://github.com/NetApp/harvest/assets/85484449/d3c430a4-6aa0-4aac-909a-23b2eff68257)

Furthermore in this graph we can see during how long time was occurring that event since the percentage of image is an average right?
![image](https://github.com/NetApp/harvest/assets/85484449/579318b3-5e58-4d5c-be17-0a9e4428e43a)

Additionally we were taking a look at the other graphs and we have a doubt what it is "Service Latency by resource"? What kind of metric is that and what does it measure? I don't know how can I find the measure in the harvest to get information about that.

Thanks so much.
