### ISSUE TITLE
ONTAP: Disk Dashboard - Variables are not sorted

### ISSUE THREAD

**Issue by Falcon667** [NetApp/harvest#1442]
**Describe the bug**
The sort function in the variables from the disk dashboard is disabled compare to other dashboards e.g. Node

**Environment**
- Harvest version: 22.08
- Install method: NABox
- ONTAP Version: 9.9.1P6

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/99657787/201104156-97fe47b4-c2fe-4f1a-802b-730821142e90.png)

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/99657787/201104073-5e94732f-4144-412f-b79f-bbdc58569376.png)

**Possible solution, workaround, fix**
Change the sort function to Alphabetical (asc)

**Comment by cgrinds** [comment]
Thanks for reporting @Falcon667. This is fixed in #1443, you can import that json directly if you want the fix now, otherwise it will be in tonight's [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).
