### ISSUE TITLE
shelf labels zapi rest mismatch

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1446]
ZAPI -> REST

shelf_voltage_labels status _1.1_2 normal -> ok
shelf_voltage_labels status _1.1_3 normal -> ok
shelf_voltage_labels status _1.1_4 normal -> ok
shelf_voltage_labels status _1.1_1 normal -> ok
shelf_temperature_labels status _1.1_6 normal -> ok
shelf_temperature_labels status _1.1_8 normal -> ok
shelf_temperature_labels status _1.1_11 normal -> ok
shelf_temperature_labels status _1.1_7 normal -> ok
shelf_temperature_labels status _1.1_9 normal -> ok
shelf_temperature_labels status _1.1_2 normal -> ok
shelf_temperature_labels status _1.1_5 normal -> ok
shelf_temperature_labels status _1.1_1 normal -> ok
shelf_temperature_labels status _1.1_3 normal -> ok
shelf_temperature_labels status _1.1_4 normal -> ok
shelf_temperature_labels status _1.1_10 normal -> ok
shelf_fan_labels status _1 normal -> ok
shelf_fan_labels status _2 normal -> ok
shelf_fan_labels status _3 normal -> ok
shelf_fan_labels status _4 normal -> ok
shelf_psu_labels status _1 normal -> ok
shelf_psu_labels status _2 normal -> ok
shelf_sensor_labels status _1.1_1 normal -> ok
shelf_sensor_labels status _1.1_2 normal -> ok
shelf_sensor_labels status _1.1_3 normal -> ok
shelf_sensor_labels status _1.1_4 normal -> ok

**Comment by Hardikl** [comment]
Fan:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/83282894/201319433-2b254be0-6684-4dfb-a022-a1b7c552e05d.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/83282894/201319472-ffc883d9-e536-48cb-88be-6ec7e6ba24a9.png">

Voltage:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/83282894/201319543-33395bb7-2a46-4c94-a82c-5f222a2def0c.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/83282894/201319604-888dfa3b-c3d5-436b-979b-cb659b270b6b.png">

Tempreture:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/83282894/201319668-9fa603dc-2680-4e8f-ba04-1c3724168c8a.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/83282894/201319717-2c30c1a6-f870-4b7a-a1c2-dcab39a643d2.png">

Current:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/83282894/201319816-23dc4ef5-a69c-4cd5-acc6-7a7695f6380f.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/83282894/201319875-59ba0411-01cf-4df1-bfe7-c86402c3f528.png">

PSU:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/83282894/201319951-201ca80a-bebf-416e-a23b-04f850b3d3dc.png">

<img width="998" alt="image" src="https://user-images.githubusercontent.com/83282894/201320196-c8d94ecb-6061-4579-9016-a3f1af5fbe40.png">

Needs plugin changes, Working on it.
