### ISSUE TITLE
svm_labels count do not match Rest vs Zapi

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1448]
![image](https://user-images.githubusercontent.com/25551691/201320153-ff420314-3e59-4076-bdfb-0c1500d13c1e.png)

![image](https://user-images.githubusercontent.com/25551691/201320255-c11284f7-5892-4edf-94e2-e68ce32a5c3e.png)

**Comment by Hardikl** [comment]
svm records don't match:
`vserver-get-iter` ZAPI gives all vservers [admin,system,node,data] whereas `api/svm/svms` REST gives only data svms. 
In ZAPI we have 7 records admin-1, system-1, node-2 and data-3 where REST has only 3 records.
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/83282894/199931662-c2a90a6a-ba74-46f9-beae-7ab93e236321.png">

**Comment by Hardikl** [comment]
This should be documented in our docs, because the customer might be consuming the non-data svms as well and that would be impacted.

**Comment by cgrinds** [comment]
This is a duplicate of #1396 - continue work there
