### ISSUE TITLE
shelf_psu_labels is missing location in labels in Rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1449]

**Comment by Hardikl** [comment]
There is no `location` field available in psu in frus in REST.
 
![image](https://user-images.githubusercontent.com/83282894/201669352-af4de937-d4c6-4f30-86fc-d45b2a528205.png)

 shelf_psu_labels and specifically location is not consumed in dashboard, so we don't have dashboard impact.

**Comment by ruanruijuan** [comment]
In the zapi_to_rest_mappings/storage-shelf.xml
psu-location -> NA +
There is no mapping for location. Do we want ONTAP to provide that?
