### ISSUE TITLE
Gaps in cluster_new_status data

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1472]
![image](https://user-images.githubusercontent.com/25551691/201887440-c52d3f6c-8577-4410-84e8-0e6afb485476.png)

**Comment by Hardikl** [comment]
Seems little odd as one poll we have new_status metric data and next poll we don't.
![image](https://user-images.githubusercontent.com/83282894/201926995-d3c5c752-bceb-4d98-bce2-74db79ea51ed.png)

![image](https://user-images.githubusercontent.com/83282894/201927029-140cf7f0-5e1b-4c8e-a3f9-fbef6cb4e6ee.png)
