### ISSUE TITLE
Add more metrics to Grafana dashboards

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#15]
The current set of Prometheus dashboards display a small fraction of the metrics Harvest collects.
We should consider:
* culling metrics we don't plan on ever displaying
* add useful ones to existing dashboards
* make it easy for customers to decide on their own

**Comment by vgratian** [comment]
I am working on this, I will commit new dashboards set in a couple of days

**Comment by cgrinds** [comment]
Covered
