### ISSUE TITLE
SVM metrics panel, Volume Metric panel in cdot dashboard do not load in grafana 8.3+

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1512]
![image](https://user-images.githubusercontent.com/25551691/202653130-f5065a56-6de7-40de-811e-b4cb9084e084.png)

Refer

http://10.195.64.86:3000/d/8sNGleDVk/ontap-cdot?orgId=1&from=now-15m&to=now

**Comment by Hardikl** [comment]
It's failed to load panels in 8.3.x grafana while it's loading on 8.4.x grafana due to exemplar queries.
Found few grafana issue fixes:
https://github.com/grafana/grafana/pull/42915
https://github.com/grafana/grafana/pull/42749

Working on the version check
