### ISSUE TITLE
Add "Harvest Upgrade steps" to README file

### ISSUE THREAD

**Issue by sridevimm** [NetApp/harvest#152]
**Describe the bug**
Add "Harvest Upgrade steps" to README file

**Environment**
All packages

- Harvest version: harvest-21.06.1121
- Command line arguments used: NA
- OS: All supported OS
- Install method: [yum, rhel, native, docker]
- ONTAP Version: [e.g. 9.7, 9.8, 9.9, 7mode]
- Other:

**To Reproduce**
Check README file

**Expected behavior**
README file should have steps to upgrade Harvest

**Actual behavior**
Currently we have steps only for installation and not upgrade

**Possible solution, workaround, fix**
Update README file

**Comment by cgrinds** [comment]
Closed by #155
