### ISSUE TITLE
docs: add configure StorageGRID collector section

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1530]
https://netapp.github.io/harvest/configure-storagegrid/

**Comment by erikgruetter** [comment]
Hi @cgrinds, just wanted to let you know this is something that a lot of customers would appreciate, including me. :)

Regards
Erik

**Comment by cgrinds** [comment]
hi @erikgruetter awesome! docs updated, take a look and let us know if you have questions

**Comment by erikgruetter** [comment]
Looks great so far @cgrinds! Are there any plans on documenting how to do that on NAbox? I managed to get it working on NAbox but I think it is a different way to do it there compared to just Harvest.

**Comment by cgrinds** [comment]
@ybizeul can you include these steps to NAbox's documentation?

**Comment by cgrinds** [comment]
See nabox release [notes](https://nabox.org/changelogs/v3_3b1/) StorageGRID dashboards and initial support for adding clusters is available as of `v3.3b1`
