### ISSUE TITLE
ONTAP: SVM Dashboard - Virus scan connections wrong scale

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#1550]
**Describe the bug**
In the Virus Scan Connections Active panel the sacle is logarithmic base 2 instead of linear. When there is no connection the timeseries still shows one connection left
![grafik](https://user-images.githubusercontent.com/99657787/204279343-f49cc3fa-f95f-4b10-990d-7829d223f969.png)

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: 22.11
- Install method: NABox
- ONTAP Version: 9.9.1 P6

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/99657787/204279113-84c21565-0141-4cf7-8f31-8283a7bf1f80.png)

**Comment by Hardikl** [comment]
Verified in 23.03.

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/83282894/218394801-9e3b7129-75d4-4bf8-b8c0-69ebf5164c66.png">
