### ISSUE TITLE
`bin/grafana` CLI message about overwrite

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1573]
as reported by jfong on [Discord](https://discord.com/channels/855068651522490400/1047198275477979196/1047580130341572608) 

Clarify what overwrite does
> maybe better explained in the error message with --overwrite will import but with a new version number

**Comment by Hardikl** [comment]
Verified in 23.02.

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/83282894/218395655-0cbbe5e9-78c2-4644-b531-c53e370e9680.png">
