### ISSUE TITLE
shelf_fan_status does not match between zapi/rest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1584]
![image](https://user-images.githubusercontent.com/25551691/205634785-95110fa7-4020-4607-b07d-d27cef8b7a39.png)

**Comment by Hardikl** [comment]
one of them is zapi and other is rest.
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/83282894/205646528-17ec4ca6-00a4-4cf8-91be-ce9bfa8fd51b.png">


`location` and `status` labels should exist in both zapi and rest.

**Comment by cgrinds** [comment]
Verified in `23.02`
Compared the `shelf_fan_status` metric published by these two pollers:

```
bin/poller --poller sar --promPort 12991 --collectors Rest,RestPerf --objects Shelf,Disk
HARVEST_NO_COLLECTOR_UPGRADE=1 bin/poller --poller sar --promPort 12990 --objects Shelf,Disk
```
