### ISSUE TITLE
shelf_psu_status does not match between rest/zapi

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1585]
![image](https://user-images.githubusercontent.com/25551691/205634992-f09593ca-03c0-4911-a3c0-6dc96ad9263e.png)

**Comment by cgrinds** [comment]
Verified in `23.02`
Compared the `shelf_psu_status` metric published by these two pollers - they are identical

```
bin/poller --poller sar --promPort 12991 --collectors Rest,RestPerf --objects Shelf,Disk
HARVEST_NO_COLLECTOR_UPGRADE=1 bin/poller --poller sar --promPort 12990 --objects Shelf,Disk
```
