### ISSUE TITLE
shelf_temperature_status doesn't match between rest/zapi

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1586]
![image](https://user-images.githubusercontent.com/25551691/205635188-2d0ebef7-27b5-4df9-bd72-cc2af7ba837f.png)

**Comment by cgrinds** [comment]
Verified in `23.02`
Compared the `shelf_temperature_status` metric published by these two pollers - they are identical

```
bin/poller --poller sar --promPort 12991 --collectors Rest,RestPerf --objects Shelf,Disk
HARVEST_NO_COLLECTOR_UPGRADE=1 bin/poller --poller sar --promPort 12990 --objects Shelf,Disk
```
