### ISSUE TITLE
shelf_sensor_status doesn't match between rest/zapi

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1587]
![image](https://user-images.githubusercontent.com/25551691/205635296-78b0865b-98d3-4fab-9b9e-903f9453d43b.png)

**Comment by cgrinds** [comment]
Verified in `23.02`
Compared the `shelf_sensor_status` metric published by these two pollers - they are identical

```
bin/poller --poller sar --promPort 12991 --collectors Rest,RestPerf --objects Shelf,Disk
HARVEST_NO_COLLECTOR_UPGRADE=1 bin/poller --poller sar --promPort 12990 --objects Shelf,Disk
```
