### ISSUE TITLE
Create harvest doctor to validate customer environments

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#16]
Similar to `brew doctor` and support bundle. Collect information, validate, and present to customer.
Compress and offer to share.

Ideas:
* validate yaml
* verify harvest is or is not running
* verify that Prometheus is or is not reachable
* verify permissions
* verify credentials
* hit the Prometheus endpoint(s) and show results
* check versions of Prometheus, Grafana, InfluxDB, OS, and embedded release/commit/build date
* validate `/var/run/harvest` [permissions](https://github.com/NetApp/harvest/issues/122)

Extract what's reasonable from [Troubleshooting Harvest](https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest) automate and/or include

**Comment by cgrinds** [comment]
- [ ] Update documentation

**Comment by cgrinds** [comment]
Validate by running `bin/harvest doctor --print`. Make sure all sensitive information is redacted.
Running `bin/harvest doctor --config bad.yml` should validate and print line number and error for bad yaml file.

**Comment by rajeshl8** [comment]
Validated harvest doctor and it works great and nice feature. Observed below issue.
bin/harvest doctor --print
Observation , it prints all information and redacted most of the sensitive information except for poller username. It marked username key as redacted instead of actual username value. [It might have happened due to auth_style: password, password was one of the sensitive key we are checking for redacted]
root@scspa2385980005 harvest-21.06.0801-nightly_linux_amd64]# bin/harvest doctor --print
Exporters:
    prometheus1:
        exporter: Prometheus
        addr: -REDACTED-
        port: 12992
    prometheus2:
        exporter: Prometheus
        addr: -REDACTED-
        port: 12991
    prometheus4:
        exporter: Prometheus
        addr: -REDACTED-
        port: 12994
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
    use_insecure_tls: true
Pollers:
    umeng_aff300:
        datacenter: umeng_aff300
        addr: -REDACTED-
        auth_style: password
        -REDACTED-: admin
        password: -REDACTED-
        exporters:
            - prometheus1
Note : rename the file yml.
[harvest.txt](https://github.com/NetApp/harvest/files/6623734/harvest.txt)

**Comment by rajeshl8** [comment]
Verified the issue using below build and everything works as expected.
[root@scspa2398581002 harvest]# ./bin/harvest -v
harvest version 21.06.1121-nightly (commit 1524ebb) (build date 2021-06-11T21:11:15+0530) linux/amd64
[root@scspa2398581002 harvest]# ./bin/harvest doctor --print
Exporters:
    prometheus1:
        exporter: Prometheus
        addr: -REDACTED-
        port: 16992
    prometheus2:
        exporter: Prometheus
        addr: -REDACTED-
        port: 16991
    prometheus4:
        exporter: Prometheus
        addr: -REDACTED-
        port: 16994
Defaults:
    collectors:
        - Zapi
        - ZapiPerf
    use_insecure_tls: true
Pollers:
    umeng_aff300_lr22:
        datacenter: umeng_aff300_lr22
        addr: -REDACTED-
        auth_style: password
        username: -REDACTED-
        password: -REDACTED-
        exporters:
            - prometheus1
    F2240-127-26_lr22:
        datacenter: F2240-127-26_lr22
        addr: -REDACTED-
        auth_style: password
        username: -REDACTED-
        password: -REDACTED-
        exporters:
            - prometheus2
    fas8060-39-239-241_lr22:
        datacenter: fas8060-39-239-241_lr22
        addr: -REDACTED-
        auth_style: password
        username: -REDACTED-
        password: -REDACTED-
        exporters:
            - prometheus4
Tools:
    grafana_api_token: -REDACTED-

[root@scspa2398581002 harvest]#
