### ISSUE TITLE
Harvest stopped reporting some qtree metrics

### ISSUE THREAD

**Issue by mwas01** [NetApp/harvest#1640]
**Describe the bug**
Harvest stopped exposing metrics for qtree_disk_used. It was serving them until last week and they suddenly disappeared. All other metrics are exposed ok. I manually verified that qtree data is available to harvest used via ONTAP API.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 22.08.0-1 (commit 93db10a) (build date 2022-08-19T09:10:05-0400) linux/amd64
- Command line arguments used: `bin/harvest start`]
- OS: RHEL7.8
- Install method: native
- ONTAP Version: 9.8
- Other:

**To Reproduce**
Conf files: 
harvest.yml 
`Tools:

Admin:
  httpsd:
    listen: :12999
Exporters:
  prometheus:
    exporter: Prometheus
    local_http_addr: 0.0.0.0
    port_range: 12991-12998
Defaults:
  collectors:
    - Zapi
    - ZapiPerf
  use_insecure_tls: true
Pollers:
  sero11:
    datacenter: gic-sero
    addr: <addrs>
    auth_style: certificate_auth
    ssl_cert: /path/to/harvest.pem
    ssl_key: /path/to/harvest.key
    exporters:
      - prometheus`

zapi/defaut.yaml
`collector:          Zapi

schedule:
  - instance: 600s
  - data: 180s
objects:
  Aggregate:                   aggr.yaml
  AggregateEfficiency:         aggr_efficiency.yaml
  ClusterPeer:                 clusterpeer.yaml
  Disk:                        disk.yaml
  Lun:                         lun.yaml
  Node:                        node.yaml
  NtpServer:                   ntpserver.yaml
  Qtree:                       qtree.yaml
  Security:                    security.yaml
  SecurityAccount:             security_account.yaml
  SecurityAuditDestination:    security_audit_dest.yaml
  SecurityCert:                security_certificate.yaml
  SecurityLogin:               security_login.yaml
  Sensor:                      sensor.yaml
  Shelf:                       shelf.yaml
  SnapMirror:                  snapmirror.yaml
  SnapshotPolicy:              snapshotPolicy.yaml
  Status:                      status.yaml
  Status_7mode:                status_7.yaml
  Subsystem:                   subsystem.yaml
  Support:                     support.yaml
  SVM:                         svm.yaml
  Volume:                      volume.yaml`

qtree.yaml
`name:                 Qtree
query:                qtree-list-iter
object:               qtree
client_timeout: 2m
counters:
  qtree-info:
    - ^export-policy
    - ^oplocks
    - ^security-style
    - ^status
    - ^^volume
    - ^^vserver => svm
    - ^^qtree   => qtree
collect_only_labels: true
plugins:
  - LabelAgent:
      exclude_equals:
        - qtree ``
  - Qtree:
      objects:
        - disk-limit
        - disk-used
        - disk-used-pct-disk-limit
        - disk-used-pct-soft-disk-limit
        - disk-used-pct-threshold
        - file-limit
        - files-used
        - files-used-pct-file-limit
        - files-used-pct-soft-file-limit
        - soft-disk-limit
        - soft-file-limit
        - threshold
      quotaType:
        - tree`

**Expected behavior**
Harvest should expose all the metrics qtree_disk_used which it initially did.

**Actual behavior**
Metrics are not present.

**Possible solution, workaround, fix**
Tell us if there is a workaround or fix

**Additional context**
Metrics are not exposed even with harvest used having full admin access.

**Comment by Hardikl** [comment]
@mwas01 , Along with logs, Could you confirm any changes/update in quota objects(mainly tree quotas) in your system?

**Comment by ruanruijuan** [comment]
Closing based on email exchange. @mwas01 has upgraded to the nightly version and enabled user/group quota collection. The issue went away.
