### ISSUE TITLE
Prefix (-p option) does not add prefix to all panels

### ISSUE THREAD

**Issue by matejzero** [NetApp/harvest#1643]
**Describe the bug**

I'm using -p parameter to append prefix to metrics names but it doesn't get added to all the panels, just some.

A few examples (can go over all the boards is nessessary):
- volume: volume table drilldown, volume WAFL, per-volume rows
- cluster: power, throughput, storage efficency, SVM performance rows
- disk: list of disks and disk utilization rows
- headroom: aggregate headroom and cpu headroom
- ...

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 22.11.1-1 (commit 689c1cfb) (build date 2022-12-08T09:26:57-0500) linux/amd64
- Command line arguments used: RPM install with Zapi metrics
- OS: AlmaLinux 8
- Install method: rhel
- ONTAP Version: 9.7 and 9.11

**To Reproduce**

Import dashboards via harvest grafana import with -p parameter set (eg. `netapp_`).

**Expected behavior**

All panels showing metrics as I do have metrics collected, but panels have missing prefix for metrics name.

**Actual behavior**

Some panels have no prefixes.

**Possible solution, workaround, fix**

Well, prepend the prefix:P

**Comment by cgrinds** [comment]
Hi @matejzero if you want to try these changes out before the next release, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).

**Comment by cgrinds** [comment]
Verified in `23.02`

**Comment by matejzero** [comment]
I tested on my end too and it works OK. Thanks for the quick fix.
