### ISSUE TITLE
Cannot build container in an environment requiring a http proxy

### ISSUE THREAD

**Issue by optiz0r** [NetApp/harvest#165]
**Describe the bug**

In an environment where direct internet access is not available, and use of an http proxy is required, the docker container cannot be built due to upstream busybox issue https://github.com/mirror/busybox/issues/21

**To Reproduce**

Build the container with `http_proxy`. `https_proxy` env vars pointing at a valid proxy

**Expected behavior**

Container image should build successfully

**Actual behavior**

The build fails where wget tries to download `dumb-init` with varying error messages

**Possible solution, workaround, fix**

Use upstream wget instead of the wget functionality baked into busybox

**Comment by cgrinds** [comment]
We can probably drop `dumb-init` and use [Docker's --init flag](https://docs.docker.com/engine/reference/run/#specify-an-init-process).

> The default init process used is the first docker-init executable found in the system path of the Docker daemon process. This docker-init binary, included in the default installation, is backed by [tini](https://github.com/krallin/tini).
