### ISSUE TITLE
volume summary metrics mismatch

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1666]
Thanks @twodot0h for raising [this](https://discord.com/channels/855068651522490400/1067019312356937748) 

<img width="839" alt="image" src="https://user-images.githubusercontent.com/25551691/214035396-e2d044b1-136d-49de-9b0a-d76f4ef27f34.png">

Applicable to all such summary metrics,

latency chart in Node dashboard under `Backend Drilldown` doesn't match with Harvest 1.6. Harvest 1.6 use to do weighted average while Harvest 2 does just average.

![image](https://user-images.githubusercontent.com/25551691/214035139-66741cdd-8438-43ed-8d89-6dc5d8d82158.png)

**Comment by Hardikl** [comment]
Verified in 23.02, values are matching.
