### ISSUE TITLE
Restore qtree disk metrics

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1678]
Create a new template for 23.02 qtree metrics and labels that match the 22.05 qtree metrics and labels. Added to `default.yaml`, commented out

**Comment by cgrinds** [comment]
If you want Harvest to publish qtree metrics/labels the same as Harvest 22.05 did, you can extend the qtree template by following these steps.

1. Create a `conf/zapi/custom.yaml` file, if it doesn't already exist, and add the following lines:

```yaml
objects:
 Qtree: custom_qtree.yaml
```

2. Create a new object template `conf/zapi/cdot/9.8.0/custom_qtree.yaml` with the following lines.

```yaml
plugins:
  - Qtree:
      historicalLabels: true
```

3. When you restart your pollers, Harvest will merge the out-of-the-box `qtree.yaml` template and the `custom_qtree.yaml` one.

The `historicalLabels` key causes Harvest to publish qtree metrics and labels with both the 22.05 and 22.11 shapes. More details on merging can be found [here](https://netapp.github.io/harvest/latest/configure-templates/#how-to-extend-a-zapizapiperf-collectors-existing-object-template).

**Comment by Hardikl** [comment]
Verified in 23.02.

As normal work-flow:
Historical labels (Ex: export_policy, etc labels which are from qtree template and not related to quota) are not included by-default.
```
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_labels | grep export_policy | wc -l
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep quota_disk_limit  | wc -l                    
      31
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep quota_disk_limit | grep export_policy | wc -l 
       0
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_disk_limit  | wc -l                 
      31
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_disk_limit | grep export_policy | wc -l
       0
```

Added custom.yaml file as mentioned above.
Historical labels (Ex: export_policy, etc labels which are from qtree template and not related to quota) as well as new labels (Ex: index, etc labels) from quotas are included.
```
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_labels | grep export_policy |wc -l 
     159
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep quota_disk_limit  | wc -l                    
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep quota_disk_limit | grep export_policy | wc -l
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_disk_limit  | wc -l
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_disk_limit | grep export_policy | wc -l
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep quota_disk_limit | grep index | wc -l         
      32
hardikl@hardikl-mac-2 harvest %  curl -s http://localhost:15002/metrics | grep qtree_disk_limit | grep index | wc -l
      32
```
