### ISSUE TITLE
--port in generate docker command should work for standlone harvest container deployment

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1703]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/25551691/217850484-2c134409-8d1d-46e7-a4ff-6ced92a7b713.png">

**Comment by cgrinds** [comment]
Verified in `23.02`
Before the fix, `bin/harvest generate docker --help`  did not include `-p --port` in the output
With the fix it does
