### ISSUE TITLE
Revisit counter dash to underscore replacement logic

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1738]
As raised by jfong on [Discord](https://discord.com/channels/855068651522490400/1075465999781986364/1075465999781986364)

This logic happens [here](https://github.com/NetApp/harvest/blob/1be3ef44e7f65506e76f74f81f6d478b522f648c/pkg/util/util.go#L251)

Replacement of dash to underscore happens automatically when you don't use the rename  `=>` marker, and yes, that behavior is used extensively in zapi templates. Perhaps the idea is if you rename, you get the final call to decide on the name (even if it's wrong). That may be questionable 🙂

As [noted](https://netapp.github.io/harvest/23.02/resources/templates-and-metrics/#prometheus-wire-format) Prometheus does not permit dashes `-` in labels.

**Comment by cgrinds** [comment]
ONTAP REST documentation states:

> However, REST converts hyphens `-` in CLI parameter names to underscores `_` in the REST API JSON response body.

**Comment by Hardikl** [comment]
We have investigated on this issue and below is the summary:

--> Prometheus would not supporting the hyphen (`-`) in metric/label names and erroring out, Whereas InfluxDB can support the hyphen(`-`).

--> Harvest's behaviour would be if we have the rename marker `=>` in the template, then Harvest will honour that display 
name as-is. If we don't have the rename marker `=>` in template, then Harvest will try to help and generate display name accordingly. 

The solution which we all are agreed on is, if the rename marker `=>` exist in template, Then Harvest should not intervene and honour the display name as-is.
