### ISSUE TITLE
23.02.0 Package won't install on Nabox 3.2

### ISSUE THREAD

**Issue by jgasher** [NetApp/harvest#1766]
**Describe the bug**
I tried to install the package on Nabox 3.2 and got a message that the file uploaded and installed successfully, but Harvest disappeared from the list of software on the maintenance page.  Clicking on the Systems page gives a message to install Harvest.  I then installed 22.11.1 and everything started working as expected.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: 23.02.0
- Command line arguments used: Nabox mainteance page
- OS: Nabox 3.2
- Install method: Nabox
- Other:

**To Reproduce**
contact jasher@netapp.com for access to system and see the issue live

**Expected behavior**
Harvest 23.02.0 should be installed and running

**Actual behavior**
Harvest 23.02.0 does not install or start successfully on my installation of Nabox 3.2.

**Possible solution, workaround, fix**
Tell us if there is a workaround or fix

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by jgasher** [comment]
Issue resolved.  PEBCAK error.  I was trying to upload and install the sour-code package instead of the compiled package.  All works as it should.

**Comment by cgrinds** [comment]
Thanks for the follow-up Jeff. Closing based on your comment
