### ISSUE TITLE
S3 object storage - more metrics & dashboard/s

### ISSUE THREAD

**Issue by XDavidT** [NetApp/harvest#1768]
**Describe the solution you'd like**
Add new metrics like size of buckets, list of buckets, objects count, request per buckets
Add a new dashboard/s to view metrics of S3 object storage

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/NetApp/harvest/discussions/1749#discussioncomment-5066499)

**Comment by XDavidT** [comment]
> ONTAP or Storagegrid

ONTAP

**Comment by DAx-cGn** [comment]
+1

**Comment by cgrinds** [comment]
See also https://github.com/NetApp/harvest/discussions/1749

**Comment by LukaszWasko** [comment]
I am also looking forward to the S3 dashboards. Where can I download an initial version?

**Comment by cgrinds** [comment]
hi @LukaszWasko this dashboard will be included in the `23.05` release of Harvest. If you want to try it out before the next release, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).

![image](https://user-images.githubusercontent.com/242252/235448564-4bf01d94-7bfa-432a-a27f-3dd744975fcd.png)

Verified on 3ffa2eb5
