### ISSUE TITLE
NVMe Namespace dashboard

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1829]
### Discussed in https://github.com/NetApp/harvest/discussions/1823

<div type='discussions-op-text'>

<sup>Originally posted by **ddhti** March 16, 2023</sup>
Hi,

I'm using nabox 3.2 with harvest 23.02.0-1.  I have NVMe LUNs (namespaces) in use but they are not under the LUNs dashboard and I can't find them elsewhere.  There are NVMe stats under the SVM dashboard but that's it.  ... Also, I don't see a storagegrid dashboard (but I haven't added my SG yet).

What step or config am I missing? 

thank you.</div>

**Comment by ddhti** [comment]
Those are a good start.  I guess what I'm looking for are the same metrics you'd get on the ONTAP: LUN dashboard where applicable.  For example its good to have latency counters but knowing where the latency is coming from is key to troubleshooting.  Backend? Frontend? Throttle?  I don't know what counters can be reported on but I see Namespaces as LUNs for all practical purposes.

**Comment by ddhti** [comment]
Awesome!!  I was worried for my performance lol

**Comment by cgrinds** [comment]
Verified on 3ffa2eb5
