### ISSUE TITLE
Grafana Cluster Dashboard Typo

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#184]
**Describe the bug**
In the NetApp Detail: Cluster dashboard is a typo.

**To Reproduce**
Look at the mentioned dashboard

**Expected behavior**
It should be "Throughput" with a "r" not "Thoughput"

**Actual behavior**
Its "Thoughput"

**Additional context**
![image](https://user-images.githubusercontent.com/33655308/122165846-172b2400-ce79-11eb-9d14-0fd0c1282cdc.png)

**Comment by rahulguptajss** [comment]
@Hardikl  Could you take a look.
