### ISSUE TITLE
Prometheus Alert: node_nfs_latency > 1000

### ISSUE THREAD

**Issue by elsgaard** [NetApp/harvest#1852]
The prometheus alert "Node nfs latency is high" is default set to node_nfs_latency > 1000

I assume 1000 is in micro seconds, but it seems very low, is that an recommended value ?
In the Grafana dashboard, the panel "NFSv3 Avg Latency" which uses this counter, has default thresholds set to:

10000 -> yellow
25000 -> orange
50000 -> red

Which is 50 x the configured critical alert ?

Is above 1000 microseconds really the critical value ?

**Comment by cgrinds** [comment]
hi @elsgaard, thanks for raising. This is a bug, as you noted, this [metric](https://netapp.github.io/harvest/23.02/ontap-metrics/#node_nfs_latency) is reported in microsec. We'll fix.

**Comment by elsgaard** [comment]
@rahulguptajss Thanks, just to be very precise, from the commit, they are set to 0.001s 0.0025s and 0.005s
The counter is reporting us, so the conversion is 1000.000us to 1s

**Comment by cgrinds** [comment]
Verified on 52f41df4

```bash
rg node_nfs_latency container/prometheus/alert_rules.yml
61:    expr: node_nfs_latency > 5000
```

```bash
gron grafana/dashboards/cmode/node.json | rg "10000|25000|50000"

gron grafana/dashboards/cmode/node.json | rg "thresholds.*(1000|2500|5000)"

json.panels[18].panels[0].fieldConfig.defaults.thresholds.steps[1].value = 1000;
json.panels[18].panels[0].fieldConfig.defaults.thresholds.steps[2].value = 2500;
json.panels[18].panels[0].fieldConfig.defaults.thresholds.steps[3].value = 5000;
json.panels[18].panels[1].fieldConfig.defaults.thresholds.steps[1].value = 1000;
json.panels[18].panels[1].fieldConfig.defaults.thresholds.steps[2].value = 2500;
json.panels[18].panels[1].fieldConfig.defaults.thresholds.steps[3].value = 5000;
json.panels[18].panels[2].fieldConfig.defaults.thresholds.steps[1].value = 1000;
json.panels[18].panels[2].fieldConfig.defaults.thresholds.steps[2].value = 2500;
json.panels[18].panels[2].fieldConfig.defaults.thresholds.steps[3].value = 5000;
```
