### ISSUE TITLE
security_account_activediruser and few other plugin generated metrics are missing in REST 

### ISSUE THREAD

**Issue by Hardikl** [NetApp/harvest#1855]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/83282894/227264166-8144f46f-3e18-40fb-b96e-403b79464c3e.png">

**Comment by Hardikl** [comment]
Functional impact would be 2 dashboards:
1. Compliance dashboard --> Cluster Compliance table
<img width="1738" alt="image" src="https://user-images.githubusercontent.com/83282894/227449665-eb7cc6a8-abc9-4c0a-af30-39a1f27dd55b.png">

2. Security dashboard --> Authentication Methods panel
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/83282894/227449804-8052528f-746d-4ab7-b5d4-3d9c836fdd03.png">

**Comment by cgrinds** [comment]
Verified on 52f41df4

These are present in REST and appear in dashboard
