### ISSUE TITLE
Node Dashboard Bugs

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#186]
**Describe the bug**
Several bugs in the node dashboard

- Cluster variable not based on datacenter variable
- Typo  Thoughput (2x)
- Units of Throughput panel set to seconds (4x)
- Unit of IOPS panel set to seconds (5x)

**Additional context**
![grafik](https://user-images.githubusercontent.com/26142342/122237171-672cd980-cebf-11eb-899c-6ac090b49d24.png)
![grafik](https://user-images.githubusercontent.com/26142342/122237215-71e76e80-cebf-11eb-91a9-91ac6cb7fa95.png)
![grafik](https://user-images.githubusercontent.com/26142342/122237252-7a3fa980-cebf-11eb-9cba-66fd65d4cf17.png)
![grafik](https://user-images.githubusercontent.com/26142342/122237293-8297e480-cebf-11eb-950b-872a1e700667.png)
![grafik](https://user-images.githubusercontent.com/26142342/122237594-bbd05480-cebf-11eb-9dd8-a7db9e1340f2.png)

**Comment by rahulguptajss** [comment]
@Hardikl could you check this.

**Comment by ruanruijuan** [comment]
#184 mentioned about the "thoughput" typo too.

**Comment by Hardikl** [comment]
@mamoep , issue 2, 3 and 4 are resolved.
But for issue 1: Cluster variable not based on datacenter variable, 
what is the exact expectation here for field cluster?

![image](https://user-images.githubusercontent.com/83282894/122946013-a2834880-d396-11eb-9133-ff78bd16c6b8.png)

Here, DC-03 is coming from harvest.yaml which is datacenter field, and F8080-32-25 is from ONTAP filer actual name.

**Comment by mamoep** [comment]
Cluster is not filtered based on datacenter as the other dashboards do. I expect only to get the clusters in the chosen datacenter.

**Comment by cgrinds** [comment]
Thanks for reporting @mamoep - does https://github.com/NetApp/harvest/pull/213 fix the cluster filtering issue for you?

**Comment by Hardikl** [comment]
Handled all 4 issues.

**Comment by rajeshl8** [comment]
Verified all 4 issues and all the issues are fixed. Hence moving to fixed state.
[root@scspo2403645002 harvest]# ./bin/harvest -v
harvest version 21.06.2312-v21.05.3 (commit e480de6) (build date 2021-06-23T12:21:16-0400) linux/amd64
[root@scspo2403645002 harvest]# 


![image](https://user-images.githubusercontent.com/5583674/123199160-59a5bf80-d47c-11eb-851d-ce5bb460007d.png)
