### ISSUE TITLE
Collect LIF metrics in Harvest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1875]
As discussed in [discord](https://discord.com/channels/855068651522490400/1089802354041294908), Thanks Pacqui for raising

![image](https://user-images.githubusercontent.com/25551691/228304160-3ffaf9ab-0fea-4d40-8608-5d5990914ec7.png)

**Comment by cgrinds** [comment]
Verified on 3ffa2eb5

```bash
curl -s http://localhost:12995/metrics | rg "lif_" | wc -l
361
```
