### ISSUE TITLE
Grafana Dashboard / Volumes not selectable

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#190]
**Describe the bug**
The dropdown for selecting a specific volume in the NetApp Detail: Volume Dashboard is always empty.

**To Reproduce**
Open the NetApp Detail: Volume Dashboard select SVM and klick on the dropdown for volumes 
![image](https://user-images.githubusercontent.com/33655308/122384374-ee378b80-cf6b-11eb-8557-9fc13e4588cd.png)

**Expected behavior**
Specific volumes should be selectable

**Actual behavior**
No volumes selectable

**Comment by florianmulatz** [comment]
![image](https://user-images.githubusercontent.com/33655308/122384604-25a63800-cf6c-11eb-80ed-d367b0b9b75a.png)

**Comment by matejzero** [comment]
Template query is `label_values(netapp_volume_labels{datacenter="$Datacenter",cluster="$Cluster",node=~"$Node",svm=~"$SVM"}, volume)`. 

`node=~"$Node"` should be removed as we don't have that variable on Volumes dashboard. With it removed, volumes are shown.

**Comment by rahulguptajss** [comment]
Thanks @matejzero for the triage. We'll take a look.

**Comment by florianmulatz** [comment]
Yes - volumes appear then - but when a volume is selected, filter does not apply on other graphs. Still all volumes are shown.

**Comment by matejzero** [comment]
> Thanks @matejzero for the triage. We'll take a look.

Agree. volume label filters are missing on all the graphs. Not too hard to add. I can do PR if noone else will do it.

**Comment by sridevimm** [comment]
Tested this scenario in Harvest point release 21.05.3.1 and able to reproduce this issue. Reopening the issue to get this fixed. 

<img width="1072" alt="Screen Shot 2021-06-23 at 11 39 01 AM" src="https://user-images.githubusercontent.com/83037454/123127275-1dd90e80-d418-11eb-85a2-90f479508c3d.png">

**Comment by Hardikl** [comment]
![image](https://user-images.githubusercontent.com/83282894/123244462-95369d00-d501-11eb-8412-ba467ca882cf.png)

![image](https://user-images.githubusercontent.com/83282894/123244549-a8496d00-d501-11eb-8f30-f3220805cb85.png)

I have installed the latest binary in RPM[10.140.132.80 root/netapp], alongwith the grafana(8.0.3) and prometheous(2.28.0).
Then imported the dashboards via this: 
$ bin/grafana import --addr my.grafana.server:3000 --directory grafana/prometheus

SVM filter and volume filters are working as expected, Also I have checked that the changes are available in release branch as well, so moving this to testme.

**Comment by florianmulatz** [comment]
I can confirm Hardikls' remarks:
![image](https://user-images.githubusercontent.com/33655308/123254004-67942880-d4ee-11eb-9493-fa4781263759.png)

**Comment by ruanruijuan** [comment]
Thank you @florianmulatz
