### ISSUE TITLE
Network dashboard: port utilization wrong unit

### ISSUE THREAD

**Issue by matejzero** [NetApp/harvest#195]
**Describe the bug**

Port utilization in Network dashboard shown wrong utilization in % due to wrong unit seleected. Harvest reports utilization in 0-1 format, but unit in Grafana is selected as 0-100.

**Environment**
- Harvest version: harvest version 21.05.2-1 (commit ce091de) (build date 2021-06-14T20:31:09+0530) linux/amd64
- Command line arguments used: /opt/harvest/bin/harvest restart --config /opt/harvest/harvest.yml
- OS: CentOS 7
- Install method: yum
- ONTAP Version: 9.7
- Other:

**To Reproduce**

Open network dashboard and look at `Port utilization %` graph and compare to receive/send graph.

**Expected behavior**

Unit in Grafana should be set to `Percentile (0.0 - 1.0)` instead of `Percentile (0 - 100)` as that will give correct results.

![Screenshot 2021-06-18 at 14 50 11](https://user-images.githubusercontent.com/4689252/122563522-96b91e80-d044-11eb-9759-b452179ea3a2.png)
![Screenshot 2021-06-18 at 14 50 30](https://user-images.githubusercontent.com/4689252/122563517-9587f180-d044-11eb-8a5f-6f475545ba39.png)

**Actual behavior**

![Screenshot 2021-06-18 at 14 50 11](https://user-images.githubusercontent.com/4689252/122563566-a5073a80-d044-11eb-9cca-a468d39d2987.png)
![Screenshot 2021-06-18 at 14 50 13](https://user-images.githubusercontent.com/4689252/122563579-a7699480-d044-11eb-9dbe-55a3a17cfa30.png)

**Possible solution, workaround, fix**

Change unit in graph settings.

**Comment by Hardikl** [comment]
changed percent limit from 0-100 to 0-1.

**Comment by sridevimm** [comment]
Verified the fix in Harvest 21.05.3.1 

<img width="615" alt="Screen Shot 2021-06-23 at 11 51 45 AM" src="https://user-images.githubusercontent.com/83037454/123128839-765cdb80-d419-11eb-9e62-c56b0c519198.png">
