### ISSUE TITLE
Harvest should collect fibre channel switch data

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#1961]
`/network/fc/fabrics`
`/network/fc/ports`

**Comment by faguayot** [comment]
Hello chris, 

Have you planned to integrate this information in a dashboard?

**Comment by cgrinds** [comment]
hi @faguayot - That's a good question. We're still discussing that. Do you have a dashboard in mind for these?

The Health dashboard includes some data from the `/network/fc/ports` endpoint, like so:

<img width="683" alt="image" src="https://github.com/NetApp/harvest/assets/242252/bf19963e-2b37-4640-83c8-993614db9262">

**Comment by cgrinds** [comment]
Looks like we collect some fibre channel performance metrics in the `ONTAP: Network` dashboard (see below). Are you looking for config metrics for fibre channel? Can you say more about which metrics you're interested in?

![image](https://github.com/NetApp/harvest/assets/242252/e374bbb7-6302-4a11-9161-6189c5d68451)

**Comment by faguayot** [comment]
Hello Chris, 

I was thinking in a summary tablet (can be the table shown by you but adding more info) where we can see useful information like port (adapter),node,speed, information about the other site of the port connection (switch-port). The result is In a simple view we have the information for the whole adapters and where are connected in the other end. 

Additionally If this information (switch and switch-port) can be inserted in a separate way in the database (same metric but different fields/tag) it is possible to build queries from the storage array site and the switches site making a matching between both which trigger an alert.  I am thinking not only in the monitorize but also in the alerting.

`net fcp adapter show -node * -fields switch-port
`
I am not sure if I explained my self.

Thanks.
