### ISSUE TITLE
Investigate using colors in dashboards to highlight warning, critical severity

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#1978]
Thanks @lorenzoc for raising this on [discord](https://discord.com/channels/855068651522490400/1098920812028899378)

![image](https://user-images.githubusercontent.com/25551691/233648287-d17b2846-97f4-4516-bd5d-38c415fb5eec.png)

**Comment by cgrinds** [comment]
Add unit test for thresholds by panel unit type to drive this and check 1.6.
Be mindful of HDD vs SDD threshold differences and ONTAP hardware differences
