### ISSUE TITLE
Expose nfs3 io types at the volume level

### ISSUE THREAD

**Issue by amd-eulee** [NetApp/harvest#2040]
I would like to see the nfs io types breakdown at the volume level (currently only available at SVM )

I would like to see the nfs io types breakdown at the volume level through the nabox Volume dashboard.

Another dashboards that allows nfs io type breakdown at the volume level

![image](https://user-images.githubusercontent.com/116657067/236010553-102db3d3-caf4-454e-8dcb-6fbe32ae6437.png)

**Comment by cgrinds** [comment]
Verified on bd0b0db7
