### ISSUE TITLE
Exporter does not support SSL protocol to InfluxDB

### ISSUE THREAD

**Issue by krax13** [NetApp/harvest#2042]
**Describe the problem**
I use an quite old Netapp storage and I'd like to gain data and transfer that metrics to my InfluxDB v2 database.
Unfortunately, I cannot set up SSL connection in the InfluxDB exporter, because the project cannot support TLS protocol for InfluxDB.

**Describe the solution you'd like**
Please try to develop a code to support SSL protocol between exporter and influxDB.

**Describe alternatives you've considered**
I couldn't find alternatives. However, I can disable the SSSl in influxdb, but I do not want it, because I have some other gatherer tools that sends metrics in SSL protocol.

**Comment by cgrinds** [comment]
hi @krax13 you should be able to use `https` when exporting to InfluxDB from Harvest. Examples are included in the documentation at the bottom of the page https://netapp.github.io/harvest/23.05/influxdb-exporter/

Can you give that a try?

**Comment by krax13** [comment]
Hi @cgrinds: Thank you for your response. It almost works now. :) In the logs there are a certificate issue:
"tls: failed to verify certificate: x509: certificate signed by unknown authority"
Can I put the certificates into a directory and tell the exporter to use them?

**Comment by krax13** [comment]
I have solved the issue with mapping of the local certs to /etc/ssl/certs in docker container.
So it works now! :)

**Comment by cgrinds** [comment]
Awesome! Glad to hear @krax13
