### ISSUE TITLE
PrometheusPort in poller args is a string - should be an int 

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#21]
https://github.com/NetApp/harvest/blob/e63ae7fd1d78f157e3310e8460c5903734cd4b26/cmd/poller/poller.go#L758

**Comment by rahulguptajss** [comment]
@Hardikl  pls add testing steps if any. I am moving this to testme for now. If no testing needed then pls move to untested.

**Comment by rajeshl8** [comment]
Verified the Prometheus Port updated to integer value from string. After the update verified all the port details are displayed in status command.

[root@scspo2403645002 harvest]# ./bin/harvest status
Datacenter            Poller                PID        PromPort        Status              
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++
umeng_aff300          umeng_aff300          26878      12990           running             
F2240-127-26          F2240-127-26          26888      12991           running             
+++++++++++++++++++++ +++++++++++++++++++++ ++++++++++ +++++++++++++++ ++++++++++++++++++++

Hence marking the issue fixed.
