### ISSUE TITLE
Revisit Volume Sis Stat Panels

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2106]
As discussed in [discord](https://discord.com/channels/855068651522490400/1097452031242940556/1110508129604599829), Investigate Volume Sis Stat panels.

KB link: https://kb.netapp.com/onprem/ontap/dm/Efficiency/No_compression_savings_in_ONTAP_9.8P1_or_later

**Comment by Hardikl** [comment]
We do show volume sis counters in 2 places.
1. `Volume Sis Stat` 3 newly added panels (Required 9.12+ with REST)
2. Two columns[`dedupe space saved`, `compression space saved`] in `Volumes in cluster` table

------------------
I have done initial comparison about what we do show in dashboards for different cluster versions. 
**9.8** 
--> 3 volume sis panels empty 
--> dedupe space, compression space almost all are 0 in table

**9.9** 
--> 3 volume sis panels empty, 
--> dedupe space, compression space all are 0 in table

**9.10** 
--> 3 volume sis panels empty, 
--> dedupe space, compression space all are 0 in table

**9.11** 
--> 3 volume sis panels empty in zapi and show data in rest, 
--> dedupe space, compression space show data in table

**9.12** 
--> 3 volume sis panels empty in zapi and show data in rest,
--> dedupe space, compression space show data in table

**9.13** 
--> 3 volume sis panels empty in zapi and show data in rest, 
--> dedupe space, compression space show data in table

--------------------
So far as per the above detail, It seems 9.11 onwards ZAPI/REST has appropriate data in table and panels. and if required only info details would need to be added in panel/table for the same.

Data parity of ZAPI/REST response value with CLI is yet to validate.

**Comment by Hardikl** [comment]
We have gone through the KB article https://kb.netapp.com/onprem/ontap/dm/Efficiency/No_compression_(reporting_0)savings_in_ONTAP_9.8_or_later_at_the_volume_level and compared couple of 9.12+ clusters for this counters (num_compress_attempts, num_compress_fail). 

Our newly added `Volume Sis Stat` panels required ONTAP 9.12+ and the APIs are only available via REST for collecting above mentioned counters. we have validated, this panel would showing appropriate data for 9.12+ clusters.

So, We have decided to retain `Volume Sis Stat` panel as-is, as it's working as design.

**Comment by Hardikl** [comment]
We have investigated and no changes would be needed for this as per the above details. Hence, Closing this issue. 
Please feel free to reopen if otherwise.
