### ISSUE TITLE
Volume Perf error

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2114]
The following error log was observed in one of the customer's logs.

{"level":"error","Poller":"xxxxxx","plugin":"ZapiPerf:Volume","object":"Volume","error":"duplicate instance key => .","key":".","caller":"volume/volume.go:88","time":"2023-05-24T02:49:57+02:00","message":"Failed to create new instance"}

**Comment by cgrinds** [comment]
Verified on 23.08.0 commit bd0b0db7

On .74
rg -z "duplicate instance key" /var/log/harvest/
