### ISSUE TITLE
Data rate units across all panels should be same in Harvest

### ISSUE THREAD

**Issue by Hardikl** [NetApp/harvest#2123]
For data rate panels, we are currently using the 2 flavours of units in Harvest.
1. binBps (IEC) Ex. panel:  "Top $TopResources Luns by Read Throughput"
2. Bps (SI) Ex. panel:  "Ethernet Throughput"

We need to decide which one would be appropriate and replace that to all the date rate panels.

**Comment by cgrinds** [comment]
Handled in testcase
