### ISSUE TITLE
Node-Detail Dashboard / all nodes are shown

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#215]
**Describe the bug**
In the details dashboard, all nodes are displayed even though a specific node is selected.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

I've already installed the newest dashboards from github (status as of 06/22/21)
![image](https://user-images.githubusercontent.com/33655308/123035001-e43dde80-d3ea-11eb-8fe0-0997af16f075.png)
Cheers Florian

**Comment by rajeshl8** [comment]
Issue is fixed , hence moving to fixed/done state.
[root@scspo2403645002 harvest]# ./bin/harvest -v
harvest version 21.06.2312-v21.05.3 (commit e480de6) (build date 2021-06-23T12:21:16-0400) linux/amd64
[root@scspo2403645002 harvest]# 


![image](https://user-images.githubusercontent.com/5583674/123199686-5bbc4e00-d47d-11eb-97b3-8f4e5fb597a7.png)
