### ISSUE TITLE
Investigate unit for svm nfs throughput

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2154]
**Metrics:** svm_nfs_read_throughput,  svm_nfs_throughput, svm_nfs_write_throughput
**Ontap Unit:** per_sec

```xml
<counter-info>
<desc>NFSv4.1 read data transfers.</desc>
<is-deprecated>false</is-deprecated>
<name>nfs41_read_throughput</name>
<privilege-level>admin</privilege-level>
<properties>rate,no-zero-values</properties>
<unit>per_sec</unit>
</counter-info>
```

**Dashboard:** Bps

See #2105

**Comment by cgrinds** [comment]
Verified in `24.02` 84e2f7ca

https://netapp.github.io/harvest/nightly/ontap-metrics/#node_nfs_read_throughput
