### ISSUE TITLE
Credential Script - detect unauthorized logins

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#2168]
**Is your feature request related to a problem? Please describe.**
My company is using CyberArk for automatic password management. It rotates the password for my harvest user automatically every few days. I use the credential script feature to get the password from the CyberArk "Central Credential Provider" REST API, which works well. But when the password is rotated, Harvest will wait for the time set as `schedule`, before picking up the new password. Meanwhile collection fails.

**Describe the solution you'd like**
Harvest should detect when login fails and instantly pull the new credentials.

**Describe alternatives you've considered**
Lowering the `schedule` value to narrow the gap is feasible of course. But considering possible availability issues of the CyberArk API, I would like to have 24h of cached credentials.

**Comment by cgrinds** [comment]
Add retry logic for:
- [ ] Zapi
- [ ] Rest
- [ ] StorageGRID

**Comment by cgrinds** [comment]
Fixed in #2180

@mamoep if you want to try these out before the next release, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly) and let us know if it covers your usecase.

**Comment by mamoep** [comment]
I tested now. It doesn't work when credential_script is configured in the defaults section. (similar to #2127)

Unrelated: I found Harvest is assuming ZAPI is EOA and switching to REST when the remote system is not reachable at all. Don't know if this is intended, but I think it could have unintended consequences in case of temporary network connectivity issues. Example log output:
```
{"level":"warn","Poller":"cluster","error":"connection error => Post \"https://cluster:443/servlets/netapp.servlets.admin.XMLrequest_filer\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","collector":"Zapi","caller":"./poller.go:1150","time":"2023-07-07T09:09:13+02:00","message":"ZAPI EOA. Use REST"}
{"level":"warn","Poller":"cluster","error":"connection error => Post \"https://cluster:443/servlets/netapp.servlets.admin.XMLrequest_filer\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","collector":"ZapiPerf","caller":"./poller.go:1150","time":"2023-07-07T09:10:13+02:00","message":"ZAPI EOA. Use REST"}
{"level":"warn","Poller":"cluster","error":"connection error Get \"https://cluster/api/cluster?fields=%2A&return_records=true\": dial tcp 192.168.1.1:443: i/o timeout","collector":"RestPerf","object":"VscanSVM","caller":"./poller.go:695","time":"2023-07-07T09:11:03+02:00","message":"init collector-object"}
```

**Comment by cgrinds** [comment]
Thanks for the reporting the Defaults and REST upgrade problem @mamoep. We'll check it out. We added a unit test for `credentials_script` in Defaults after your earlier issue but maybe something else changed. We'll get back to you.

**Comment by cgrinds** [comment]
hi @mamoep this has been fixed and published to the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly). Please let us know if that works for you. Thanks!

**Comment by cgrinds** [comment]
Thanks for reporting both issues and the confirmation @mamoep 

We've also addressed the ZAPI to REST upgrade issue by changing the automatic upgrade logic to only happen when ONTAP responds with an error saying ZAPIs are disabled or removed.
