### ISSUE TITLE
Change Log Detection in Harvest

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2179]
- [x] Implementation
- [x] Documentation
- [x] Create Sample Alerts
- [x] Add dashboard

**Comment by Hardikl** [comment]
Tested in release branch 23.11 with commit 815fca8e0af0c0d70307d28b5a72451071c4ad79

1. Changed svm state from running to stopped. reporting from zapi and rest both.
<img width="1770" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/ab651425-4ba0-4370-aa71-9e7609944ae5">

2. Changed node location from GDL to SVL. reporting from zapi and rest both.
<img width="1761" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/1cc44903-d55c-423c-826e-1efd79636b7c">

3. Changed volume state from to restricted. reporting from zapi only, rest is not giving change_log metric.

Working on it.

**Comment by Hardikl** [comment]
Tested with this PR https://github.com/NetApp/harvest/pull/2478 changes,
3. Changed volume state from to restricted. reporting from zapi and rest both.
<img width="1775" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/bcad8785-8880-4010-a516-856a82e33d2c">

**Comment by Hardikl** [comment]
Tested on release branch 23.11 with commit a6f049fc6e5e8924717232bd4a8b83e2400d95ba
