### ISSUE TITLE
After changing from ZAPI to RestAPI, there´s no collection of FlashPool-data anymore

### ISSUE THREAD

**Issue by lobster1860** [NetApp/harvest#2212]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

We changed from ZAPI to RestAPI, and afterwards the FlashPool graph does not contain any data anymore, so it stopped collecting if using RestAPI. If using ZAPI it worked fine:

https://github-production-user-asset-6210df.s3.amazonaws.com/63659528/254256136-c4ec0c53-6648-4844-8d29-d6eafde0a0df.PNG

### Configuration

```text
nas:
    datacenter: NSR0
    addr: xx.xx.xx.xx
    auth_style: basic_auth
    username: netapp-harvest
    password: *********
    collectors:
      #- Zapi
      #- ZapiPerf
      - Rest
      - RestPerf  
      - Ems  
    exporters:
      - prometheus3
```

### Poller

netapp-harvest

### Version

Netapp-Harvest 23.05.0

### OS and platform

RHE7.6

### ONTAP or StorageGRID version

Netapp ONTAP 9.12.1P4

**Comment by cgrinds** [comment]
hi @lobster1860 can you email your poller's log file to [ng-harvest-files@netapp.com](mailto:ng-harvest-files@netapp.com) and we'll take a look

**Comment by lobster1860** [comment]
Thank you - i´ve just sent the requested log.
