### ISSUE TITLE
Harvest should include a QoS fixed and adaptive policy dashboard

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2267]
Related to #1426

**Comment by Hardikl** [comment]
Tested in release branch 23.11 with commit 815fca8e0af0c0d70307d28b5a72451071c4ad79

4 new panels have been added in `QoS Fixed Utilization %` row.
<img width="1738" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/35ec4c35-5265-4a7c-9be8-7cca207f29a9">
