### ISSUE TITLE
qos policy not updated in workload counters

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2317]
As reported by @jmg011

> Users complained twice in past couple of days about the qos policy being not updated as part of this metric qos_volume_read_io_type that they use in their reporting. I do not see any warning, delay or errors in the logs. When I restart the poller, it updates the policy info on the metric.

**Comment by Hardikl** [comment]
Tested in release branch 23.11 with commit a6f049fc6e5e8924717232bd4a8b83e2400d95ba,

1. Changed policy-group from `rahul1` to `rahul2`, Harvest updates new label to all the qos related metrics in next poll.
`::> qos policy-group rename -policy-group rahul1 -new-name rahul2`
