### ISSUE TITLE
ONTAP Power calculation for embedded Shelf

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2332]
- [ ] The power algorithm implemented in the Harvest should exclude the power reported from embedded shelves when calculating the Total Power.
https://kb.netapp.com/onprem/ontap/hardware/FAQ%3A_How_do_shelf_product_IDs_and_modules_in_ONTAP_map_to_a_model_of_a_shelf_or_storage_system_with_embedded_storage

**Comment by Hardikl** [comment]
Tested in main with commit 41584651972c5ab9c336e10fc3c662e6df873b15

Tested in 2 AFF-250, umeng-01-02, umeng-05-06 clusters.
1. Embedded shelves are ignored to calculate the total power.
2. Total power = Nodes power + shelf power (if not embedded).
