### ISSUE TITLE
Dashboard "StorageGrid: Overview" wrong unit in panel "Top x tenants by quota usage"

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#2347]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Dashboard "StorageGrid: Overview" shows wrong unit in panel "Top x tenants by quota usage"

Panel shows Bytes (or in my case Milli-Bytes). Metric calculation indicates a percentage 0.1-1 value.

### Poller

StorageGrid

### Version

harvest version 23.08.0-1 (commit 874a1f87) (build date 2023-08-21T08:36:53-0400) linux/amd64

### OS and platform

RHEL 8.8

### ONTAP or StorageGRID version

11.7.0

**Comment by cgrinds** [comment]
Thanks @mamoep this bug is fixed in PR #2348
