### ISSUE TITLE
how to enable quota or quota report?

### ISSUE THREAD

**Issue by leejshades** [NetApp/harvest#2352]
plz,help me 

how to enable quota or quota report 

i have make create  /opt/harvest2-conf/conf/zapi/custom_my.yaml  and /opt/harvest2-conf/conf/zapi/cdot/9.8.0/custom_qtree.yaml

and then restart harvest2
![image](https://github.com/NetApp/harvest/assets/7189444/e0df30c1-1d90-4357-8af2-916c2c9d2890)
![image](https://github.com/NetApp/harvest/assets/7189444/efc02c6b-55f4-4fd5-a62a-80f50a485f25)

**Comment by leejshades** [comment]
hi ,
![image](https://github.com/NetApp/harvest/assets/7189444/eff7a85a-456a-4a27-982e-75ba7649e40f)
![image](https://github.com/NetApp/harvest/assets/7189444/bc635da5-5898-46f7-ae37-fba763872fb7)

**Comment by leejshades** [comment]
my version is:
![image](https://github.com/NetApp/harvest/assets/7189444/b4e00c50-cc18-43e5-a5d8-631ac741204c)

**Comment by leejshades** [comment]
hi,
![image](https://github.com/NetApp/harvest/assets/7189444/73585a06-0acc-4c98-afa0-4057656be3e1)
![image](https://github.com/NetApp/harvest/assets/7189444/3767de09-e4d1-4ec4-afbd-478b167d1c50)

**Comment by leejshades** [comment]
can't see 'quota'
![image](https://github.com/NetApp/harvest/assets/7189444/50bacc64-861f-4124-bcb4-41d81c87738c)

**Comment by cgrinds** [comment]
Closing.

@leejshades if you still see this problem please reopen and reply with the logs mentioned in [comment](https://github.com/NetApp/harvest/issues/2352#issuecomment-1713617059)
