### ISSUE TITLE
Harvest power algorithm should ignore embedded shelves, handle shared PSUs, and include root aggregates

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2357]
Thanks to Evan Lee for reporting!

Summary of the three issues:
1. In most cases, ONTAP does not report power for embedded disk shelves, and Harvest relied on that. But in some cases, ONTAP reports power for embedded disk shelves. FAS2750 is an example. Harvest should ignore embedded shelves. #2332 fixed in #2333
 
2. Some hardware (FAS2620, FAS2750, etc.) use shared PSUs – when there are shared PSUs, Harvest double counts the PSUs power. For example: “system environment sensors show” reports node1 is using 297W and node2 is using 297W, but because the system has shared PSUs that load share power between nodes, the actual power is (297+297)/2 = 297W. 

`23.08` and earlier versions of Harvest would report 297W + 297W = 594W since we summed the PSU power. The fix is to detect shared PSUs and divide the total PSU power by the number of shared-nodes, resulting in 297W in this example.

3. Root aggregates should be shown in aggregate power table panel

- [x] Finish documentation
- [ ] Include root aggregates in power calculation

**Comment by cgrinds** [comment]
The logic to determine if PSUs are shared in point two requires using `system chassis fru show`.

We have not been able to find a ZAPI that returns this information, which means Power would become a REST only feature.

We can gather the data via `/api/private/cli/system/chassis/fru` with `fields=chassis-id,fru-name,name,num-nodes,status,type`

**Comment by Hardikl** [comment]
Tested in main with commit 41584651972c5ab9c336e10fc3c662e6df873b15

Tested in 2 AFF-250, umeng-01-02, umeng-05-06 clusters.

1. Embedded shelves are ignored to calculate the total power.
2. Total power = Nodes power + shelf power (if not embedded).
3. Root aggregates are displayed in `Aggregates` table.
<img width="1848" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/072bf5f7-3ac8-4227-868b-03e247b20187">
