### ISSUE TITLE
Volume Latency breakdown

### ISSUE THREAD

**Issue by demalik** [NetApp/harvest#241]
**Is your feature request related to a problem? Please describe.**
Regression from Harvest 1.6 to harvest 2.0

**Describe the solution you'd like**
Customer is already using workload counters in 1.6 for latency breakdown along the data path in ONTAP. Customer will like capability with dashboarding IO profile breakdown (R/W/O), protocol (NFS/SMB) breakdown latency, Protocol breakdown i.e. open/close/delete/getattr/setatte information available within harvest 2.0, NVIDIA

**Comment by tsrustam** [comment]
would this breakdown include qos_latency_from_* drilldown from 1.6(*=network,throttle,frontend etc)?

**Comment by cgrinds** [comment]
@tsrustam thanks for raising this request.  We'll take a look at pulling those missing counters in from 1.6. Some of those may be available now in one of the `workload*.yaml` files [here](https://github.com/NetApp/harvest/tree/main/conf/zapiperf/cdot/9.8.0).

If you want to try these, make sure you uncomment [these four lines](https://github.com/NetApp/harvest/blob/d7fe8f7b691b6c059c85868ec8e6ed410d026f1a/conf/zapiperf/default.yaml#L49).

**Comment by cgrinds** [comment]
these have been added to Harvest 2.0 dashboards. Please let use know if there is anything else missing
