### ISSUE TITLE
Flexcache statistics

### ISSUE THREAD

**Issue by ewilts** [NetApp/harvest#2428]
We have multiple FlexCache implementations locally and are now progressing to WAN-based FlexCache.  As such, cache performance is far more critical.
Please implement counters such as:
* time to retrieve items
* oldest data in the cache volume
* cache miss rate
We're looking for any and all data that will help us determine if the cache is sized correctly and whether or not it's being used correctly.
Some of the many statistics available are documented in TR-4743.

**Comment by cgrinds** [comment]
https://www.netapp.com/media/7336-tr4743.pdf

**Comment by ewilts** [comment]
What I see in the screenshot isn't going to help me answer the questions.  All of the data is per node but I need it per volume.  If I have multiple volumes on the same node and see a high node evict latency, how does that tell me if it's volume 1 or volume 2 that's too small?  And since cache targets are by definition flexgroups, there's a reasonable likelihood for many customers that there are multiple constituents spread across the nodes (a best practice for flexgroups).  

I asked "We're looking for any and all data that will help us determine if the cache is sized correctly and whether or not it's being used correctly.".  None of the graphs you've shown address that.

Now it's quite likely that this is not a harvest issue but that ontap isn't collecting the data in the first place in which case I'll ask you to explain to them why you can't monitor data that isn't there...

**Comment by cgrinds** [comment]
Verified in `24.02` 84e2f7ca
