### ISSUE TITLE
Add NFS rewinds data

### ISSUE THREAD

**Issue by shawnahall71** [NetApp/harvest#2434]
**Is your feature request related to a problem? Please describe.**
We're experiencing a performance issue with our NetApp system, and support has determined that it is related to a high number of NFS rewinds as mentioned in [this support article](https://kb.netapp.com/onprem/ontap/da/NAS/High_Network_Processing_(CPU_N-blade)_latency_and_poor_performance_due_to_locking).

**Describe the solution you'd like**
It would be helpful if Harvest collected these NFS rewind statistics so we can view them historically.

**Describe alternatives you've considered**
Currently we can only run CLI statistics commands to see the NFS rewinds data and average over a period of time.  NetApp support has the ability to pull this information from performance snapshots, but I don't have a good way to graph these metrics myself short of extending what Harvest is doing.

**Additional context**
After opening various NetApp support cases, it's clear that NetApp performance engineers have access to a richer set of statistics than customers do, although the data Harvest collects is quite good.  It would be nice for NetApp power users to have access to deeper insights like support does.

**Comment by Hardikl** [comment]
@shawnahall71 

We've added the `rw_ctx` ZapiPerf object template via PR https://github.com/NetApp/harvest/pull/2494 which has NFS rewinds data.
Fix would be available via [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) build.

Added `Rewind View` Row in `Node Dashboard` with 6 new panels.
<img width="1874" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e4d8e14c-c970-4bef-bd65-915850d651bf">
