### ISSUE TITLE
Missing `Zapi:Volume` metrics in harvest for considerable time

### ISSUE THREAD

**Issue by kbhalaki** [NetApp/harvest#2444]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

We have setup harvest (v22.08.0) for our production netapp clusters and we started to miss Zapi:Volume metrics after a while with the following error for each volume:

`9:15PM ERR collector/zapi.go:431 > skipped instance [instance_id]: not found in cache Poller=cluster-01 collector=Zapi:Volume`

All the other metrics were working fine. 

We also observed that just before the above error, we also saw 401-Unauthorized on the same collector:

`9:14PM ERR collector/collector.go:363 > error="error reading api response => 401 Unauthorized" mPoller=cluster-01 mcollector=Zapi:Volume mtask=instance`

Note that we did not receive 401 errors for other collectors.

The above two errors came after 4 hours of deployment and that is when we started to miss metrics. 

I also went through [troubleshooting.md](https://github.com/NetApp/harvest/blob/main/docs/help/troubleshooting.md#some-of-my-clusters-are-not-showing-up-in-grafana) and checked if we got any `timeout` errors but we did not get any timeout errors at any point in our logs. 

1. Does harvest not retry the next time after we run into 401?
2. Should we upgrade harvest version?

### Poller

ZAPI

### Version

22.08.0

### OS and platform

cbl-mariner,docker

### ONTAP or StorageGRID version

9.11

**Comment by kbhalaki** [comment]
@rahulguptajss I just checked the logs again - we see 401s for ZAPI:ClusterPeer too and after that - we start to see `not found in cache` errors.

**Comment by kbhalaki** [comment]
@rahulguptajss we also see few 401s in ZAPIPerf but NOT any `not found in cache` logs for them

**Comment by kbhalaki** [comment]
@rahulguptajss thank you for the link, but if it was permission issue I think it should happen for all collectors and it should not go away once i restart the harvest service right? Please let me know your thoughts.

**Comment by kbhalaki** [comment]
@rahulguptajss thank you, we will run it and share the details with you. 

We saw this log after the first series of `not found in cache` errors. 

`9:15PM INF collector/collector.go:342 > no instances, entering standby Poller=cluster-01 collector=Zapi:Volume`

Also, we never got `401 Unauthorized` errors for Zapi:Volume after the first time which makes me think if it even tried after that? 

Do you think this is something that is fixed in v23.08?

**Comment by kbhalaki** [comment]
@rahulguptajss  we have shared the logs. Please check.

**Comment by cgrinds** [comment]
@kbhalaki have you had a chance to upgrade yet?

**Comment by kbhalaki** [comment]
@cgrinds yes we upgraded and it works well for us till now. Thank you for your support!

**Comment by cgrinds** [comment]
Great! I'll close this one
