### ISSUE TITLE
Adaptive policy dashboard

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2497]
This is a follow up story from #2267 #1426. We should create a adaptive policy panels similiar to QOS fixed % in workload dashboard.

**Comment by faguayot** [comment]
Hello @rahulguptajss 

First at all thanks for all the information shared in a order and visual way.

I have some doubts related the  shared information. In this example that you expose,  we have asummed that the adaptative QoS policy is implemented on a `volume level` but for example in our particular case, we are applying the adaptative QoS in the `LUN level.` 
Additionally, we don't use the **throughput** for limitated the ceiling or floor (probably other clients do this). And the last thing I have seen is we don't have a block size for every specific QoS defined too, in our case `the block size is ANY `and the `Peak and Expected IOPS Allocation` are: **allocated-space**.

But all the information that I have shared is only our use case, so I don't know if all the calculation that you share could be apply and adapt depending on the different way of defining the QoS adaptative policy. 

I hope I have explained myself successfully.
Thanks.

**Comment by faguayot** [comment]
Hello Rahul, 

I have download the nightly from the link that you share but I don't see the same informacion about % of Adaptative QoS.

![image](https://github.com/NetApp/harvest/assets/85484449/babecf89-7c0b-499d-b2e9-40b72e9a100d)

In the `QoS bandwidth` is normal since we don't configure and use but where it should appear the list of workload, cluster,etc I only see `%qos used, IOPS and Max IOPS`.

Thanks. It looks great in your image dashboard.

**Comment by faguayot** [comment]
I have tried importing the JSON as a new dashboard but the result is the same,

![image](https://github.com/NetApp/harvest/assets/85484449/542fdbc1-3227-4a0f-a9df-7832c47a9e11)

**Comment by faguayot** [comment]
Hello rahul, 

With this importation is working correctly.

![image](https://github.com/NetApp/harvest/assets/85484449/ef361a53-d9cc-4cb6-aa51-4104188eaab0)


> @faguayot Could you try re-importing the dashboard from [here](https://raw.githubusercontent.com/NetApp/harvest/3f8f1e7dd29ae8e56f5ad9f94a535792eabdee07/grafana/dashboards/cmode/workload.json) to see if it helps?

**Comment by Hardikl** [comment]
Verified in 24.05 release branch at commit 74dcf38a872d2c38e633664314e0acc5b9f8d76b

Tested in grafana 8.3.4,
<img width="1726" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/7f81cebe-11cb-4040-9713-0af34237a977">


Tested in grafana 9.5.15,
<img width="1749" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/e40937ca-7e95-4c74-a0e0-78ff7bcc4ef5">



Tested in grafana 10.3.1,
<img width="1760" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/faa2f2f0-2ad6-4942-97a6-02481546b58d">


Tried to unselect/select `cluster` column in the table and no extra columns were visible with 1,2,etc during that path.
working as expected.

**Comment by faguayot** [comment]
> > Hello rahul,
> > With this importation is working correctly.
> > ![image](https://private-user-images.githubusercontent.com/85484449/327755154-ef361a53-d9cc-4cb6-aa51-4104188eaab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODA4MzcsIm5iZiI6MTcxNDk4MDUzNywicGF0aCI6Ii84NTQ4NDQ0OS8zMjc3NTUxNTQtZWYzNjFhNTMtZDljYy00Y2I2LWFhNTEtNDEwNDE4OGVhYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA3Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNjZmOTNkZmZiZTVlMjg4ZTljYmU2MjJjMDY2YzdkYWQ2ODc2Yzg5MzM4ZTE3NDY4NDc1MDNiMmM1NTNkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oiA1cWxjCQnZhvcesTsMMIW_2MFRri6L8DRM-oxdZFs)
> > > @faguayot Could you try re-importing the dashboard from [here](https://raw.githubusercontent.com/NetApp/harvest/3f8f1e7dd29ae8e56f5ad9f94a535792eabdee07/grafana/dashboards/cmode/workload.json) to see if it helps?
> 
> Thank you, @faguayot. This dashboard issue will be addressed through #2873. Are there any other feedback regarding the panels?

Hello Rahul

I am trying the new release with these changes until now I haven't seen anything but if I find something I will let you know.
Thanks for the implementation.
