### ISSUE TITLE
Add NDMP metrics

### ISSUE THREAD

**Issue by schumijo** [NetApp/harvest#2498]
**Describe the solution you'd like**
Can you add NDMP metrics from REST API endpoint /api/protocols/ndmp/sessions ?

**Additional context**
Could be interesting to monitor number of concurrent sessions, statistics about performances.....

**Comment by Hardikl** [comment]
@schumijo 

This is list of fields returned from Rest call `/api/protocols/ndmp/sessions`, and I have added one [PR](https://github.com/NetApp/harvest/pull/2531) in draft stage which have few of these counters.
<img width="651" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/2c9813cc-3cfe-4179-9c0c-d763c4b53b18">

Could you please share which are the counters would be helpful for you for performance statistics.

**Comment by Hardikl** [comment]
@schumijo NDMP session rest template is now available via [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) builds. By default this template is disabled. You can uncomment [here](https://github.com/NetApp/harvest/blob/main/conf/rest/default.yaml#L27) and let us know your feedback.
