### ISSUE TITLE
Pre-defined rules for Prometheus alerting

### ISSUE THREAD

**Issue by demalik** [NetApp/harvest#254]
Customer would like to use the alerting functions of Prometheus – they ask for pre-defined rules showing the best practice rules used by AIQUM
Customer requests NetApp provide alerts for objects within ONTAP management, performance and provide capability for customers to edit alert triggers.

**Comment by demalik** [comment]
Here is additional information received from customer on "predefined rules" for alerting

            Below are the alerts I believe should be part of canned rules shipped with Harvest. 

1.	Rules for checking volume capacity
2.	Rules for detect any hardware failure (disk/PSU/IOM/Memory)
3.	Rules for checking node latency (system/protocol)
4.	Rules for checking offlined volumes
5.	Rules for checking non-online aggreagtes
6.	Rules for identifying not-home LIFs
7.	Rules for identifying failed/lagging SnapMirror replications
8.	Rules for idenitifying snapshots older than X days
9.	Rules for detecting volume latency (NFS/CIFS)
10.	Rules for detecting QOS induced volume latency
11.	Rules for checking vserver level latency (NFS/CIFS)
12.	Rules to detect qtree quota usage

**Comment by cgrinds** [comment]
A couple of examples alerts added [here](https://github.com/NetApp/harvest/blob/main/docker/prometheus/alert_rules.yml)

**Comment by rahulguptajss** [comment]
- [ ] Add more sample alerts
- [ ] Add documentation on creating alerts

**Comment by rahulguptajss** [comment]
@demalik Harvest now supports below alerts. Refer document (https://github.com/NetApp/harvest/blob/main/cmd/exporters/prometheus/README.md#prometheus-alerts) for creating new alerts. Let us know if this helps addressing this issue. 

1. Rules for checking volume capacity
2. Rules for detect any hardware failure (disk)
3. Rules for checking node nsf latency
4. Rules for checking offlined volumes
5. Rules for checking non-online aggreagtes
6. Rules for identifying lagging SnapMirror replications

**Comment by rahulguptajss** [comment]
verified rules are imported in prometheus with our docker workflow and working fine.
