### ISSUE TITLE
Ensure that Harvest dashboards work with Grafana 10.X

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2547]

**Comment by Hardikl** [comment]
**Issue:**

After grafana version 10.2.3, default prometheus type datasource name has been changed from `Prometheus` to `prometheus` while adding the datasource in grafana. While dashboard import, If the datasource name in json file don't match with the grafana datasource name, then `datasource not found/legacy datasource error` will be shown in all the panels and all the dashboard will be impacted.

**Summary of what we have discussed as next steps**

1. We can change our grafana import default to `prometheus` and we need to change our datasource add workflow for Docker, NABox and Ansible to use `prometheus` as Harvest controlled those workflows 
2. Update our documentation to say 
- When you create a Prometheus datasource in Grafana make sure you name it `prometheus`
- If you already have a Prometheus datasource setup, you need to make sure that name matches what you use for `import --datasource`
3. We could use Grafana's API to get all datasources and check that the datasource you specify at the CLI exists and if it does not, then fail the import workflow.
4. Add another CLI switch `--force Import` even if datasource does not exist in Grafana
