### ISSUE TITLE
Improve dashboard performance / consider simplified top n calculation

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#2549]
**Is your feature request related to a problem? Please describe.**
I have 22 clusters monitored and using the SVM dashboard takes up to 20 seconds before I get what I want. A high number of queries in variables for `top n` calculations.

**Describe the solution you'd like**
Consider calculating top n once based on volume iops & throughput and then use this value for all protocols.

**Describe alternatives you've considered**
n/a

**Additional context**
The approach would be different and my lead to less accurate results, but the usability would improve a lot. Top talkers on the cluster would still be visible.

**Comment by cgrinds** [comment]
Leaving open to capture remaining work. #2553 fixes SVM dashboard. We should roll this out to all dashboards with topk panels.
