### ISSUE TITLE
Protocol Counters

### ISSUE THREAD

**Issue by demalik** [NetApp/harvest#255]
Customer is currently using the protocol counters on the volume level with 1.6, looking for similar information in Harvest 2.0

For example - NFS R/W/metadata @ volume, node, svm level

**Comment by cgrinds** [comment]
hi @demalik do the new svm dashboards with nfs drill-downs have you need? If not could you let us know what's missing? Thanks
- [SVM dashboard](https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/harvest_dashboard_svm.json)
- [SVM details dashboard](https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/harvest_dashboard_svm_details.json)

**Comment by demalik** [comment]
I will check with customer and update. Thanks!

**Comment by cgrinds** [comment]
hi @demalik any update on this?

**Comment by cgrinds** [comment]
Covered by additional dashboards. Closing - feel free to reopen if there are more questions
