### ISSUE TITLE
Harvest 1.6 extension manager

### ISSUE THREAD

**Issue by demalik** [NetApp/harvest#257]
Customer looking for extension manager capability in harvest 2.0, leveraging extension manager  to add any other data/counters to their Grpahite DB

**Comment by cgrinds** [comment]
We're working on an extension manager. It's a work in progress at the moment, and it probably end up looking different than 1.6's. In the meantime, the code is modular and open making it easier to extend than 1.6. Take a look at [ARCHITECTURE.md](https://github.com/NetApp/harvest/blob/main/ARCHITECTURE.md) to get an overview of the system.

There are not plans to support Graphite in Harvest 2.

If you want to follow along or contribute to the extension work, take a look at https://github.com/NetApp/harvest/pull/120 and #100 

Also take a look at Harvest2's [built-in plug-ins](https://github.com/NetApp/harvest/blob/main/cmd/poller/plugin/README.md). You may be able to use these without additional code.

**Comment by cgrinds** [comment]
Plugins are supported in Harvest 2. Closing
