### ISSUE TITLE
ONTAP: SVM dashboard - additional volume capacity panel

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#2595]
**Is your feature request related to a problem? Please describe.**
Feature request for the SVM dashboard

**Describe the solution you'd like**
Currently there is a panel with Top volumes by % used, which works well for volumes with no autogrow. For better transparency additional panels like the per volume statistics on the ONTAP volume dashboard would be great.

**Additional context**
Sometimes we need to have a look how a SVM  evolve over time regarding space usage and with that additional panel, it makes it much easier to the usage of a svm at one view.

**Comment by cgrinds** [comment]
Thanks for the issue @BrendonA667 Have you already made this change locally? Would you like to contribute this change?

**Comment by BrendonA667** [comment]
Hi @cgrinds unfortunatley not, need to finde some time for that
