### ISSUE TITLE
Qos latency seeing spike

### ISSUE THREAD

**Issue by summertony15** [NetApp/harvest#2597]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

When using "qos_latency" metric in harvest, there are peak value that are over 600000s 
![qos_latency overall](https://github.com/NetApp/harvest/assets/33056261/27590091-8df8-4ebe-8319-11c7f67f0c0e)

Here are the comparison of "qos_ops" and "qos_latency", 

![comparison](https://github.com/NetApp/harvest/assets/33056261/37f29964-130e-440a-b2f4-b2912dc41003)

Here is the line graph of "qos_latency"
![latency](https://github.com/NetApp/harvest/assets/33056261/75350849-9ad1-4495-8af4-12a515b98749)

Here are some details:
![la850-855](https://githu
![la850-851](https://github.com/NetApp/harvest/assets/33056261/4c259a05-f132-49f2-be46-2064527fe8f1)
b.com/NetApp/harvest/assets/33056261/cad78a1d-6a86-4d07-9f9e-c759d500ba01)
![la902-905](https://github.com/NetApp/harvest/asse
![la903](https://github.com/NetApp/harvest/assets/33056261/8bb3a06b-0720-4c1a-a81d-e8b5424deefb)
ts/33056261/4383789d-874b-46c7-a2a9-6ac1c528bd01)

And this is the line graph of "qos_ops"
![ops](https://github.com/NetApp/harvest/assets/33056261/91722046-dad9-48ba-b5f9-ecdf5e0ad572)

Here are some details:
![op850-851](https://github.com/NetApp/harvest/assets/33056261/7fb8f019-b1fe-4bca-b515-9073c76c3434)

![ops855-858](https://github.com/NetApp/harvest/assets/33056261/b3e9d6cc-0e57-4524-bb7a-b77633d25ebe)
![ops857](https://github.com/NetApp/harvest/assets/33056261/2dceec2b-1631-4314-8447-78cc6bb17c97)

### Poller

cluster1

### Version

23.12.18

### OS and platform

Nabox

### ONTAP or StorageGRID version

9.11.1

**Comment by cgrinds** [comment]
Closing. Tony said he would update on [Discord](https://discord.com/channels/855068651522490400/1177540045163474965/1211933380430667856).
