### ISSUE TITLE
Harvest should add forecasting with Prometheus's `predict_linear`

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2610]
## Links
- https://prometheus.io/docs/prometheus/latest/querying/functions/#predict_linear
- https://stackoverflow.com/questions/56606452/how-to-use-forcasting-in-prometheus-predict-linear
- https://www.dbi-services.com/blog/predict-the-future-with-prometheus/

**Comment by Hardikl** [comment]
customer discussion here: https://github.com/NetApp/harvest/discussions/2518
