### ISSUE TITLE
clone_split_estimate parse error

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2612]
From one of the customer logs, noticed below error.

nabox-harvest2  | 2024-01-30T03:15:54Z ERR volume/volume.go:144 > parse clone_split_estimate error="strconv.ParseFloat: parsing \"\": invalid syntax" Poller=*** clone_split_estimate= object=Volume plugin=Zapi:Volume

**Comment by cgrinds** [comment]
Verified in `24.02` 84e2f7ca
