### ISSUE TITLE
Option to use grafana import to output customized dashboards to local filesystem

### ISSUE THREAD

**Issue by nicolai-hornung-bl** [NetApp/harvest#2617]
**Is your feature request related to a problem? Please describe.**
We are using Grafana Cloud for visualization and they recently deprecated API Tokens in favor of Cloud Access Policies and either I am still not giving enough scope to the token I created or something else is not working. Additionally I would prefer to manage dashboards via the available Terraform provider rather than having some machine in our environment pushing dashboard to Grafana Cloud.

**Describe the solution you'd like**
An option to simply have harvest customize the dashboards for our setup (stuff like adding the prefix and correct datasources and then output the customized dashboard json to the local filesystem again so I can import them either manually or using Terraform or any other IaC solution. Command could look like this:

`
/opt/harvest$ bin/harvest grafana customize --directory grafana/dashboards --output-dir ~/harvest-dashboards --prefix netapp_ --datasource my_datasource
`

**Describe alternatives you've considered**
In my specific case either documentation on what scope a cloud access policy needs to have for grafana import to work without a 401 response or a general fix to support cloud access policies (don't know if it's user error or a bug on your side).

**Comment by cgrinds** [comment]
hi @nicolai-hornung-bl thanks for the feature request. I understand that you would like a `customize` command that writes the dashboards to the filesystem so that another program can manage the dashboards. We can take a look at that.

In the meantime, let's see if we can make `grafana import` work against Grafana Cloud. I'd like that work since other customers may hit the same problem and they may not want to manage the dashboards externally.

Looking at the [scopes](https://grafana.com/docs/grafana-cloud/account-management/authentication-and-permissions/access-policies/#scopes), I agree that none of those sound like dashboard create/update permissions. It's odd that the [Dashboard API for Cloud](https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/http-api/dashboard/) does not mention any scopes either.

Have you tried asking in the Grafana forums? It should be straightforward to recreate the problem you're seeing with Grafana Cloud import via a one line curl and hopefully then can tell you what scope(s) is needed. Something along the lines of

```bash
vi dashboard.json
```

Paste the following into the file
```
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "refresh": "25s"
  },
  "message": "Made changes to xyz",
  "overwrite": false
}
```

Run with the following, updating $ip and $token
```bash
curl -v -H 'Content-Type: application/json' -H 'Authorization: Bearer $token' -d '@dashboard.json' http://$ip:3000/api/dashboards/db
*   Trying $ip:3000...
* Connected to 10.193.49.74 (10.193.49.74) port 3000
> POST /api/dashboards/db HTTP/1.1
> Host: 10.193.49.74:3000
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer $token
> Content-Length: 241
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< Date: Tue, 30 Jan 2024 18:00:57 GMT
< Content-Length: 130
< 
* Connection #0 to host 10.193.49.74 left intact
{"id":5520,"slug":"production-overview","status":"success","uid":"6mO800tIz","url":"/d/6mO800tIz/production-overview","version":1}⏎  
```

**Comment by cgrinds** [comment]
hi @nicolai-hornung-bl Pull request #2619 adds `grafana customize` as requested. 
We'll review it and let you know when it hits nightly.

Example execution
```bash
bin/harvest grafana customize --directory grafana/dashboards --prefix netapp_ --datasource my_datasource --output-dir ~/harvest-dashboards

OK - customized [/Users/cgrindst/harvest-dashboards/cmode/aggregate.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/cdot.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/changelogMonitor.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/cluster.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/compliance.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/data_protection_snapshot.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/disk.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/external_service_op.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/flexcache.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/flexgroup.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/fsa.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/headroom.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/health.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/lun.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/mcc_cluster.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/metadata.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/namespace.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/network.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/nfs4storePool.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/nfs_clients.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/node.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/power.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/qtree.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/quotaReport.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/s3ObjectStorage.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/security.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/shelf.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/smb.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/snapmirror.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/svm.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/volume.json]
OK - customized [/Users/cgrindst/harvest-dashboards/cmode/workload.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/aggregate7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/cluster7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/disk7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/lun7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/network7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/node7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/shelf7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/7mode/volume7.json]
OK - customized [/Users/cgrindst/harvest-dashboards/storagegrid/fabricpool.json]
OK - customized [/Users/cgrindst/harvest-dashboards/storagegrid/overview.json]
OK - customized [/Users/cgrindst/harvest-dashboards/storagegrid/tenant.json]
```

**Comment by nicolai-hornung-bl** [comment]
Hi @cgrinds,

Wow thanks for the super quick response! 

Initially I was trying to use a Cloud Access Policy Token with the scopes "stack-dashboards:read, stack-dashboards:write, stack-dashboards:delete". This led to a 401 Invalid Response for both the harvest import as well as your curl test. After some digging I tried using a Service Account token (don't ask me what the difference is supposed to be 😆) with the scopes "Dashboards:Reader, Dashboards:Writer, Dashboards:Creator, Organizations:Reader". Using the SA Token with this scope the curl command successfully imports the test dashboard however using this token with harvest import now gives me a 403 Forbidden. 
SA Tokens however still support adding "Editor" rights and with this finally the import also works (However I would still prefer to have a minimally scoped token - I will try to find out what permissions are still missing). I will also try to clarify with Grafana when Service Accounts should be used and when Cloud Access Policies.

Concerning the customize part this looks exactly like what I was hoping for - again thanks for the super quick implementation. I will test it once it hits nightly and give you feedback.

Thanks again!

Nicolai

**Comment by cgrinds** [comment]
hi @nicolai-hornung-bl these changes have been included in the latest nightly. If you want to try them out before the next release, you can grab the [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).
