### ISSUE TITLE
Shelf metrics should report on op-status for components

### ISSUE THREAD

**Issue by hashi825** [NetApp/harvest#262]
**Is your feature request related to a problem? Please describe.**
Shelf metrics currently only have a value mapping for `state` to create metric `shelf_status` and `psu-is-enabled` for `shelf_psu_labels`.
 Currently for example to detect a failure you have to use `shelf_sensor_reading` to see if that value dropped to 0 which is pretty ambiguous and doesn't help pinpoint the issue.

**Describe the solution you'd like**
Have the default template for `harvest/conf/zapi/cdot/9.8.0/shelf.yaml`  use `op-status` from `storage-shelf-info-get-iter` for shelf components bays, psu, fans etc.

**Describe alternatives you've considered**
None at the moment

**Additional context**
In a real environment it's unlikely that shelf state is a very important metric since Shelves rarely change from online > offline, but it's extremely common to have failed power supplies or other components. Each of these components in a shelf have their own `op-status` that allows detecting failures. These failures are also rolled up into the `shelf-errors` field that reports `storage-shelf-error-info`, these values report text data though such as `error-type`, `error-text` so these would be potentially difficult to convert to time series, but they can also be used to potentially verify their existence as a shelf health metric, ie if empty 0 otherwise 1 (same concept as disk_status outage-info field) ?

**Comment by cgrinds** [comment]
@hashi825 does https://github.com/NetApp/harvest/pull/295 address you ask?

**Comment by hashi825** [comment]
Yea that looks like it could work, you could use the label metrics instead of say `shelf_status` in an alert ie:

`expr: shelf_sensor_labels{status!="normal"}`

Would it also be better to use `op-status` at the shelf level for the value mapping? this way `shelf_status` can actually report a 1/0 value for the `op-status` and not `state` which is more indicative of the status.

Also I noticed that the value mapping for status 1/0 (not just for the shelf template but for others) are back to front from what typical up/status metrics are in Prometheus. In Prometheus generally 1 indicates healthy and 0 otherwise, this is pretty common across all prometheus exporters.

**Comment by Hardikl** [comment]
@hashi825,
I need to see the feasibility for this: expr: shelf_sensor_labels{status!="normal"}, let me check and update here.

Regarding the 2nd ask for op-status instead of state in shelf_status, I have made the changes in current PR.

And last one, 
[value mapping for status 1/0 (not just for the shelf template but for others) are back to front from what typical up/status metrics are in Prometheus.], 
--> Yeah, this is the same across all yamls where 0 indicates up/normal and 1 indicates default(or not expected outcome). I would suggest that we can track this separately and handle for all if required.

**Comment by cgrinds** [comment]
@hashi825 opened #306 about the status values - we'll update everything to use 1 for healthy. In cases where there are multiple kinds of failures would distinct values be preferable or would you rather have all of those mapped to zero?

**Comment by Hardikl** [comment]
@hashi825 
regarding the ask: expr: shelf_sensor_labels{status!="normal"}

With current changes:
shelf_sensor_labels metric would show these records:

shelf_sensor_labels{cluster="F8080-32-25", datacenter="DC-03", instance="localhost:12991", job="prometheus1", location="rear of the shelf on the lower left power supply", sensor_id="1", status="normal", shelf="1.0"} | 1
-- | --
shelf_sensor_labels{cluster="F8080-32-25", datacenter="DC-03", instance="localhost:12991", job="prometheus1", location="rear of the shelf on the lower left power supply", sensor_id="1", status="normal", shelf="1.10"} | 1

Do you mean that the shelf_sensor_labels metric would only gives result when status would be non-normal? 
In case of all sensors are normal(like above example), metric won't list records?

**Comment by hashi825** [comment]
Since status has now been added as a  label you can use the expression for Prometheus alerting to send alerts on non normal statuses eg

shelf_sensor_labels{status!="normal"} = 1

That should work for alerting since the label metrics return more descriptive information such as location of sensors compared to the status related metrics

**Comment by Hardikl** [comment]
This is harvest 21.05.3-2 RPM: 10.140.133.43
![image](https://user-images.githubusercontent.com/83282894/126510134-e0550f79-5695-47c5-957a-3c0ce2b4c4e7.png)


This is harvest 21.05.4-1 RPM: 10.140.132.253
![image](https://user-images.githubusercontent.com/83282894/126510026-01a175a2-152f-4ce9-a2e5-0e8d93f4bea8.png)


Child Objects:
Child object's new status metric is available and status field is added in label in 21.05.4:
status metric gives 1 for normal value and 0 for non normal values.
Fan:
![image](https://user-images.githubusercontent.com/83282894/126511668-745b5d9e-d751-4534-9446-9b63712e1c50.png)

![image](https://user-images.githubusercontent.com/83282894/126511942-06ea2ee3-19eb-4ba5-b582-ab2ec248263b.png)

PSU:
![image](https://user-images.githubusercontent.com/83282894/126512319-c4570ddc-663f-4176-b732-ae38b242bcde.png)

![image](https://user-images.githubusercontent.com/83282894/126512373-45395392-9671-4bcc-916a-70d9f8116335.png)

Sensor:
![image](https://user-images.githubusercontent.com/83282894/126512460-814e9b7b-14da-4158-bbaa-fcbc15e6c5d0.png)

![image](https://user-images.githubusercontent.com/83282894/126512501-60cb5801-da25-4d96-a1b1-a503c93b6b0a.png)

Voltage:
![image](https://user-images.githubusercontent.com/83282894/126512759-a23edbbf-067c-4397-8bc6-5803c4e5e835.png)

![image](https://user-images.githubusercontent.com/83282894/126512815-2da31e4b-799a-45a0-905a-722c04ceaef0.png)

Temperature:
![image](https://user-images.githubusercontent.com/83282894/126512898-de766494-bab8-41d1-ba1f-088c9af5d1fa.png)

![image](https://user-images.githubusercontent.com/83282894/126512956-fba1faa9-0036-42f3-b694-f5f949040781.png)

op_status column is visible in shelf dashboard and all child object are having status metric with required mapping values.
So with these, moving this to status/done state.
