### ISSUE TITLE
Datacenter count in metadata Dashboard is incorrect

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2621]
As reported by norespers over [discord](https://discord.com/channels/855068651522490400/1200214236702441622/1202115223348318219)

Datacenter count in metadata Dashboard is incorrect.

<img width="1243" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/795bd00a-c636-4973-adf1-e9b4982bc20f">

**Comment by cgrinds** [comment]
Verified in `24.02` 84e2f7ca

<img width="250" alt="image" src="https://github.com/NetApp/harvest/assets/242252/05f7827d-60b0-483c-902e-949aa233f2d8">
