### ISSUE TITLE
Harvest dashboards should include an `All` option for cluster, node, volume, svm, and aggregate variables

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#2660]
Some dashboards do
<img width="608" alt="image" src="https://github.com/NetApp/harvest/assets/242252/5bef90e1-8832-4ef9-948e-93ff9cb442b7">

and some don't.

<img width="631" alt="image" src="https://github.com/NetApp/harvest/assets/242252/ba033ee2-9847-4f42-834f-c3ebe2696c5f">

Use `All` consistently on dashboards

**Comment by Hardikl** [comment]
Tested in main with commit febb62c563db51e24d99114ad758524eeeb25311
