### ISSUE TITLE
ONTAP:Disk Dashboard user_(write|read)_chain length displayed as kbytes

### ISSUE THREAD

**Issue by george-strother** [NetApp/harvest#2665]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

In [https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/disk.json](https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/disk.json) the two panels for read/write chains incorrectly display as chain_length as kbytes.

- Read Chain panel:
  - ["unit": "kbytes"](https://github.com/NetApp/harvest/blob/4e021db9cbe920f1e495094b2d8f78bfd3bc23b3/grafana/dashboards/cmode/disk.json#L1217)
  - ["title": "Top $TopResources Aggregates by User Read IOP Size",](https://github.com/NetApp/harvest/blob/4e021db9cbe920f1e495094b2d8f78bfd3bc23b3/grafana/dashboards/cmode/disk.json#L1255)
 
- Write Chain panel:
  - ["unit": "kbytes"](https://github.com/NetApp/harvest/blob/4e021db9cbe920f1e495094b2d8f78bfd3bc23b3/grafana/dashboards/cmode/disk.json#L1313)
  - ["title": "Top $TopResources Aggregates by User Write IOP Size",](https://github.com/NetApp/harvest/blob/4e021db9cbe920f1e495094b2d8f78bfd3bc23b3/grafana/dashboards/cmode/disk.json#L1351)

**Recommend** we display as either a (count) float or a computed value of (chain_length * 4KB)

### Poller

n/a (dashboards/cmode/disk.json)

### Version

harvest version 24.02.1221-nightly (commit fb74b201) (build date 2024-02-12T21:36:16+0000) linux/amd64

### OS and platform

Amazon Linux 2023, native 

### ONTAP or StorageGRID version

9.14.1

**Comment by cgrinds** [comment]
Thanks for reporting @george-strother. We'll fix that. 

I'll change the unit to locale, that feels like a good fit for "Average number of blocks transferred".
The locale unit adds grouping separators depending on locale, so in the US that means 12990 is displayed as 12,990.

**Comment by cgrinds** [comment]
@george-strother and I discussed and he is going to submit PR for this change. Thanks @george-strother!

**Comment by cgrinds** [comment]
Fixed by #2666
