### ISSUE TITLE
Make vendored copy of dependencies

### ISSUE THREAD

**Issue by chrishenzie** [NetApp/harvest#27]
This is a small change. I've found that using vendored dependencies can help reduce build flakiness, particularly when the project has many dependencies it pulls in. It doesn't look like there are many here, but maybe this can help future proof it.

**Comment by cgrinds** [comment]
@chrishenzie thanks for the issue and PR.

We use vendoring to build on air-gapped machines in the lab, but as you pointed out, we aren't adding the `vendor` directory to SCM. 

The pros are:
* reproducible builds - upstream renames or deletions don't affect us
* slightly faster builds

cons are:
* slight repo bloat

Any other cons I'm missing? 

A quick sampling of other Go projects: 
* Vendors: k8 and all Hashicorp's projects
* Does not: Influx and Prometheus

I think this makes sense for Harvest. Thanks

**Comment by cgrinds** [comment]
Fixed by #108. Thanks @chrishenzie
