### ISSUE TITLE
Unit Ambiguity in QOS Adaptive Policy Configuration

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2719]
The QOS adaptive policy configuration can be set in either IOPS/GB or IOPS/TB. Currently, Harvest only publishes the value of this configuration, without specifying the unit. We should address this by converting all values to TB (which is the default) or another consistent unit.

<img width="577" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/1d9d6129-067d-4a47-af55-226b2a6e7298">
<img width="1918" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/1ff13ba7-4015-4dc5-831d-80beee21bb02">

**Comment by Hardikl** [comment]
verified in 24.05 release branch at commit 74dcf38a872d2c38e633664314e0acc5b9f8d76b,

From Ontap,
<img width="601" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/98e49512-1744-4ceb-95fb-3e213a8aa11b">

Consider for `bbbbb` and `mnop` named whose value converted from GB to TB.

From Prometheus,
<img width="1770" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/22cea0c7-dc84-431e-8744-57738c810444">

<img width="1770" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/d757358d-4a9c-4a93-b2ef-eaa5f3848fbf">


<img width="1772" alt="image" src="https://github.com/NetApp/harvest/assets/83282894/321b4ecc-2053-4b20-a3d7-bf1d54b3e9d0">
