### ISSUE TITLE
Investigate improving RestPerf Collector

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2729]
Investigate whether the RESTPerf URL can use the following format for requests.

```api/cluster/counter/tables/qos/rows?fields=*&counters.name=ops|read_io_type_base```

**Comment by cgrinds** [comment]
Verified on 24.05.0 commit 74dcf38a

`/api/cluster/counter/tables/volume/rows?counters.name=nfs.lookup_latency|nfs.setattr_ops|nfs.write_ops|total_write_ops|nfs.getattr_ops|nfs.lookup_ops|nfs.total_ops|nfs.read_latency|nfs.write_latency|nfs.access_ops|nfs.read_ops|read_latency|total_ops|total_other_ops|total_read_ops|bytes_written|nfs.other_ops|average_latency|nfs.getattr_latency|nfs.punch_hole_ops|nfs.setattr_latency|other_latency|write_latency|nfs.access_latency|nfs.other_latency|nfs.punch_hole_latency|bytes_read&fields=*&return_records=true`
