### ISSUE TITLE
Improve ZAPI client timeout handling

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#274]
See https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#some-of-my-clusters-are-not-showing-up-in-grafana

A downside to editing `default.yaml` is your edits may be overwritten on next upgrade. Other options:
- A separate directory not touched by upgraded
- Increase the out-of-the-box value from 10s to something higher
- Eliminate the need for a timeout by making the code more adaptive
- Understand implications to polling schedule

**Comment by rahulguptajss** [comment]
Can this be closed?

**Comment by cgrinds** [comment]
21.11 supports overriding `client_timeout` in object template files and increases a few of the out-of-box-defaults. Closed by #617
