### ISSUE TITLE
Harvest should ignore performance counters with partial aggregation

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2769]
## Background
After resolving some of the counter spike issues in #2597 and #2544, the frequency of spikes has decreased. However, as reported by @summertony15, there are still occurrences where Harvest reports high latency (up to approximately 200 seconds) and around 200 million ops. 

When ONTAP is under load or a node is down, it may report partial aggregation results. Objects that have their stats collected across nodes can be affected by this. Processing partial aggregation results can lead to incorrect data.

### Example Scenario
Consider the following scenario for ops:

- The first poll data is correct, providing complete aggregation.
- The next poll is a partial aggregation, which may result in a negative delta, so we skip that result.
- If the subsequent poll is a complete aggregation, the delta of the last two polls will result in abnormally high values, skewing most performance counters.

## Proposal
The proposal is to not process these partial aggregation results. ONTAP provides this information at the instance level for both ZAPI and REST.

**Zapi Response** (in json)

```json
    "instances": {
      "instance-data": [
        {
          "aggregation": {
            "aggregation-data": {
              "constituent-count": "2",
              "result": "complete_aggregation"
            }
          },
```

**Rest Response**

```json
  "aggregation": {
                "count": 2,
                "complete": true
            },
```

## Affected Harvest Objects
The following Harvest objects can experience partial aggregation:

- `namespace`
- `nfsv4_2`
- `nfsv4_2:node`
- `copy_manager`
- `flexcache_per_volume`
- `lun`
- `nfsv3`
- `nfsv3:node`
- `nfsv4`
- `nfsv4_1`
- `nfsv4_1:node`
- `nfsv4:node`
- `nvmf_tcp_port`
- `qtree`
- `system:node`
- `volume:node`
- `volume:vserver`
- `workload`
- `workload_volume`

## Next Steps

1. Add more logging for partial aggregation and Implement logic to skip processing partial aggregations alongside enhanced logging.
2. Suggest `jitter` to reduce the occurrence of partial aggregations. If ONTAP is under constant load and unable to retrieve complete aggregation results for such objects, dropping partial aggregated results may lead to significant gaps in customer Grafana graphs.To mitigate this, we should also consider activating `jitter` option for performance templates. This could help reduce the load on ONTAP and increase the probability of obtaining complete aggregation results. However, if complete results still cannot be provided, we will drop those results.

More details [here](https://github.com/NetApp/harvest-private/discussions/174)

**Comment by cgrinds** [comment]
Customer validated and unit tests cover
