### ISSUE TITLE
Duplicate series error during join queries

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2782]
Thanks @ybizeul for reporting.

<img width="485" alt="image" src="https://github.com/NetApp/harvest/assets/25551691/6be2c9ff-fe1b-4d6d-9464-3c4ab7b04aca">

From the screenshot, it seems that the poller port has changed. We should investigate whether the instance label can be ignored during join queries in Prometheus/Grafana.

**Comment by cgrinds** [comment]
We decided there are no changes required
