### ISSUE TITLE
Harvest should create resolution metrics for health alerts

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2804]
Thanks @faguayot for raising [here](https://github.com/NetApp/harvest/issues/2315#issuecomment-2010191616)

**Comment by faguayot** [comment]
Hello @rahulguptajss,
I was trying the nightly but I don't know what is the name of new metric that you have created for **health**? I was checking `health_ha_alerts` which is an old metric but I don't find any information on that. 

The other alerts related to health that I have in my prometheus database are the following:

![image](https://github.com/NetApp/harvest/assets/85484449/29322c9e-f5a5-422b-b99c-452ee73f1600)

Thanks.

**Comment by faguayot** [comment]
Ok, in that case I can't check the information until something happens in the HA. I thought that you write everytime the good state (in this case a 0) and when something happens you will write a 1 (failed state). I don't know if you can test it and show me the information available for the metric.

When something happens in our environment, I will be pending to review these parameters. Thanks for the implementation.

**Comment by Hardikl** [comment]
Verified in 24.08 with commit 4e3945c1

When home port is changed via UI
<img width="1779" alt="image" src="https://github.com/user-attachments/assets/76563708-e8d9-4684-87e7-ba7482352e4c">


When the port reverted to home port via UI
<img width="1775" alt="image" src="https://github.com/user-attachments/assets/e7d94369-1187-4b58-a7c5-214d874d8b4c">
