### ISSUE TITLE
Rest/Zapi parity for volume_labels

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2821]
**Zapi Response**

volume_labels{aggr="aggr0", cluster="umeng-aff300-01-02", datacenter="u2", instance="dc-1:12992", isEncrypted="false", isHardwareEncrypted="false", is_sis_volume="false", job="harvest", node="umeng-aff300-01", node_root="true", root_volume="Yes", snapshot_autodelete="true", state="online", style="flexvol", svm="umeng-aff300-01", type="rw", volume="vol0"} 1

**Rest response**

volume_labels{aggr="aggr0", cluster="umeng-aff300-01-02", datacenter="u2", , instance="dc-1:12992", isEncrypted="false", isHardwareEncrypted="true", is_sis_volume="false", job="prometheus", node="umeng-aff300-01", state="online", style="flexvol", svm="umeng-aff300-01", type="rw", volume="vol0"}

**Missing labels in Rest**

node_root                         => no mapping in Rest. Also this field is used to generate `root_volume` label in Zapi.
root_volume                     => added in #2816
snapshot_autodelete      => Need an endpoint to fill this

**Comment by Hardikl** [comment]
Tested in 24.05 release branch at commit 74dcf38a872d2c38e633664314e0acc5b9f8d76b,

First, With this changes https://github.com/NetApp/harvest/pull/2854, node_volumes (vol0) won't be exported in zapi and rest response don't have them.

validating for these labels: node_root, root_volume, snapshot_autodelete
**node_root:** Rest don't have `node_root` field. 
**root_volume:** working as designed.
**snapshot_autodelete:**  working as designed.


In Zapi,
```
volume_labels{aggr="umeng_aff300_aggr2", cluster="umeng-aff300-01-02", datacenter="zapi", instance="localhost:13001", isEncrypted="false", isHardwareEncrypted="false", is_sis_volume="false", job="c1", junction_path="/", node="umeng-aff300-01", node_root="false", root_volume="Yes", snapshot_autodelete="false", snapshot_policy="default", state="online", style="flexvol", svm="vs", svm_root="true", type="rw", volume="vol"}
```

In Rest,
```
volume_labels{aggr="umeng_aff300_aggr2", antiRansomwareState="disabled", cluster="umeng-aff300-01-02", datacenter="rest", instance="localhost:13001", isEncrypted="false", isHardwareEncrypted="true", is_sis_volume="false", job="c1", junction_path="/", node="umeng-aff300-01", root_volume="Yes", snaplock_type="non_snaplock", snapshot_autodelete="false", snapshot_policy="default", state="online", style="flexvol", svm="vs", svm_root="true", type="rw", volume="vol"}
```
