### ISSUE TITLE
Quota metrics should remove index from label

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2867]
As part of both the Zapi and REST plugins, quota metrics include an `index` label that is incremented according to the order of the response. This causes problems, as reported in [Discord](https://discord.com/channels/855068651522490400/1224702085983895552/1235463001335664722) discussion. This happens because if a quota is deleted, the ordering may change since the index is incremented based on the order received from the Zapi/REST response.

The primary reason for the index is to do joins in the quota dashboard. This can be resolved by using the adaptive workload table query format, where we generate a unique ID from labels within the dashboard itself.

```
quota_disk_used{cluster="A250-41-42-43", datacenter="nane", index="A250-41-42-43_1", instance="localhost:13001", job="prometheus", qtree="xxxx", svm="xxxx", type="tree", unit="Kbyte", volume="xxx"}
```

**Comment by cgrinds** [comment]
Thanks Alessandro for reporting!

**Comment by cgrinds** [comment]
Verified on 24.05.0 commit 74dcf38a
index is no longer exported and Quota dashboard shows table of quotas
