### ISSUE TITLE
Remove duplicate quota metrics

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2885]
Currently Harvest publishes quota metrics under qtree and quota prefix both. This was done for backward compatibility reasons but given quota metrics can be very high , this leads to 2x problem for these metrics. For one of the cluster quota metrics were in range of 500k which lead it to become 1 million. 

Harvest should disable these duplicate metrics by default and use quota prefix and allow it to be enabled via a flag for backward compatible support. Leaving handlingHistoricalMetrics as is.

**Comment by Hardikl** [comment]
In 24.02 release branch,
```
harvest % curl -s http://localhost:13001/metrics | grep qtree_disk_used{ | wc -l
      44
harvest % curl -s http://localhost:13001/metrics | grep quota_disk_used{ | wc -l
      44
```

Verified in main branch at commit 74dcf38a872d2c38e633664314e0acc5b9f8d76b,
```
harvest % curl -s http://localhost:13001/metrics | grep quota_disk_used{ | wc -l
      44
harvest % curl -s http://localhost:13001/metrics | grep qtree_disk_used{ | wc -l
       0

```
