### ISSUE TITLE
Docker Hub Publishing for use in OpenShift / Kubernetes Platform

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#291]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could push the docker image then to docker hub as well. 

**Describe the solution you'd like**
We want to use this image then in an openshift/kubernetes infrastructure. Would be nice if you maybe could also take in consideration to document how to get this working

**Comment by cgrinds** [comment]
hi @florianmulatz we're in the process of publishing the [one-poller-per-container](https://github.com/NetApp/harvest/tree/5341e6e5f539c6a8bdee70ddaf63e1c080d0bb8a/docker/onePollerPerContainer) image to NetApp's org on DockerHub. In the meantime, we've published the image under @rahulguptajss account [here](https://hub.docker.com/r/rahulguptajss/harvest).

Feel free to try this image out and let us know if it suits your needs while we get it moved to the right place.
