### ISSUE TITLE
metrics when node is down

### ISSUE THREAD

**Issue by natke889** [NetApp/harvest#2916]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Hi,

When node is down for example the collector still showing the last values that gather when node was functioning.
for example I keep seeing the node IOPS on times when node was down. 

is there a way to change this behavior to show nulls or zero when can't pull data ?

### Poller

PerfRest

### Version

24.05

### OS and platform

docker

### ONTAP or StorageGRID version

9.15.1

**Comment by cgrinds** [comment]
Closing. Feel free to reopen @natke889 if you get a chance to get back to this
