### ISSUE TITLE
Dashboard for the Tiers storage

### ISSUE THREAD

**Issue by razaahmed** [NetApp/harvest#2973]
I would like to request a dashboard for the Tiers storage showing Hot/Cold data usage trand

**Comment by tymercer** [comment]
seconded, would be super useful

**Comment by razaahmed** [comment]
Thanks for looking into this.  Personally, I would like to capture the following:

aggr show-space -fields aggregate-size,physical-used,physical-used-percent,performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent,object-store-logical-used,object-store-physical-used

for the volume, vol show doesn't give you details on "used in local tier, and "used in cloud tier" info, otherwise that would be a great addtion

**Comment by razaahmed** [comment]
Thanks for the update. hopefully will be able to try it soon

**Comment by raza-sky** [comment]
Thanks @rahulguptajss I just upgraded to 24.06.27-nightly. It works for me except I see "no data" on aggregates by logical space used in object store and aggregates by physical space usage in object store.

**Comment by razaahmed** [comment]
Thanks @rahulguptajss I just upgraded to 24.06.27-nightly. It works for me except I see "no data" on aggregates by logical space used in object store and aggregates by physical space usage in object store.

**Comment by razaahmed** [comment]
> > @razaahmed Could you share output of below curl with us via email @ [ng-harvest-files@netapp.com](mailto:ng-harvest-files@netapp.com)
> > Please note that the USERNAME, PASSWORD, URL should be replaced with the appropriate credentials.
> > ```
> > curl -s -k -u USERNAME:PASSWORD 'https://URL/api/private/cli/aggr/show-space?return_records=true&fields=object_store_logical_used,object_store_physical_used,bin_num,tier_name'
> > ```
> 
> @razaahmed Could you share output of this Rest API.

I am getting error:
404 page not found

**Comment by cgrinds** [comment]
@razaahmed what version of ONTAP is your cluster?

**Comment by razaahmed** [comment]
9.11, 9.12 and 9.13

**Comment by cgrinds** [comment]
That CLI command should be there for 9.11, as shown below.
Let's make sure that REST is enabled for the cluster that returned a 404.

Does this work? Replace ip, user, and pass.

```bash
curl -s -k -u $user:$pass 'https://$ip/api/cluster?return_records=true&fields=version,name'
```

```json
{
  "name": "umeng-aff300-01-02",
  "version": {
    "full": "NetApp Release Mightysquirrel__9.15.1: Fri May 24 05:03:10 UTC 2024",
    "generation": 9,
    "major": 15,
    "minor": 1
  },
  "_links": {
    "self": {
      "href": "/api/cluster"
    }
  }
}
```                                

```bash
curl -s -k -u $user:$pass 'https://$ip/api/private/cli/aggr/show-space?return_records=true&fields=object_store_logical_used,object_store_physical_used,bin_num,tier_name'
```

```json
{
  "records": [
    {
      "aggregate_name": "aggr0",
      "bin_num": 0,
      "tier_name": " "
    },
    {
      "aggregate_name": "aggr0_umeng_aff300_02_0",
      "bin_num": 0,
      "tier_name": " "
    },
    {
      "aggregate_name": "test1",
      "bin_num": 0,
      "tier_name": "Performance Tier"
    },
    {
      "aggregate_name": "test1",
      "bin_num": 1,
      "tier_name": "Object Store: sg-ontap1",
      "object_store_physical_used": 0,
      "object_store_logical_used": 0
    },
    {
      "aggregate_name": "umeng_aff300_aggr2",
      "bin_num": 0,
      "tier_name": " "
    }
  ],
  "num_records": 5
}
```

**Comment by razaahmed** [comment]
I miss understood. I was pointing to grafana instead of filer. here is the output

sical_used,bin_num,tier_name'
{
  "records": [
    {
      "aggregate_name": "aggr0_01_root",
      "bin_num": 0,
      "tier_name": " "
    },
    {
      "aggregate_name": "aggr0_02_root",
      "bin_num": 0,
      "tier_name": " "
    },
    {
      "aggregate_name": "aggr1",
      "bin_num": 0,
      "tier_name": "Performance Tier"
    },
    {
      "aggregate_name": "aggr1",
      "bin_num": 1,
      "tier_name": "Object Store: local_ontap_s3",
      "object_store_physical_used": 35144895150624,
      "object_store_logical_used": 35360459766176
    },
    {
      "aggregate_name": "aggr2",
      "bin_num": 0,
      "tier_name": "Performance Tier"
    },
    {
      "aggregate_name": "aggr2",
      "bin_num": 1,
      "tier_name": "Object Store: local_ontap_s3",
      "object_store_physical_used": 97797447724128,
      "object_store_logical_used": 98622360153376
    }
  ],
  "num_records": 6

**Comment by Hardikl** [comment]
Tested in 24.08 with commit 0a2d140c

<img width="1787" alt="image" src="https://github.com/user-attachments/assets/0e693db6-1f14-4f50-aeb2-ef8fcb394c5b">


<img width="927" alt="image" src="https://github.com/user-attachments/assets/7dbd91eb-4d46-401f-a8df-33803e7a9a25">

<img width="908" alt="image" src="https://github.com/user-attachments/assets/a32472ab-7bd6-4cdf-bbb7-955ec138a65b">
