### ISSUE TITLE
NetApp Detail: Volume Dashboard / space used column does not reflect current fill grade as graphic

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#303]
Volume dashboard shows a incomplete grade of filling in the table of volumes

**To Reproduce**
Open the NetApp Detail: Volume

**Expected behavior**
Last column in table should reflect the current fill-state of volume in conjunction to value

**Actual behavior**
Graph shows always the same fill-state
![image](https://user-images.githubusercontent.com/33655308/125610269-b482e3f6-f915-43a8-8912-ae5359b8be6f.png)

**Possible solution, workaround, fix**
Set an override property for the "space used" column "Standard options > Max" and set the value to 100
![image](https://user-images.githubusercontent.com/33655308/125610384-3bded168-8e64-4cf9-8f1d-7590f7396f82.png)

**Comment by cgrinds** [comment]
thanks for reporting @florianmulatz - this should be fixed now

**Comment by florianmulatz** [comment]
confirmed - is working as expected now! Thx
