### ISSUE TITLE
Feature request for Dashboard template for ontaps3 metrics

### ISSUE THREAD

**Issue by gaow1423** [NetApp/harvest#3055]
**Is your feature request related to a problem? Please describe.**
I re-enable the ontap s3 metrics on 24.02.0 release by uncommenting those ontaps3 metrics templates. It'd be good if we have some dashboard templates for those ontaps3 metrics.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cgrinds** [comment]
Thanks for the feature request @gaow1423. 

Have you built an s3 metrics dashboards already or have any input on which metrics are most important?

**Comment by cgrinds** [comment]
See also https://discord.com/channels/855068651522490400/1265265157479862335/1275400044769579132

**Comment by Hardikl** [comment]
Default `ontap_s3_svm ` template is disabled and dashboard look like this, 

<img width="1780" alt="image" src="https://github.com/user-attachments/assets/a433fba0-8054-477a-819f-5b85da74708f">
