### ISSUE TITLE
Change Harvest metrics to use a one for healthy

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#306]
Raised by hashi825 in #262 

Few notes from chat with team:

- The reason we map label values into a numeric value (0 or 1), is that you can't generate alerts in Grafana from labels, only numbers
- Originally 0 represented ok in Harvest because many statuses are enums that were mapped like this:

| enum      |  int |
| --------- | ---: |
| ok        |    0 |
| fail      |    1 |
| missing   |    2 |
| error     |    3 |
| not_found |    4 |

**Comment by Hardikl** [comment]
earlier: 
cluster_status{cluster="C2_sti7-vsim-ucs569c_cluster", datacenter="DC-02", instance="localhost:12992", job="prometheus2", status="ok"} | 0
-- | --

now:

cluster_new_status{cluster="C2_sti7-vsim-ucs569c_cluster", datacenter="DC-02", instance="localhost:12992", job="prometheus2", status="ok"} | 1
-- | --

Node new status:
![image](https://user-images.githubusercontent.com/83282894/126620476-ea0dc3e6-f5ad-47e5-ada4-9c199ff57817.png)

Cluster new subsystem: 
![image](https://user-images.githubusercontent.com/83282894/126620559-0195510a-8b09-41ff-9c2f-7285d586022e.png)

Cluster new status:
![image](https://user-images.githubusercontent.com/83282894/126620610-0dec4571-1ea4-48c3-8de9-2355c73c25be.png)

Aggregate new status:
![image](https://user-images.githubusercontent.com/83282894/126620712-3a3cbe57-31c1-4631-bfc5-b9356c5df72b.png)

Shelf new status:
![image](https://user-images.githubusercontent.com/83282894/126620922-4cb06dab-cc8f-4735-b623-8a58088bbd70.png)

Volume new status:
![image](https://user-images.githubusercontent.com/83282894/126621041-6aa0f95b-aa76-4fd3-bbf1-a4cac7aa0b57.png)


normal/online/ok value mapped to 1 and rest non normal value mapped to 0.
With these detail, moving to status/done.
