### ISSUE TITLE
Node Power Metrics not pulled from 9.15.1RC1 or A90/A1K

### ISSUE THREAD

**Issue by jgasher** [NetApp/harvest#3062]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Node power metrics are zero on A1K and A90 systems in my lab.  These systems are running 9.15.1RC1 and I don't know if the problem is with ONTAP or the new system architecture.  Metrics from a C800 running 9.12.1 are working as expected on the same server.

### Configuration

```text
snippet of harvest configuration

vino-a90-1:
    addr: 10.63.122.160
    autostart: '1'
    collectors:
      - Zapi
      - ZapiPerf
      - Rest
      - Ems
    datacenter: 5091-Nvidia

    prometheus_port: 12999
    use_insecure_tls: true
```

### Poller

vino-a90-1

### Version

v24.05.2

### Poller logs

```text
I'm unable to pull the logs but this is an internal NetApp system and I can provide access.
```

### OS and platform

nabox 3.2

### ONTAP or StorageGRID version

9.15.1RC1

### Additional Context

No.  Contact jasher@netapp.com for more info and access to the systems.

**Comment by cgrinds** [comment]
Verified on 24.08.0 commit 0a2d140c

go run cmd/poller/poller.go --config cbg/harvest.openlab.yml --promPort 12990 --poller a1k --collectors Rest --objects Sensor

curl -s 'http://localhost:12990/metrics' | sort | rg -v '^#|metadata' | rg power
environment_sensor_power{cluster="a1k",datacenter="5090-N",node="a1k-01"} 904
environment_sensor_power{cluster="a1k",datacenter="5090-N",node="a1k-02"} 912
