### ISSUE TITLE
Prometheus is unable to connect to the poller port after harvest upgrade: dial tcp 10.10.10.10:15019: connect: connection refused

### ISSUE THREAD

**Issue by madhusudhanarya** [NetApp/harvest#308]
**Describe the bug**
I upgraded harvest to latest version 21.05.3 yesterday. After the upgrade, Prometheus is unable to scrap the metrics and showing   "dial tcp 10.10.10.10:15019: connect: connection refused" error.

In the harvest log file, i can see below error.

{"level":"error","Poller":"clus01","caller":"command-line-arguments/poller.go:630","time":"2021-07-14T23:09:30-07:00","message":"no exporter of name:type prom80:prometheus"}

There are no changes to the harvest.yml file. We are using the same file from GA version of the harvest 2.0 and it was working fine till the upgrade.

**Environment**
- Harvest version: harvest version 21.05.3-2 (commit b482aff) (build date 2021-06-28T21:08:05+0530) linux/amd64
- Command line arguments used: harvest start clus01
- OS: CentOS Linux release 7.9.2009 (Core)
- Install method: YUM
- ONTAP Version: 9.8P4

**To Reproduce**
NA

**Expected behavior**
Prometheus should continue to scrap the metrics

**Actual behavior**
Prometheus is failing to scrap metrics

**Comment by cgrinds** [comment]
hi @madhusudhanarya can you share your harvest.yml? If it has sensitive info, you can redact using `bin/harvest doctor --print`

Going by what you've pasted above, also double check that the exporter: value is `Prometheus` (capital P) not `prometheus` (lower case P).
```
Exporters:
    prom80:
        exporter: Prometheus
```

**Comment by madhusudhanarya** [comment]
Thank you @cgrinds. Updating "prometheus" to "Prometheus" has fixed the issue.
