### ISSUE TITLE
Changes in /opt/harvest/conf/zapiperf/cdot/9.8.0/volume.yaml file was overwritten during harvest upgrade

### ISSUE THREAD

**Issue by madhusudhanarya** [NetApp/harvest#309]
**Describe the bug**
We have made few custom changes to /opt/harvest/conf/zapiperf/cdot/9.8.0/volume.yaml file. During harvest upgrade, this changes have been overwriiten.

Harvest version: harvest version 21.05.3-2 (commit b482aff) (build date 2021-06-28T21:08:05+0530) linux/amd64
Command line arguments used: harvest start clus01
OS: CentOS Linux release 7.9.2009 (Core)
Install method: YUM
ONTAP Version: 9.8P4

**To Reproduce**
Make some changes to volume.yaml file and run harvest update

**Expected behavior**
Config files should not be overwritten during the upgrade.

**Actual behavior**
Custom changes made to the volume.yaml file was overwritten

**Possible solution, workaround, fix**
Make a copy of the production file and diff it against the default one in the RPM. If there are any changes, copy the production file to another location and ask customer to check and copy back his file to required path

**Comment by cgrinds** [comment]
hi @madhusudhanarya we added sub-templates for customer edits. Does [this line of documentation](https://github.com/NetApp/harvest/wiki/FAQ#ontap-counters-are-missing) address your issue?

**Comment by madhusudhanarya** [comment]
Hi @cgrinds: we need to implement below feature. 

https://github.com/NetApp/harvest/issues/209

can you suggest how i can do this using sub-templates?

**Comment by cgrinds** [comment]
@madhusudhanarya - it's not completely possible until #124 is finished. You can get close with the following

```
cp conf/zapi/cdot/9.8.0/volume.yaml conf/zapi/cdot/9.8.0/tagvolume.yaml
```

- Create a `conf/zapi/custom.yaml` and copy/paste the following into it to use the new template
```
collector:          Zapi

# Order here matters!
schedule:
  - instance: 600s
  - data: 180s

objects:
  Volume:           tagvolume.yaml
```

- update `conf/zapi/cdot/9.8.0/tagvolume.yaml` with details in #209. This only needs to be done once
- edit `conf/zapi/default.yaml` and comment out `  #Volume:           volume.yaml` - this will be overwritten until #124 is added

Bounce harvest and you will see the tagged volumes

**Comment by madhusudhanarya** [comment]
Thank you @cgrinds. Was able to get custom labels working after following above instructions. We can close this issue.

**Comment by cgrinds** [comment]
awesome - glad you got it working!
