### ISSUE TITLE
Tenants Dashboard should include column: average size per object

### ISSUE THREAD

**Issue by ofu48167** [NetApp/harvest#3090]
**Is your feature request related to a problem? Please describe.**
In our StorageGrid we have many different types of data, they greatly vary in size per object.

**Describe the solution you'd like**
Show column: avg size per object in panel "Tenant Quota"

**Describe alternatives you've considered**
`none`

**Additional context**
please use this optimized harvest/grafana/dashboards/storagegrid/tenant.json

[tenant.json](https://github.com/user-attachments/files/16524735/tenant.json)

**Comment by cgrinds** [comment]
@ofu48167 thanks for the contribution! We'll include this additional column

**Comment by Hardikl** [comment]
verified in 24.08 with commit 0d2d7b4c

<img width="1776" alt="image" src="https://github.com/user-attachments/assets/80ad05f3-e322-4684-b6cc-402095a5c8a0">
