### ISSUE TITLE
Harvest should include a Vscan dashboard

### ISSUE THREAD

**Issue by T1r0l** [NetApp/harvest#3114]
the vscan.yaml template is disabled by default, and the metrics generated from it are not included in any dashboards.
could you please add a vscan dashboard in the next harvest release?

counters:
  - instance_name
  - instance_uuid
  - scan_latency
  - scan_request_dispatched_rate
  - scanner_stats_pct_cpu_used
  - scanner_stats_pct_mem_used
  - scanner_stats_pct_network_used

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
ONTAP: Vscan dashboard includes 10 panels
