### ISSUE TITLE
Usage of wrong labels in alert rules definition 

### ISSUE THREAD

**Issue by Hardikl** [NetApp/harvest#3142]
Thanks to roller for reporting on [Discord](https://discord.com/channels/855068651522490400/1265265157479862335/1275400044769579132)

Issue:
Alert rules definition using the wrong labels which haven't been exported from the Harvest.

Reference Discord thread: https://discord.com/channels/855068651522490400/1062050414146625536/threads/1265265157479862335

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
