### ISSUE TITLE
tenant dashboard should include graphs for tenants and buckets over time

### ISSUE THREAD

**Issue by ofu48167** [NetApp/harvest#3145]
**Is your feature request related to a problem? Please describe.**

I want to see growth of a tenant/a bucket over time.

**Describe the solution you'd like**
have a dashboard panel where you can see lines of growth of a tenant or bucket.

**Describe alternatives you've considered**
none
[tenant.json](https://github.com/user-attachments/files/16963433/tenant.json)

**Additional context**
As I am not an expert yet, please review carefully what I did here...
Also, I added a filter for TopResources here...

**Comment by cgrinds** [comment]
Thanks for the contribution @ofu48167! I've merged your changes with the latest Tenant dashboard. How does this look?

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/a292c73a-c469-41d4-a129-0b240c890a69">

**Comment by ofu48167** [comment]
yeah, exactly what I intended.... TopResources seems also to be working fine :)
