### ISSUE TITLE
ONTAP: Power Dashboard - Add kW/h Panel

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3156]
**Is your feature request related to a problem? Please describe.**
Feature request for the Power dashboard

**Describe the solution you'd like**
An additional panel where the metrics are calculated to kW/h. Currently there is Total Power but this shows the current value. It would be interesting to have a panel which shows the total kW/h value. 

**Describe alternatives you've considered**
No

**Additional context**
This is used for our sustainability initiative.

**Comment by BrendonA667** [comment]
Hi @rahulguptajss this is exactly what would fit in the existing power dashboard.

**Comment by cgrinds** [comment]
HI @BrendonA667 these changes are in the latest [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) build if you want to try them out. Alternatively, you can import the [power.json](https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/power.json) dashboard from the repo too.

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57

<img width="535" alt="image" src="https://github.com/user-attachments/assets/3525fbb3-b056-4450-ac6b-f0ab74040c20">
