### ISSUE TITLE
ONTAP: SVM Dashboard - Volume Capacity row ordering

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3157]
**Is your feature request related to a problem? Please describe.**
Feature request to improve the SVM dashboard.

**Describe the solution you'd like**
Change the ordering of the panels in the volume capacity rows that physical and logical used is on top instead of deduplication, compression and total efficiency savings. This would look like in the Aggregate dashboard

**Describe alternatives you've considered**
No

**Additional context**
Dashboard would be more readable

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/fec14731-ef8b-454a-97a2-009e3f8c963a">
