### ISSUE TITLE
Feature: Creating a metric to track packet loss

### ISSUE THREAD

**Issue by jperez08** [NetApp/harvest#316]
Having a metric to track packet loss would be helpful when troubleshooting/monitoring network congestion, hardware failure, etc

**Comment by MrObvious** [comment]
I'm not sure if there is a CM counter, but there is netstat and the 9.5+ option has packet loss columns. This may be helpful: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_view_network_connections_on_different_versions_of_ONTAP

**Comment by cgrinds** [comment]
This is covered by #1386. Closing
