### ISSUE TITLE
Issue with Aggregation in FSA Multi-Select History Panels

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#3160]
Thanks, 70tas, for reporting this issue on [Discord](https://discord.com/channels/855068651522490400/1286020106392043540).

### Issue Description

The FSA multi-select feature should use `sum` instead of `avg` for the history panels. Additionally, the percentage history panels should use a weighted average to accurately reflect data usage across multiple volumes.

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
70tas on Discord also verified in an earlier nightly
