### ISSUE TITLE
Harvest should add ifgroup(LAG) throughput metrics

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#3161]
Thanks, imthenightbird, for reporting this issue on [Discord](https://discord.com/channels/855068651522490400/1275113959854440540).

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
Link Aggregation Group row is in the `ONTAP: Network` dashboard.
imthenightbird also confirmed, in an earlier nightly build, that these three new panels contained the correct data
