### ISSUE TITLE
volume perf plugin failed when flexvol naming has __000x

### ISSUE THREAD

**Issue by Hardikl** [NetApp/harvest#3201]
Thanks to florent4155 for raising on [Discord](https://discord.com/channels/855068651522490400/1290344751089844255/1290344751089844255).

Due to different naming of flexvol, it's not guarantee to decide the volume is `flexgroup_constituent` or `flexvol` just based on `__000x` regex, which eventually creating duplicate instance error and later nil pointer exception due to invalid map access as shown in below.

This is one of the volume which is flexvol: `TR0_P04_0010_pol_svm41_poll_vf257_v07_Backup__0001`

<img width="1755" alt="image" src="https://github.com/user-attachments/assets/ee5f4f7d-7217-47ee-80e7-aa9462ed1509">

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
florent4155 also verified in an earlier nightly build
