### ISSUE TITLE
Net Port health status metric

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3211]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
A possibility to collect the health status of a port which can be degraded because of the L2_reachability which was implemented in ONTAP 9.13.1

https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/Native_VLAN_ports_show_degraded_after_upgrade_to_ONTAP_9.13.1

**Additional context**
With that we can avoid issued prio to a ONTAP upgrade or missconfiguration of a switch

**Comment by Hardikl** [comment]
That's a useful feature request, @BrendonA667.  Thanks for the suggestion. 
Here are a few questions to help us add this feature:
- Which dashboard should include the health status of a port? Should we add it to the Health dashboard or the Network dashboard? Do you have any preference?
- It appears that the port status is available for both Ethernet and Fibre Channel ports. Would you like to see the health status for both types of ports?

**Comment by BrendonA667** [comment]
Hi @Hardikl 
About the dashboard I would say in the Network dashboard. Main reason it is not a direct issue for the running system.

About Ethernet and FC. Since we only have Ethernet I cannot talk for FC but for the folks who use FC it would be nice :)

**Comment by cgrinds** [comment]
Verified in `24.11` ddb97c57
