### ISSUE TITLE
Track ONTAP image update progress for a cluster

### ISSUE THREAD

**Issue by knappmi** [NetApp/harvest#3218]
**Is your feature request related to a problem? Please describe.**
We have a large fleet of ONTAP clusters. Tracking update progress, duration, and status across the fleet is cumbersome and requires us to write automation to let us know if the update fails or is otherwise unhealthy. 

**Describe the solution you'd like**
ONTAP exposes a REST API for `/api/cluster/software` which will give us the phase infromation as well as phase status. Having this data scraped and formatted will help us track update progress.

**Describe alternatives you've considered**
We plan to use the Private Cli passthrough to gather the state information `cluster image show-update-progress` but the data is going to be minimal and we could use a more rich solution with alot more detail. 

**Additional context**
n/a

**Comment by cgrinds** [comment]
Verified on 25.02.0 commit 4b2cbc0b
