### ISSUE TITLE
Harvest should check for a new release

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#323]
When running `bin/harvest version` or `bin/harvest --version` determine whether there is a newer release of Harvest and if so print a link to the GitHub release.

**Comment by rahulguptajss** [comment]
It should be bin/harvest start also right? i doubt if many do bin/harvest version regularly.

**Comment by cgrinds** [comment]
Let's start with version first. The problem with start is you either: 1) delay startup, sometimes significantly, waiting for a client timeout or 2) async and log to a place no one sees

**Comment by mamoep** [comment]
Please keep in mind that "dark sites" and corporate proxies exist while designing this.

**Comment by cgrinds** [comment]
@mamoep the current PR for this includes the follwoing - do these address your concerns?

- You can skip the version check by using the arg version instead of the subcommand version.
`bin/harvest --version`

- there is a 5s timeout on the GitHub request and the version info is printed before the GitHub check. We log to the console when the request is happening and you can `Ctrl-C` if you don't want to wait for the timeout

**Comment by mamoep** [comment]
Sounds reasonable, thanks for the update!
