### ISSUE TITLE
ONTAP: Health dashboard "Active Emergency EMS Alerts" panel should link to ONTAP's syslog translator

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#3255]
For example, the highlighted cell should link to https://mysupport.netapp.com/site/bugs-online/syslog-translator?product=ontap&syslog=secd.lsa.noServers

<img width="387" alt="image" src="https://github.com/user-attachments/assets/b8a6fd28-856e-496e-a142-0a7b597cec28">

**Comment by Hardikl** [comment]
validate in main at commit db58b0b2,

<img width="622" alt="image" src="https://github.com/user-attachments/assets/797f540a-fd1f-429c-9e42-b2689970008b">

Below link redirect to https://mysupport.netapp.com/site/bugs-online/syslog-translator?product=ontap&syslog=secd.lsa.noServers
<img width="1776" alt="image" src="https://github.com/user-attachments/assets/5ef2c5e4-8dfb-4843-b86c-b6c5163ae7b4">
