### ISSUE TITLE
Exclude OS aggregates from capacity used graph

### ISSUE THREAD

**Issue by matejzero** [NetApp/harvest#327]
**Describe the bug**

On the cluster dashboard, capacity usage is calculates as `avg(netapp_aggr_space_used_percent{datacenter=~"$Datacenter",cluster="$Cluster"})`. This gives wrong result in my case where I have dedicated aggregates for NetApp OS (not sure if this is typical or not). I guess netapp makes them as small as possible and they are always 93%+ full, skewing the calculation.

![Screenshot 2021-07-21 at 16 20 25](https://user-images.githubusercontent.com/4689252/126504983-54f16143-a50b-45a5-8333-8d144ac470a9.png)

Capacity usage on the single panel graph is showing 78% instead of 62%, which is a lot of space in my case:)

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: `harvest version 21.05.3-2 (commit b482aff) (build date 2021-06-28T21:08:05+0530) linux/amd64`
- ONTAP Version: 9.7

**To Reproduce**

Load latest Cluster dashboard.

**Expected behavior**

Take only "data" aggregates into the account, to get more precise usage.

**Possible solution, workaround, fix**

Solution in my case is simple. Add an exclude filter to the metric: `avg(netapp_aggr_space_used_percent{datacenter=~"$Datacenter",cluster="$Cluster",aggr!~"aggr0_.+"})`

But I'm not sure, if this is a default name for the aggregates (aggr0_<filer name>-<node number>).

**Comment by ruanruijuan** [comment]
Relate to #99.

**Comment by cgrinds** [comment]
- Compare with UM capacity aggregate calculation
- Consider creating a plugin that ignores root-aggregate for ZAPIs (REST does this automatically)
