### ISSUE TITLE
making some rest calls in zapi settings

### ISSUE THREAD

**Issue by ekolove** [NetApp/harvest#3272]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

We upgraded to 24.11
The harvest account for monitoring only has ontap(izapi) permissions on storage

The message keeps occurring after the upgrade

(harvest puller log)
./poller_second-cluster.log:time=2024-11-08T15:22:29.101+09:00 level=ERROR source=poller.go:1424 msg="Failed to send Harvest version" Poller=second-cluster error="StatusCode: 401, Error: auth failed, Message: 401 Unauthorized, API: /api/cluster?fields=%2A&return_records=true"

---------------

(storage log)
Filer: second-node1
Time: Fri, Nov 08 14:22:25 2024 +0900
Severity: LOG_ALERT

Message: security.invalid.login: Failed to authenticate login attempt to
Vserver: second-cluster, username: harvest2, application: http.

Description: This message occurs when an attempt is made to access the appliance
by using invalid authentication credentials.

Action: Verify that the user made a genuine attempt to access the system. If
not, use the "security login delete" command to either remove the account or use
the "security login lock" command to lock the account to disallow access to the
system using that user account. Also, strengthen the authentication credentials
of the user account by updating it. More detail regarding the authentication
failure is available in audit.log file.

Source: mgwd
Index: 456959

[Note: This email message is sent using a deprecated event routing mechanism.
For information, search the knowledgebase of the NetApp support web site for
"convert existing event configurations in Data ONTAP 9.0."]

------------

This message occurs in all ONTAP 9.4 and above, and does not appear in 9.3 and below because they do not support REST.

Our harvest config is as follows:

second-cluster:
datacenter: 
addr: 
auth_style: basic_auth
username: harvest2
password: 
use_insecure_tls: true
tls_min_version: tls10
exporters:

collectors:
- Zapi
- ZapiPerf

### Poller

second-cluster

### Version

harvest version 24.11.0-1 (commit 29dddbb9) (build date 2024-11-06T08:56:41-0500) linux/amd64

### OS and platform

Rocky 8.9

### ONTAP or StorageGRID version

connected to second-cluster (NetApp Release 9.4P3: Thu Oct 11 22:23:50 UTC 2018)

**Comment by cgrinds** [comment]
hi @ekolove thanks for raising this. We're working on a fix and will update you when a nightly is available with the fix.

**Comment by cgrinds** [comment]
hi @ekolove this is fixed in [nightly](https://github.com/NetApp/harvest/releases/tag/nightly). Please give it a try when you get a chance and let us know if it solves the issue
