### ISSUE TITLE
Additional instance_labels for volume and svm

### ISSUE THREAD

**Issue by BrendonA667** [NetApp/harvest#3291]
**Is your feature request related to a problem? Please describe.**
Feature request for additional instance_labels for volume and svm

**Describe the solution you'd like**
Extend the volume_labels and svm_labels metric with is-space-reporting-logical and is-space-enforcement-logical labels.

**Describe alternatives you've considered**

**Additional context**
We have some volumes and svms where logical space reporting and enforcement is enabled. Whit this additional instance labels we could create a alarming based on these labels and with the corresponding metric.

**Comment by cgrinds** [comment]
hi @BrendonA667 these changes are in the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly) or you can copy the templates from the [pull request](https://github.com/NetApp/harvest/pull/3301/files) too.

**Comment by Hardikl** [comment]
verified in main at commit db58b0b2,

<img width="1769" alt="image" src="https://github.com/user-attachments/assets/c4a46ca1-7279-4810-a163-61b2140a6bee">

<img width="1761" alt="image" src="https://github.com/user-attachments/assets/65bb92cf-48f8-4290-a449-bfd5712d5fa4">

<img width="1759" alt="image" src="https://github.com/user-attachments/assets/1be638e4-960a-4d75-a509-c61b4e0798f7">

<img width="1779" alt="image" src="https://github.com/user-attachments/assets/aadedeb7-6e56-4106-8347-8a90361cd257">
