### ISSUE TITLE
Deprecate RHEL and Debian releases

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#330]
Reduce maintenance cost and better align with container direction.

Downloads by platform over the last couple of months
Docker is `schmots1/na_harvest` + `rahulguptajss/harvest`

| Platform | Count |    % |
|----------|------:|-----:|
| Deb      |    85 |   11 |
| RPM      |   183 |   24 |
| Native   |   195 |   26 |
| Docker   |   291 |   39 |
| Total    |   754 | 100% |

Please leave a thumbs-up or down if you feel strongly about this

**Comment by ruanruijuan** [comment]
Add a note: The Docker download is since July and the rest since May 20.

**Comment by hashi825** [comment]
While small, most enterprise environments will be using RPM based installations.

**Comment by lvicainne** [comment]
Hi !
I am a RHEL user.
Nonetheless, if no RHEL package is available any more, the usage of Docker container could be nice as long as it is deployable over standalone docker-compose commands and a easy docker-compose.yml configuration :)

**Comment by rahulguptajss** [comment]
@lvicainne Docker support is available for harvest. You can refer https://github.com/NetApp/harvest/blob/main/docker/onePollerPerContainer/README.md
https://github.com/NetApp/harvest/blob/main/docker/README.md

**Comment by faguayot** [comment]
Hello, 

I am not sure if I wrote something related the RHEL support in other issue but it is the installer that we are using. 
In our company and the different environment we use machines with RHEL which are customized by our security team, so it's not possible to use another operating system. Also to accomplish the installation of the product we have pipelines defined and additional code with ansible. What I am trying to say is, we will need to modify many things to change the way we deploy the product without RHEL support.

For now our goal is to understand the new harvest, see how is work, know the new features like the workloads (something that we were requering for a while).

In the future we can move to the docker option but we will need more time coexisting both versions together until we have the enough time for change our installation. 

Thanks for asking.

**Comment by wally007** [comment]
Same here - our company has dozens of Netapp devices and we only use RHEL (isn't every company stuck RHEL? :-) )

**Comment by chris-muc69** [comment]
I have switched to the tar.gz-version. So for me is is ok to to close.

Kind reagards
Chris

**Comment by hashi825** [comment]
Still using rpms here, I'm sure there are still people in the same boat as me in the enterprise sector that prefer rpm for the ability to audit software.

**Comment by cgrinds** [comment]
Thanks for the feedback everyone! 👍 

Based on the feedback, the Harvest team is going to continue building RPM, Debs, Native, and Docker artifacts.
