### ISSUE TITLE
Asup error messages in harvest logs

### ISSUE THREAD

**Issue by db-wally007** [NetApp/harvest#3322]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please let us know in a comment

### Problem

Every 24 hours, Harvest generates the 2 error messages for each poller in my configuration:

`time=2024-11-24T13:15:56.001Z level=ERROR source=poller.go:491 msg="Start autosupport failed." Poller=agora error="failed to send ASUP message poller:agora autosupport call to ./autosupport/asup timed out:signal: killed" poller=agora
`

Any idea what this is ?

I've tested AutoSupport from ONTAP SystemManager and that seems to work. 

![image](https://github.com/user-attachments/assets/b62077bb-072f-4c4f-b869-67355d31dc96)

can you please advise where this is coming from and how I can resolve the issue ?

### Poller

AGORA

### Version

24.08.0

### OS and platform

RHEL 9.4 , podman

### ONTAP or StorageGRID version

Netapp 9.13.1P8

**Comment by cgrinds** [comment]
hi @db-wally007 that log message is from the Harvest poller. Harvest has its own [auto-support](https://github.com/NetApp/harvest/tree/main/autosupport) that sends daily. This is primarily used to understand which collectors customers value so we prioritize correctly and to understand what version of Harvest customers are running in the field.

As for why you see that log message, I suspect your poller is not able to see NetApp's auto-support endpoint, it times out after trying, and we log that message.

**Comment by db-wally007** [comment]
@cgrinds  - thank you. 

Makes sense as our containers do not have access to the internet. I'll disable it
