### ISSUE TITLE
tcp_unencrypted duplicate key detected

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#3340]
Issue noticed in logs @ https://upload.nabox.org/doqi-gybe-rafu

time=2024-11-27T13:03:00.794Z level=WARN source=rest.go:587 msg="This instance is already processed. instKey is not unique" Poller=harvest collector=Rest:SecurityAuditDestination instKey=tcp_unencrypted

**Comment by Hardikl** [comment]
I can able to reproduce this locally, working on it to fix this.
