### ISSUE TITLE
Disk and tape drives throughout should provide information by Host Adapter

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#3373]
Discord [discussion](https://discord.com/channels/855068651522490400/1315777895502970970)

**Comment by Hardikl** [comment]
Verified in main with commit 40f3f855

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/a566e10c-6b8f-472e-962c-736f19e549e7" />

<img width="586" alt="Image" src="https://github.com/user-attachments/assets/eed64125-284b-4060-977a-eade2404188d" />

<img width="1720" alt="Image" src="https://github.com/user-attachments/assets/cb4b4883-ed5f-4fc8-a46d-b048e77994d0" />
