### ISSUE TITLE
SVM dashboard should include protocol drilldowns and panels

### ISSUE THREAD

**Issue by burkl** [NetApp/harvest#344]
In Harvest 1.x one can find dashboards displaying SVM related counters, in particular protocol related performance data. As a start, I've submitted #342 which is adding NFS v3 panels according to the Harvest 1.x dashboard. 

- However, the following rows/panels are missing:
- Highlights(12 panels)
- Top Volumes Performance Drilldown(6 panels)
- Top LIF Drilldown(6 panels)
- CIFS Frontend Drilldown(11 panels)
- ~~NFSv4 Frontend Drilldown(10 panels)~~
- ~~NFSv4_1 Frontend Drilldown(10 panels)~~
- FCP Frontend Drilldown(8 panels)
- iSCSI Frontend Drilldown(8 panels)
- Copy Offload Drilldown(3 panels)
- Top QoS Policy Group Workload Drilldown(7 panels)
- Top QoS Policy Group Latency From Drilldown(7 panels)
- Top Volumes Capacity Drilldown(4 panels)
- Storage Capacity Drilldown(5 panels)

**Comment by cgrinds** [comment]
Thanks @burkl #342 is merged - this is a nice addition 👍

**Comment by cgrinds** [comment]
@rahulguptajss noticed the filtered dropdowns are empty - he's using Grafana `8.0.4`. Leaving this comment here to make sure we track this down

**Comment by rahulguptajss** [comment]
It was due to timeout issue pointed out at #274 . After increasing timeout, dashboard is loading fine. All counters are 0 though which is due to no load on cluster.

**Comment by burkl** [comment]
I'd like to re-open this feature again. There are still plenty of missing panels in comparison to the Harvest 1.x dashboards. I've updated my initial comment to reflect what is still missing. Added a PR #416 yesterday for NFSv4.x panels.

**Comment by cgrinds** [comment]
@burkl sounds good - this issue was closed when #342 was checked in, but we can keep it open and use it to track the missing parts of the svm dashboard

**Comment by vgratian** [comment]
re-opening until we confirm the svm dashboards has everything listed

**Comment by rahulguptajss** [comment]
Assigning to myself for verification

**Comment by rahulguptajss** [comment]
verfied.

**Comment by cgrinds** [comment]
hi @burkl does the 21.08 [harvest_dashboard_svm_details](https://github.com/NetApp/harvest/blob/main/grafana/dashboards/harvest_dashboard_svm_details.json) cover everything in your original request? If so, can this issue be closed?
