### ISSUE TITLE
Missing Antivirus counters in Harvest 2.x

### ISSUE THREAD

**Issue by burkl** [NetApp/harvest#346]
offbox_vscan and offbox_vscan_server counters are not honored in the default pollers. 

That said, these are mandatory for filling the (missing) AntiVirus panels in the "CIFS" row mentioned in #344

**Comment by TeeBeePeeSiSi** [comment]
This issue is hindering my upgrade to Harvest 2.X

**Comment by cgrinds** [comment]
hi @TeeBeePeeSiSi feel free to chime in on #718 - depending on exactly what you need, you may be able to take the templates in that PR and apply them locally to try out. The work remaining is the aggregation across cluster via `offbox_vscan_server`

**Comment by Olofsn** [comment]
How do I enable the collecting of the offbox vscan counters?

**Comment by Olofsn** [comment]
> How do I enable the collection of the offbox vscan counters?

Nevermind, I just removed the comment # in front of the counters in the default.yaml and now it’s working
