### ISSUE TITLE
Storage type metrics is missing

### ISSUE THREAD

**Issue by bengoldenberg** [NetApp/harvest#348]
Hi,
We saw that there is not option to pull metrics about disk type(HHD,SSD).
Can you add a metric that will gather info about the disks and output the size the type and etc.

**Comment by talshechanovitz** [comment]
Hi, I also need that feature.

**Comment by cgrinds** [comment]
type and capacity are gathered [here](https://github.com/NetApp/harvest/blob/2a6732b45c17d13f80929760800c4c0b1b5ec9ae/conf/zapi/cdot/9.8.0/disk.yaml#L11) type is exported, but doesn't look like  `bytes_per_sector` or `sectors` are collected. 

If you add these at line 54, does that give you want you need?
```
    44	  instance_labels:
    45	    - type
    46	    - model
    47	    - outage
    48	    - owner_node
    49	    - shared
    50	    - shelf
    51	    - shelf_bay
    52	    - serial_number
    53	    - failed
    54      - sectors            # <============= add here
    54      - bytes_per_sector

```

**Comment by talshechanovitz** [comment]
Thank you very much for the answer,
This will give me the information about what is the disk type in my
aggregate ? Or generally which type of disks I have in my machine ?

**Comment by cgrinds** [comment]
`disk.yaml` uses `storage-disk-get-iter` which is returns info about disks cluster wide

`aggr.yaml` uses `aggr-get-iter` and return `aggregate-type` which is the type of an aggregate. One of: hdd, hybrid, lun, ssd, vmdisk

@talshechanovitz which are you interested in?

**Comment by talshechanovitz** [comment]
In the end I want to know how many disks I have from each type(ssd,sata)
and for each aggregate they are associated  .

‫בתאריך יום ב׳, 26 ביולי 2021 ב-21:39 מאת ‪Chris Grindstaff‬‏ <‪
***@***.***‬‏>:‬

**Comment by cgrinds** [comment]
thanks for clarifying - we've added a disk dashboard to the backlog

**Comment by talshechanovitz** [comment]
Thank you very much , when do you think this will be done?

**Comment by talshechanovitz** [comment]
For now , there is option to get disk types from another metric that is already collected in harvest?

**Comment by cgrinds** [comment]
hi @talshechanovitz we hope to target that for the `21.08` release (mid Aug 2021)

Yes, disk type is collected via the [disk.yaml](https://github.com/NetApp/harvest/blob/2a6732b45c17d13f80929760800c4c0b1b5ec9ae/conf/zapi/cdot/9.8.0/disk.yaml#L13)

Example with most recent release

```
curl -s localhost:12995/metrics | rg disk | rg type

disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-01",disk="1.2.9",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-01",shared="true",shelf="2",shelf_bay="9",serial_number="F496ZX0J711876",failed="false"} 1.0
disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-02",disk="1.2.16",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-02",shared="true",shelf="2",shelf_bay="16",serial_number="F496ZX0J713072",failed="false"} 1.0
disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-01",disk="1.3.11",type="SSD",model="X371_S1643960ATE",outage="",owner_node="ocum-mobility-01",shared="true",shelf="3",shelf_bay="11",serial_number="F6SENF0K701356",failed="false"} 1.0
disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-02",disk="1.2.14",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-02",shared="true",shelf="2",shelf_bay="14",serial_number="F496ZX0J714820",failed="false"} 1.0
```

**Comment by bengoldenberg** [comment]
> hi @talshechanovitz we hope to target that for the `21.08` release (mid Aug 2021)
> 
> Yes, disk type is collected via the [disk.yaml](https://github.com/NetApp/harvest/blob/2a6732b45c17d13f80929760800c4c0b1b5ec9ae/conf/zapi/cdot/9.8.0/disk.yaml#L13)
> 
> Example with most recent release
> 
> ```
> curl -s localhost:12995/metrics | rg disk | rg type
> 
> disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-01",disk="1.2.9",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-01",shared="true",shelf="2",shelf_bay="9",serial_number="F496ZX0J711876",failed="false"} 1.0
> disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-02",disk="1.2.16",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-02",shared="true",shelf="2",shelf_bay="16",serial_number="F496ZX0J713072",failed="false"} 1.0
> disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-01",disk="1.3.11",type="SSD",model="X371_S1643960ATE",outage="",owner_node="ocum-mobility-01",shared="true",shelf="3",shelf_bay="11",serial_number="F6SENF0K701356",failed="false"} 1.0
> disk_labels{datacenter="nane1",cluster="ocum-mobility-01-02",node="ocum-mobility-02",disk="1.2.14",type="SSD",model="X371_S163A960ATE",outage="",owner_node="ocum-mobility-02",shared="true",shelf="2",shelf_bay="14",serial_number="F496ZX0J714820",failed="false"} 1.0
> ```

This metric will bring me if the disk is HHD or SSD.
I need to get the specific type like sata or sas.
Is it possible somehow?

**Comment by cgrinds** [comment]
hi @talshechanovitz disk dashboard added by this PR https://github.com/NetApp/harvest/pull/360 can you take a look and let us know if this addresses your ask?

**Comment by talshechanovitz** [comment]
The url http://10.249.25.52:3000/ doesn’t work

**Comment by cgrinds** [comment]
that's an internal site used for testing - if you want to use these changes in your local environment you'll need to build Harvest from source or wait for our next release - here's a screenshot 

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/242252/127498196-3e9d29d4-f4f2-401f-b683-c669f2bdf7f9.png">

**Comment by faguayot** [comment]
Hello @cgrinds ,

This dashboard is interesting for me too. In which release will be available? Does it have more info about the disks like status (broken, unassigned,etc), performance to detecting problems, etc.

Thanks.

**Comment by cgrinds** [comment]
hi @faguayot the next planned release is Aug. If you're comfortable building from [source](https://github.com/NetApp/harvest#building-from-source) you can grab it sooner. Status is not there yet. 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/242252/127650194-1da4546f-27db-48a0-8f69-55d75389c30c.png">

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/242252/127650223-70a0c112-37c5-411f-a3fa-9036e0715997.png">

**Comment by talshechanovitz** [comment]
What about the type of the disk? Sata/sas/ssd there is option to add that?🙏

**Comment by Hardikl** [comment]
Now we have added type and status in the disk dashboard. 

![image](https://user-images.githubusercontent.com/83282894/128166154-ba4af821-de1d-484b-b35a-84b2268ef51a.png)

**Comment by cgrinds** [comment]
nice job @Hardikl 

@talshechanovitz take a look at the screenshot above and let us know if this has what you need.

**Comment by bengoldenberg** [comment]
> Now we have added type and status in the disk dashboard.
> 
> ![image](https://user-images.githubusercontent.com/83282894/128166154-ba4af821-de1d-484b-b35a-84b2268ef51a.png)

Looks cool!!
Is there a way to sort by shelf and not by disk,
Because in the end I want to display my aggregate and his shelf’s type.

**Comment by cgrinds** [comment]
@bengoldenberg all columns are sortable

the disk type is queried in [disk.yaml](https://github.com/NetApp/harvest/blob/6bd7acb46804f0b8d7056bd23dfc86aea8c4b14f/conf/zapi/cdot/9.8.0/disk.yaml#L13) via the `storage-disk-get-iter` zapi

**Comment by faguayot** [comment]
> Now we have added type and status in the disk dashboard.
> 
> ![image](https://user-images.githubusercontent.com/83282894/128166154-ba4af821-de1d-484b-b35a-84b2268ef51a.png)

Hello @cgrinds , 

I am running the following version which I built from source:

`**harvest version 21.08.0617- (commit ) (build date 2021-08-06T17:50:56+0200) linux/amd64**
`
But I don't have the Avg IOPS, Avg Latency or the Status in the Disk dashboard. 

Additionally I have a question, do you use the real status which the disk has in the storage array or do you replace for Ok or failed? 

Thanks.

**Comment by faguayot** [comment]
Sorry I forgot to add an screenshoot, there you can appreciate too there is something wrong in the percent of disk utilization.

![image](https://user-images.githubusercontent.com/85484449/128854386-d4c43b06-b423-4536-a729-4e567a530255.png)

On the other hand, the unit for the section: 

> Disk and Take Drives Throughput

 seems very big.

![image](https://user-images.githubusercontent.com/85484449/128854715-e7480f60-84b3-42f1-8a1f-55de29580283.png)

**Comment by Hardikl** [comment]
> > Now we have added type and status in the disk dashboard.
> > ![image](https://user-images.githubusercontent.com/83282894/128166154-ba4af821-de1d-484b-b35a-84b2268ef51a.png)
> 
> Hello @cgrinds ,
> 
> I am running the following version which I built from source:
> 
> `**harvest version 21.08.0617- (commit ) (build date 2021-08-06T17:50:56+0200) linux/amd64** `
> But I don't have the Avg IOPS, Avg Latency or the Status in the Disk dashboard.
> 
> Additionally I have a question, do you use the real status which the disk has in the storage array or do you replace for Ok or failed?
> 
> Thanks.

Hi @faguayot , 
can you please add the detail of grafana version?

for the status question, we use outage field from storage-disk-get-iter zapi. when disk is fine without any issue, outage is empty, which mapped to grafana UI as Ok, And when some issue in disk then outage field would have show the detail like: unknown or not responding or init failed, etc from possible cases which would show as it is in status column in UI.

**Comment by faguayot** [comment]
Hello @Hardikl,

Here the grafana version:

**`Grafana v7.4.3 (010f20c1c8)`**

Regarding the disk status issue, you said for example if a disk is in a maintenance mode, broken, unknown or whatever this will appear in the status coumn.Am I right?

Thanks.
