### ISSUE TITLE
Change variable sort-order in Grafana-dashboards

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#350]
**Describe the solution you'd like**
The current sort order of the dashboards is disabled
![image](https://user-images.githubusercontent.com/33655308/126987670-035d8169-43cc-4257-b53a-e48480453bc5.png)

**Describe alternatives you've considered**
It would be better readable if the sites (and also the other variables) would be ordered alphabetically ascending.
![image](https://user-images.githubusercontent.com/33655308/126987929-22fce8c3-7315-4cb3-b83b-bd68a599a506.png)

Cheers Flo

**Comment by cgrinds** [comment]
hi @florianmulatz thanks for raising this issue and describing the solution - does PR #354 address this?

**Comment by florianmulatz** [comment]
Yep it does! Perfect - thx
