### ISSUE TITLE
Generic or common collector subtemplates

### ISSUE THREAD

**Issue by albinpopote** [NetApp/harvest#395]
**Is your feature request related to a problem? Please describe.**
Currently, the collector subtemplates depend on the versioning of ONTAP. It doesn't seem possible to have a generic or common subtemplate for more than one version of ONTAP: if you want to use the same subtemplate from 2 or 3 different versions of ONTAP, you need to create a subfolder for each version and paste the same subtemplate into each folder (and edit all of them at any change)

**Describe the solution you'd like**
Modify the hierarchy of subtemplate search function to get subtemplate from ONTAP version if exists or a generic/common subtemplate located directly on the ONTAP type (cdot / 7mode) folder or a specific folder (common/generic/...).

**Comment by cgrinds** [comment]
Thanks for the feature request @albinpopote 

You are correct that subtemplates are selected by consulting the ONTAP version, and maybe you already know this, but the selection process uses a closest-matching algorithm that may work for what you trying to achieve.

A few examples from `helpers_test.go`
- ONTAP version: `9.8.1` and template directories `9.8.0, [9.8.1], 9.9.0, 10.10.10`. Harvest will select `9.8.1`
- ONTAP version: `9.7.1` and template directories `[9.8.0], 9.8.1, 9.9.0, 10.10.10`. Harvest will select `9.8.0`
- ONTAP version: `9.9.2` and template directories `9.8.0, 9.8.1, [9.9.0], 10.10.10`. Harvest will select `9.9.0`

The closest-matching algorithm means the same template will be used between multiple versions of ONTAP.

Your suggestion of a `conf/zapi/cdot/common` directory may still be a good idea, but I wanted to make sure the way Harvest works is clear.

I want to make sure I understand your suggestion. Say we're trying to find the `cifs_node.yaml` perf ZAPI. Harvest checks `conf/zapiperf/cdot/9.8.0/cifs_node.yaml` first and let's say the template is not there. Harvest would then try all earlier versioned direcotries, in `conf/zapiperf/cdot/`, returning the first that matches. If the template is not found in any of the versioned directories then one last check would be to try `conf/zapi/cdot/common/cifs_node.yaml`

Is that correct?

**Comment by albinpopote** [comment]
Sorry I didn't understand harvest algorithm in this way. The second example disturbs me because it donesn't work for me with an ONTAP version on 9.5 and a template directory at 9.8.0:

```
2:21PM DBG goharvest2/cmd/collectors/zapi/collector/zapi.go:88 > connected to: XXX (CDOT version 9.5.0) (serial 1-80-12345) (NetApp Release 9.5P11: Tue Feb 25 13:56:38 UTC 2020) Poller=DC-01 collector=ZapiPerf:Node
2:21PM DBG goharvest2/cmd/poller/collector/helpers.go:61 > Looking for best-fitting template in [conf/zapiperf/cdot] Poller=DC-01 collector=ZapiPerf:Node
2:21PM TRC goharvest2/cmd/poller/collector/helpers.go:70 > available version dir: [9.8.0] Poller=DC-01 collector=ZapiPerf:Node
2:21PM TRC goharvest2/cmd/poller/collector/helpers.go:81 > checking for 1 available versions: [9.8.0] Poller=DC-01 collector=ZapiPerf:Node
2:21PM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:99 > Error importing subtemplate: node.yaml error="No best-fitting subtemplate version found" Poller=DC-01 collector=ZapiPerf:Node
2:21PM WRN command-line-arguments/poller.go:532 > init collector-object (ZapiPerf:Node): No best-fitting subtemplate version found Poller=DC-01
2:21PM DBG command-line-arguments/poller.go:547 > initialized (ZapiPerf) with 0 objects Poller=DC-01
2:21PM WRN command-line-arguments/poller.go:257 > no collectors initialized, stopping Poller=DC-01
2:21PM INF command-line-arguments/poller.go:421 > cleaning up and stopping [pid=2532] Poller=DC-01
```

I had not tested with a lower version of template directory... 

The search algorithm is only necessary if you have multiple clusters with multiple versions of ONTAP. In this case, I think you want a common template for all versions of ONTAP to get the same counters on harvest (used by another app or grafana). The only reason to use a specific template is therefore to want to monitor different counters for a single version, or to introduce a counter that is only present from the concerned version.

So we have 3 choices:
- define the common template on a file in the template directory of the lowest version of ONTAP used : my lowest ONTAP version is 9.1.0, I put my template file in 9.1.0 directory and all highest ONTAP versions will use this template
- use the common template last if no other version is defined (your vision of my feature request) : I used a 9.5.0 ontap version : conf/zapiperf/cdot/9.5.0/ --> conf/zapiperf/cdot/* --> conf/zapiperf/cdot/common/ 
- use the common template if no template for the version concerned is found: I used a 9.5.0 ontap version : conf/zapiperf/cdot/9.5.0/ --> conf/zapiperf/cdot/common/ --> conf/zapiperf/cdot/*

I think personaly that the third choice will be more logical but I may not have all the overview of the possibilities of Harvest.
Maybe @ybizeul will help us with his vision to use harvest with multiple cluster versions on Nabox ?

**Comment by ybizeul** [comment]
Hey Albin.

Let's see what @cgrinds says about `No best-fitting subtemplate version found` in your case, in might be a bug. That would solve your specific problem I believe ?

**Comment by cgrinds** [comment]
hi @albinpopote the selection bug you hit was discovered and fixed six days ago in [32fc838d](https://github.com/NetApp/harvest/commit/32fc838d8f05a554c0b2cf00d15cf047e3a23974) - in your earlier issue, you mentioned you're running `v21.05.4` which doesn't have this fix.

Can you try [building from source](https://github.com/NetApp/harvest#building-from-source) and confirming that fixes the selection bug?

**Comment by albinpopote** [comment]
Hi @cgrinds, I just built from the last commit and patch is working fine for me : 
```
8:58PM DBG goharvest2/cmd/collectors/zapi/collector/zapi.go:88 > connected to: XXXX (CDOT version 9.5.0) (serial 1-80-12345) (NetApp Release 9.5P11: Tue Feb 25 13:56:38 UTC 2020) Poller=DC-01 collector=ZapiPerf:Node
8:58PM DBG goharvest2/cmd/poller/collector/helpers.go:61 > Looking for best-fitting template in [conf/zapiperf/cdot] Poller=DC-01 collector=ZapiPerf:Node
8:58PM TRC goharvest2/cmd/poller/collector/helpers.go:71 > available version dir: [9.8.0] Poller=DC-01 collector=ZapiPerf:Node
8:58PM TRC goharvest2/cmd/poller/collector/helpers.go:82 > checking for 1 available versions: [9.8.0] Poller=DC-01 collector=ZapiPerf:Node
8:58PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/node.yaml] for [9.5.0] Poller=DC-01 collector=ZapiPerf:Node
```

If the closest-matching algorithm checks all template directories (lower and higher of the ONTAP HA Pair version), I let you decide if there is any advantage in including the notion of a common template ^^

**Comment by cgrinds** [comment]
glad to here that fix works for you - I'll keep this issue open for a bit to discuss the idea of a fallback `common` folder before closing

**Comment by cgrinds** [comment]
hi @albinpopote after discussing with team, we're going to close this. please re-open if you run into a need for a common folder that isn't covered by the current version matching algorithm
