### ISSUE TITLE
Simplify install by renaming harvest.example.yml to harvest.yml

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#41]
Requires changes in packaging scripts

**Comment by vgratian** [comment]
That was the case in RC1. The problem however is that during upgrade RPM will overwrite `harvest.yaml` because it belongs to the original package filesystem. Copying was a workaround.

**Comment by rahulguptajss** [comment]
@vgratian  We already do have a check in spec file for this. Does this resolve your concern?

https://github.com/NetApp/harvest/blob/main/rpm/spec#L45

**Comment by vgratian** [comment]
yes, thanks!

**Comment by sridevimm** [comment]
Validated this fix with the below build. 
harvest version 21.06.0300-nightly (commit d08ecee) (build date 2021-06-03T00:28:53+0530) linux/amd64

Tested on fresh installation on Debian 10 and RHEL8 systems with .deb, .rpm and tar.gz artifacts. 
Also verified that the upgraded systems retained the harvest.yml.
