### ISSUE TITLE
NAbox compatibility

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#42]
As Alpine Linux doesn't use glibc, harvest 2 doesn't currently work, and prevents integration in NAbox 3

This can be solved either by providing an alpine build in the pipeline (or apk package), or compiling harvest statically.

Sorry @vgratian I totally forgot about that one !

Thoughts ?

**Comment by cgrinds** [comment]
@ybizeul yep, if you need this sooner I didn't have any problem building latest with `golang:1.15-alpine`

alpine was called out in #32

**Comment by vgratian** [comment]
I also had no issue building in an `alpine:3.13` container, but didn't test running the pollers

**Comment by cgrinds** [comment]
If you need something sooner @ybizeul try something like this.
Might want to mount the `conf` instead of copy...

git clone harvest, cd harvest

```
go mod vendor

vim Dockerfile
FROM golang:1.15-alpine AS build
RUN apk add --no-cache git make musl-dev go vim

# Configure Go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

COPY ./cmd/ ${GOPATH}/src/cmd
COPY ./conf/ ${GOPATH}/src/conf
COPY ./pkg/ ${GOPATH}/src/pkg
COPY ./vendor/ ${GOPATH}/src/vendor
COPY Makefile go.mod go.sum ${GOPATH}/src

WORKDIR $GOPATH/src
RUN make

FROM alpine:latest
COPY --from=0 /go/src/bin/ ./bin
COPY --from=0 /go/src/conf/ ./conf

ENTRYPOINT ["./bin/poller"]

```

Run like so:
```
docker run --rm -it -v $(pwd):/yml -p 12991:12991 poller --config /yml/harvest.yml --poller infinity
```
```docker build -t poller .
docker image ls
REPOSITORY                           TAG       IMAGE ID       CREATED         SIZE
poller                               latest    2b5163354f64   7 minutes ago   152MB
```

```
curl -s http://localhost:12991/metrics | wc -l
   20106
```

**Comment by ybizeul** [comment]
Unfortunately I already have a container to run Harvest inside, and it has the REST frontend for NAbox, it seems like too much overhead for production. I think maybe the best option is to have a static build beside the shared build so people can choose. I'll see what I can do

**Comment by darthVikes** [comment]
Will be great to see Nabox 3 move forward.  Seems like it's going to be a new deployment going forward based on the notes?  so if there is a docker image to separate out harvest, poller, rest frontend for nabox? perhaps fixes could be done faster in the future?  aka more microservices in different docker images?

**Comment by ybizeul** [comment]
It's actually how it's implemented in NAbox v3. Harvest is mounted in a container, but it needs a build compatible with alpine linux

**Comment by ruanruijuan** [comment]
From Slack:
Chris Grindstaff:  8:10 AM
hi @yannb with the recent changes to remove go-plugins and Docker alpine build you should be all set - reply in issue #42 if there's something else you need
yannb  10:48 AM
So I can just test with a recent binary release ?
Chris Grindstaff:  10:54 AM
hey Yann - not sure how you're building nabox, but you probably want to grab the changes here if you want Alpine in your vm. The binary release of course works if you want amd64

**Comment by ybizeul** [comment]
Basically I need people to be able to download Harvest from github and install it in NAbox. What release will they be able to use ? From what I see everything is still dynamically linked.

**Comment by ybizeul** [comment]
Hi folks,

Once #357 is solved and a release available, I will be able to release beta5 that should work with Harvest 2

**Comment by ybizeul** [comment]
Last update and closing this bug.

As NAbox doesn't use `harvest` binary, but directly deals with `poller`, #357 is not a match, but a solution has been found to workaround the change in how prometheus ports are configured into `harvest.yml`

Expect NAbox v3b5 anytime soon with Harvest 2 compatibility.
