### ISSUE TITLE
Create distinct set of 7-mode dashboards separate from c-mode

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#441]
There will be a directory of separate 7-mode dashboards, distinct from c-mode dashboards. The expectation is 7-mode dashboards, once extracted from the unified c-mode dashboards, will change much less frequently.

See also:
- #383
- #423

**Comment by Hardikl** [comment]
TODOs: 
- [ ] harvest_dashboard_metadata.json
- [ ] harvest_dashboard_snapmirror.json -> no yaml exist in 7mode
- [ ] harvest_dashboard_svm.json
- [ ] harvest_dashboard_svm_details.json
- [ ] harvest_dashboard_aggregate.json
- [ ] harvest_dashboard_lun.json. -> no yaml exist in 7mode
- [ ] harvest_dashboard_network.json
- [ ] harvest_dashboard_network_detail.json
- [ ] harvest_dashboard_node.json
- [ ] harvest_dashboard_node_details.json
- [ ] harvest_dashboard_volume.json
- [ ] harvest_dashboard_volume_details.json
- [ ] harvest_dashboard_cluster.json
- [ ] harvest_dashboard_nvme_fc.json
- [ ] harvest_dashboard_disk.json
- [ ] harvest_dashboard_shelf.json
