### ISSUE TITLE
aggr metrics returning 0 value

### ISSUE THREAD

**Issue by jperez08** [NetApp/harvest#442]
The following metrics are returning 0 values:

aggr_snapshot_size_used
aggr_space_reserved
aggr_snapshot_reserve_percent

Pollers are up, collectors/object are running and other aggr metrics seem to be working properly. 

- Harvest version: harvest version 21.06.2911-v21.05.0 (commit 08e534b) (build date 2021-06-29T11:13:56-0700) linux/amd64
- Install method: source
- ONTAP Version: 9.7P4

**Comment by Hardikl** [comment]
Hi @jperez08 , 

The above metrics are showing the same value which zapi would return, I have compared the zapi value and Prometheus metric values for all.

![image](https://user-images.githubusercontent.com/83282894/130642547-22cee814-672a-4a14-a12b-16f629649b88.png)

![image](https://user-images.githubusercontent.com/83282894/130643155-0b9e08a4-eec3-4c8b-ac18-6bc77b8d83f4.png)

Could you please share the output of the below commands to fetch zapi response of above all 3 metrics?
./bin/zapi --poller <pollername> show data --api aggr-get-iter | dasel -r xml -w json | grep "snapshot-reserve-percent"

**Comment by cgrinds** [comment]
if you don't have dasel and want to install it, you can find it https://daseldocs.tomwright.me/

@Hardikl is using it to convert the XML returned from the ZAPI into JSON. It's not required but makes it easier to grep out the `snapshot-reserve-percent`

**Comment by jperez08** [comment]
Hello @Hardikl, The zapi and prometheus values seem to be returning the same values for all three metrics. However, when I look at the equivalent metrics/charts (for same poller) for Harvest 1.6 the values are not zero. 

old metrics:
aggr_snapshot_used_bytes
aggr_allocated_bytes
aggr_snapshot_reserve_bytes

![image](https://user-images.githubusercontent.com/56817245/130654020-42a71082-8306-468f-b63a-70e50b929b03.png)

**Comment by jperez08** [comment]
All the pollers have zero values for the 3 metrics while the equivalent harvest 1.6 metrics have non zero values as can be seen below:
![image](https://user-images.githubusercontent.com/56817245/130687914-4e80ed3e-ec97-4e3a-a74d-fcb11af1a78c.png)
![image](https://user-images.githubusercontent.com/56817245/130687948-13f6a002-3028-4695-be0e-308a1fcfd3f8.png)
![image](https://user-images.githubusercontent.com/56817245/130688007-ad43d0d3-9e1d-4e3c-8167-2d6130b3e32f.png)

**Comment by jperez08** [comment]
Found that Harvest 1.6 charts were using different datasource.

**Comment by cgrinds** [comment]
@jperez08 thanks for the follow-up, want to make sure we don't have a gap in Harvest 2.0 with aggregates. Is your Harvest 1.6 chart pulling from a Harvest 1.6 created datasource or a different datasource altogether.
