### ISSUE TITLE
NFS metrics appear to overwrite themselves

### ISSUE THREAD

**Issue by hashi825** [NetApp/harvest#462]
**Describe the bug**
There is a strange behaviour on clusters containing both nfsv3 and nfsv4.1 (or 4 I spose), svm and node related NFS metrics that use `global_labels` nfsv appear to overwrite each other/not appear.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.4-2 (commit 19f8f25) (build date 2021-07-22T15:41:23+0000) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: RHEL 7.9
- Install method: yum
- ONTAP Version: 9.4P8
- Other:

**To Reproduce**
Enable both nfsv3.yaml and nfsv4_1 or nfsv4.yaml in the default template.

**Expected behavior**
Metrics should export metrics relating to any version of nfs

**Actual behavior**
Metrics collected from the Prometheus exporter from a cluster having SVM/Node nfs with differing versions appear to alternate after a while which metric gets exported.
ie:

`node_nfs_access_avg_latency{cluster="cluster1",node="node1",nfsv="v3"} 221`

sometime later, the above goes missing and you get the v4 (or v4.1) related metric

`node_nfs_access_avg_latency{cluster="cluster1",node="node1",nfsv="v4.1"} 111`

**Possible solution, workaround, fix**
Unsure if its do with the Prometheus exporter itself or the code around the use of `global_labels`, disabling one or the other nfs template in the default.yaml fixes the issue for that particular nfs version, this requires disabling both node level and svm level metrics. If only one is disabled, once node nfsv4 metrics get exported, then svm nfsv3 metrics disappear.

**Additional context**
N/A

**Comment by rahulguptajss** [comment]
@hashi825 Yes this is a bug. Templates having same object names are overwriting each others metrics. Fix is on its way and will be targetted for upcoming release.

**Comment by cgrinds** [comment]
Verified on `harvest version 21.08.0-5 (commit 4044fcf) (build date 2021-08-30T08:02:27-0400) linux/amd64`

Monitored a cluster with nfs v3 and v4 shares, after monitoring for 10m, counted the number of  metrics using `curl -s 'http://localhost:12998/metrics' | rg "^node_nfs_" | rg -o "nfsv=\"(\w+)\"" | sort | uniq -c`

Before the fix, the query returns 102 v3 shares, because the v4 shares are overwritten in the matrix.
```
    102 nfsv="v3"
```

After the fix, this correctly returns both.
```
    102 nfsv="v3"
    162 nfsv="v4"
```

**Comment by cgrinds** [comment]
The possible counters effected by this bug are these five
```
grep -R "object:" conf/zapiperf/cdot/ | grep -oE "object:\s+(.*)$" | sort | uniq -c | grep -v "1 object"
      2 object:                   fabricpool
      2 object:                   fcp
      2 object:                   flashpool
      3 object:                   node_nfs
      3 object:                   svm_nfs
```
