### ISSUE TITLE
Counters from zapiperf object_store_client_op.yaml not collected

### ISSUE THREAD

**Issue by jgasher** [NetApp/harvest#473]
**Describe the bug**
Counters from object_store_client_op.yaml are not being collected.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version:  harvest version 21.08.2409-v21.05.4 (commit e8f580d) (build date 2021-08-24T09:46:04-0400) linux/amd64

- Command line arguments used: bin/harvest start
- OS: CENTOS 8
- Install method: native
- ONTAP Version: 9.8+
- Other:

**To Reproduce**
Use Harvest

**Expected behavior**
Tell us what should happen:
This should be collected:
counters:
  - instance_name
  - instance_uuid
  - node_name              => node
  - average_latency
  - get_throughput_bytes
  - put_throughput_bytes
  - stats
  - throughput_ops

**Actual behavior**
Tell us what happens instead:
These aren't collected.

**Possible solution, workaround, fix**
Is it possible these aren't collected because the fabricpool.yaml and object_store_client_op.yaml both output as the fabricpool object?

**Additional context**
I have several systems internal to NetApp labs that can be used to demonstrate the behavior.

**Comment by rahulguptajss** [comment]
@jgasher Is fabricpool.yaml a new template added from your side? I do not see it in default template list. Though having same object name in multiple templates causes issue as described by you. #462 also highlights the same problem. We'll be fixing it in upcoming release.

**Comment by cgrinds** [comment]
Verified on `4044fcf` 

```
curl -s 'http://localhost:12993/metrics' | grep fabricpool | grep -v cloud
fabricpool_throughput_ops{datacenter="4219-ATT",cluster="primary",node="a400-02",fabricpool="0"} 0.6501261846760531
fabricpool_throughput_ops{datacenter="4219-ATT",cluster="primary",node="a400-01",fabricpool="0"} 0.05000970651354255
```
