### ISSUE TITLE
Revisit Docker mount volume

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#511]
Currently we mount /opt/harvest directory in harvest containers. This causes issues where volume needs to be manually updated before a new code can be deployed. We should revisit this is /opt/harvest mount is needed.

Also check harvest.yaml file mount if this is needed. We need to make sure that backward compatibility is supported.

**Comment by cgrinds** [comment]
Verified, commit`c37b608`

Modified `conf` directory and verified compose based pollers see changes and don't require volume updates.
