### ISSUE TITLE
How to collect metrics for ifgrp status and information?

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#520]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
ifgrp status and MLAG'd ports information metrics

**Describe alternatives you've considered**
Custom Monitor

**Additional context**
N/A

**Comment by ruanruijuan** [comment]
The ifgrp related ZAPI is net-port-ifgrp-get for a specific ifgrp. The same attributes are also available in net-port-get-iter (for all ports).

**Comment by jmg011** [comment]
@ruanruijuan: I built and tested the template but it is not working. Can you take a look?

**Template** 

name:                      NetIfgrp
query:                     net-port-ifgrp-get
object:                    net_ifgrp

collect_only_labels: true

counters:
  net-ifgrp-info:
    - ^ifgrp-name
    - ^^node       => node
    - ^mode
    - ^^ports
    - ^up-ports
    - ^mac-address
    - ^down-ports
    - ^distribution-function
    - ^port-participation

plugins:
  LabelAgent:
    value_mapping: status status up `0`

export_options:
  include_all_labels: true


**Error from the log file:**

{"level":"error","Poller":"poller_name","collector":"Zapi:NetIfgrp","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"422","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"292","source":"client.go"},{"func":"(*Zapi).PollData","line":"367","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}],"error":"api request rejected => Missing input: ifgrp-name; Missing input: node; Extra input: max-records","task":"data","caller":"goharvest2/cmd/poller/collector/collector.go:340","time":"2021-11-09T10:57:15-08:00"}

**When I run zapi command to get the data for the api, I get below error:** 

(NetApp Release 9.8P4: Mon May 03 09:22:00 UTC 2021)
2021/11/09 11:03:54 api request rejected => Missing input: ifgrp-name; Missing input: node

**Comment by cgrinds** [comment]
hi @jmg011 `net-port-ifgrp-get` won't work without some code changes since that ZAPI is not a `-get-iter` ZAPI. For the most part, Harvest config ZAPIs only work with the `-get-iter` ZAPIs.

Let's see if we can get what you need from `net-port-get-iter`.

**Comment by jmg011** [comment]
@cgrinds Thank you. I have actually the template for net-port-get-iter. With ifgrp-get, I was trying to get up and down ports for ifgrps. 

name:                      NetPort
query:                     net-port-get-iter
object:                    net_port

counters:
  net-port-info:
    - ^administrative-duplex                   => admin_duplex
    - ^administrative-flowcontrol              => admin_flowcontrol
    - ^administrative-speed                    => admin_speed
    - ^broadcast-domain                        => broadcast
    - ^ifgrp-distribution-function             => ifgrp_func
    - ^ifgrp-mode                              => ifgrp_mode
    - ^ifgrp-node                              => ifgrp_node
    - ^ifgrp-port                              => ifgrp_port
    - ^ignore-health-status                    => ignore_health
    - ^ipspace                                 => ipspace
    - ^is-administrative-auto-negotiate        => admin_auto_negotiate
    - ^is-administrative-up                    => admin_up
    - ^is-operational-auto-negotiate           => op_auto_negotiate
    - ^link-status                             => status
    - mtu                                      => port_mtu
    - ^^node                                   => node
    - ^operational-duplex                      => op_duplex
    - ^operational-flowcontrol                 => op_flowcontrol
    - ^operational-speed                       => op_speed
    - ^^port                                   => port
    - ^port-type                               => port_type
    - ^vlan-id                                 => vlan_id
    - ^vlan-node                               => vlan_node
    - ^vlan-port                               => vlan_port

plugins:
  LabelAgent:
    value_mapping: status status up `0`

export_options:
  include_all_labels: true

**Comment by cgrinds** [comment]
@jmg011 excellent! that means you have what you need. `net-port-get` returns exactly the same info as `net-port-get-iter`. I verified this by diffing the two. 

We just need to figure out which counter, from what you pasted above, has what you want. Is it `link-status`?

**Comment by jmg011** [comment]
yes, it is link-status => status. I summed it with ifgrp, status and port. I can work with this. Thanks for looking into this.  

![image](https://user-images.githubusercontent.com/89614353/141002560-19066e79-7663-48dc-a1d7-10b94b408aa5.png)
