### ISSUE TITLE
How to collect thin vs thick provisioned volume information? 

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#523]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Thin/Thick provisioned volume information.

**Describe alternatives you've considered**
Custom Monitor

**Additional context**
N/A

**Comment by jmg011** [comment]
@ruanruijuan Thank you. Should I enable this in the default template or do you recommend that this should be a custom template for the volume?

**Comment by jmg011** [comment]
@ruanruijuan Hi, I could enable it for c-mode with space attributes, but I could not find the way to collect this data for 7-mode. Can you help get more information on this for 7-mode?

**Comment by ruanruijuan** [comment]
@jmg011 can you please check https://www.netapp.com/pdf.html?item=/media/19678-tr-3965.pdf which I googled?

**Comment by ruanruijuan** [comment]
> 
There is space-reserve attribute in the 7-mode zapi as well and it's under "volume-list-info.volume-info".

**Comment by jmg011** [comment]
Got it working. Thank you @ruanruijuan.
