### ISSUE TITLE
Node status value is different for 7mode vs cmode for node_new_status metrics. For example, when node is down, cmode would show 0 but 7-mode would show 1. How do we make the value same for both platforms?

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#525]
**Is your feature request related to a problem? Please describe.**
yes. It creates confusion when we query the status for the different platforms

**Describe the solution you'd like**
Value (0 or 1) should mean the same thing across different platforms

**Describe alternatives you've considered**
Writing alert rules with different platform label as a filter solves the issue.  But when we run ad-hoc queries, we just need to remember that behavior.

**Additional context**
N/A

**Comment by cdurai-netapp** [comment]
As exepcted node_7mode_status metric has been removed and node_new_status metric shows values as expected for cluster and 7mode system
