### ISSUE TITLE
Poller does not parse the contents of `ping` correctly when it use ping from busybox. 

### ISSUE THREAD

**Issue by charz** [NetApp/harvest#529]
**Describe the bug**
Poller does not parse the contents of `ping` correctly when it use ping from busybox. That causes metric `metadata_target_status` report incorrectly. 
The output of ping doesn't includes `mdev =` and that causes ping() returns false. 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 2.0-nightly (commit ) (build date 2021-07-22T15:42:55+0000) linux/amd64
- Command line arguments used: docker image from https://hub.docker.com/r/rahulguptajss/harvest

**To Reproduce**

```
bash-5.1# ps -ef |grep poller
31257 root      2d18 bin/poller --poller netapp --promPort 12990

bash-5.1# cat harvest.yml |grep netapp -A 2
  netapp:
    datacenter: test
    addr: 192.168.1.133

bash-5.1# wget 127.0.0.1:12990/metrics
bash-5.1# cat metrics |grep metadata_target_status
metadata_target_status{version="2.0",hostname="netapp-metrics-harvest-68f4db67d8-958c7",poller="netapp",addr="192.168.1.133"} 1
```

There is no `mdev` in outupt of ping from busybox. 

```
bash-5.1# ping 192.168.1.133 -w 5 -c 1 -q
PING 192.168.1..133 (192.168.1.133): 56 data bytes

--- 192.168.1.133 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.291/0.291/0.291 ms

bash-5.1# ping --help
BusyBox v1.33.1 () multi-call binary.

Usage: ping [OPTIONS] HOST

Send ICMP ECHO_REQUESTs to HOST

        -4,-6           Force IP or IPv6 name resolution
        -c CNT          Send only CNT pings
        -s SIZE         Send SIZE data bytes in packets (default 56)
        -i SECS         Interval
        -A              Ping as soon as reply is recevied
        -t TTL          Set TTL
        -I IFACE/IP     Source interface or IP address
        -W SEC          Seconds to wait for the first response (default 10)
                        (after all -c CNT packets are sent)
        -w SEC          Seconds until ping exits (default:infinite)
                        (can exit earlier with -c CNT)
        -q              Quiet, only display output at start/finish
        -p HEXBYTE      Payload pattern
bash-5.1# 
```

If you run the ping command from a normal host (not using busybox). You'll abel to see `mdev`.

```
$ ping 192.168.1.133 -w 5 -c 1 -q
PING 192.168.1.133 (192.168.1.133) 56(84) bytes of data.

--- 10.181.193.133 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.155/0.155/0.155/0.000 ms

$ ping -V
ping utility, iputils-s20160308
```

**Expected behavior**

```
bash-5.1# wget 127.0.0.1:12990/metrics
bash-5.1# cat metrics |grep metadata_target_status
metadata_target_status{version="2.0",hostname="netapp-metrics-harvest-68f4db67d8-958c7",poller="netapp",addr="192.168.1.133"} 0
```

**Possible solution, workaround, fix**
The paring of contents needs to improve to prevent this issue. There is no `mdev =` in the output of ping when it is from busybox. 

https://github.com/NetApp/harvest/blob/214f702b11eac30fcfdc351d4173e691643fc2d5/cmd/poller/poller.go#L506-L516

**Comment by cgrinds** [comment]
thanks @charz for the excellent steps to reproduce and details. agreed this needs improvement

**Comment by charz** [comment]
@cgrinds just curious when this patch will be ready in the docker image (https://hub.docker.com/r/rahulguptajss/harvest)?

**Comment by rahulguptajss** [comment]
@charz Our planned next release will be sometime end of next month. In mean time , you can build from main branch with below command. Let me see if we can make nightly docker build from main available through this repo.

```sh
docker build -f docker/onePollerPerContainer/Dockerfile -t harvest:latest . --no-cache
```

**Comment by rahulguptajss** [comment]
verified in release/21.11.0 branch

**Comment by charz** [comment]
@rahulguptajss Thanks!
