### ISSUE TITLE
Please create/migrate dashboards from harvest to harvest2, specifically MCC dashboards

### ISSUE THREAD

**Issue by darthVikes** [NetApp/harvest#539]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like to see the MCC Dashboards added back as a higher priority.

**Describe alternatives you've considered**
Having to use the old harvest environment until all the dashboards that were available prev. are added to the new harvest2 version.

**Additional context**
NA

**Comment by cgrinds** [comment]
MCC dashboard covered by #612 @darthVikes let us know if that covers your ask

**Comment by darthVikes** [comment]
We have MCC IP, so more detail about MCC IP would be good.

**Comment by cdurai-netapp** [comment]
@darthVikes  we would like to have a call and go over your ask.  i have both 1.6 and 2.0 setup are available with MCC-IP cluster is available which will help during our conversation.

**Comment by cgrinds** [comment]
@darthVikes can you elaborate on what's missing? We have both Harvest 1.6 and 2.0 setup in the lab monitoring an MCC-IP cluster so we can compare the dashboards locally if you're seeing a difference

**Comment by cgrinds** [comment]
Covered in 21.11, please reopen if we missed something
