### ISSUE TITLE
Pollers aren't running on fresh Docker install

### ISSUE THREAD

**Issue by survive-wustl** [NetApp/harvest#559]
**Describe the bug**
Pollers aren't running

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: [copy paste output of `harvest --version`]
harvest version 21.08.0-6 (commit 485d191) (build date 2021-08-31T11:51:03-0400) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
started docker per the easy-start page  
- OS: [e.g. RHEL 7.6, Ubuntu 21.04, Docker 19.03.1-CE]
RedHat 8.4
- Install method: [yum, rhel, native, docker]
docker
- ONTAP Version: [e.g. 9.7, 9.8, 9.9, 7mode]
9.7P7
- Other:

**To Reproduce**
Installed\setup to use docker. Started the containers per the docs, I can see them download & start but the pollers never report in. checking them with ./bin/harvest status reports that the pollers are there but not running.

**Expected behavior**
pollers would be running, I would see my datacenters & clusters in Grafana

**Actual behavior**
pollers are not running, only "local" listed in Grafana

**Possible solution, workaround, fix**
Tell us if there is a workaround or fix

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by survive-wustl** [comment]
Here's what I did in a nutshell:

[root@wuit-s-12454 harvest]# ./docker-compose -f prom-stack.yml -f harvest-compose.yml restart
[+] Running 12/12
 ⠿ Container poller_WUIT-A-03B_v21.08.0  Started                                                                                                                                                                                    2.4s
 ⠿ Container poller_WUIT-A-03A_v21.08.0  Started                                                                                                                                                                                    2.0s
 ⠿ Container poller_WUIT-A-08A_v21.08.0  Started                                                                                                                                                                                    1.1s
 ⠿ Container poller_WUIT-A-06B_v21.08.0  Started                                                                                                                                                                                    1.4s
 ⠿ Container poller_WUIT-A-08B_v21.08.0  Started                                                                                                                                                                                    1.2s
 ⠿ Container prometheus                  Started                                                                                                                                                                                    3.3s
 ⠿ Container poller_WUIT-A-11A_v21.08.0  Started                                                                                                                                                                                    2.9s
 ⠿ Container poller_WUIT-A-11B_v21.08.0  Started                                                                                                                                                                                    2.1s
 ⠿ Container poller_unix_v21.08.0        Started                                                                                                                                                                                    3.1s
 ⠿ Container poller_WUIT-A-01A_v21.08.0  Started                                                                                                                                                                                    2.7s
 ⠿ Container poller_WUIT-A-01B_v21.08.0  Started                                                                                                                                                                                    3.3s
 ⠿ Container grafana                     Started                                                                                                                                                                                    3.7s
[root@wuit-s-12454 harvest]# ./bin/harvest status
  Datacenter |   Poller   |  PID  | PromPort |   Status     
-------------+------------+-------+----------+--------------
  GDCE       | WUIT-A-01A |       |          | not running  
  WCDC       | WUIT-A-01B |       |          | not running  
  GDCE       | WUIT-A-03A |       |          | not running  
  WCDC       | WUIT-A-03B |       |          | not running  
  WCDC       | WUIT-A-06B |       |          | not running  
  GDCE       | WUIT-A-08A |       |          | not running  
  WCDC       | WUIT-A-08B |       |          | not running  
  GDCE       | WUIT-A-11A |       |          | not running  
  WCDC       | WUIT-A-11B |       |          | not running  
  local      | unix       | 62324 |    12990 |     running  

I have no idea how to start the pollers.

-Will

**Comment by rahulguptajss** [comment]
@survive-wustl Could you share docker logs for any one of these pollers.

**Comment by survive-wustl** [comment]
If I had any idea how to get at these logs I would.

**Comment by survive-wustl** [comment]
3: connect: connection refused Poller=WUIT-A-11B
12:40PM WRN command-line-arguments/poller.go:615 > aborting collector (ZapiPerf) Poller=WUIT-A-11B
12:40PM WRN command-line-arguments/poller.go:260 > no collectors initialized, stopping Poller=WUIT-A-11B
12:40PM INF command-line-arguments/poller.go:489 > cleaning up and stopping [pid=1] Poller=WUIT-A-11B
12:41PM INF command-line-arguments/poller.go:156 > log level used: info Poller=WUIT-A-11B
12:41PM INF command-line-arguments/poller.go:157 > options config: /opt/harvest.yml Poller=WUIT-A-11B
12:41PM INF command-line-arguments/poller.go:182 > started in foreground [pid=1] Poller=WUIT-A-11B
12:41PM WRN command-line-arguments/poller.go:550 > Unable to load template. Poller=WUIT-A-11B err="open conf/zapi/custom.yaml: no such file or directory"
12:41PM WRN command-line-arguments/poller.go:613 > init collector-object (Zapi:Node): connection error => connection error => Post "https://10.0.0.1:443/servlets/netapp.servlets.admin.XMLrequest_filer": dial tcp 10.0.0.1:443: connect: connection refused Poller=WUIT-A-11B
12:41PM WRN command-line-arguments/poller.go:615 > aborting collector (Zapi) Poller=WUIT-A-11B
12:41PM WRN command-line-arguments/poller.go:550 > Unable to load template. Poller=WUIT-A-11B err="open conf/zapiperf/custom.yaml: no such file or directory"
12:41PM WRN command-line-arguments/poller.go:613 > init collector-object (ZapiPerf:SystemNode): connection error => connection error => Post "https://10.0.0.1:443/servlets/netapp.servlets.admin.XMLrequest_filer": dial tcp 10.0.0.1:443: connect: connection refused Poller=WUIT-A-11B
12:41PM WRN command-line-arguments/poller.go:615 > aborting collector (ZapiPerf) Poller=WUIT-A-11B
12:41PM WRN command-line-arguments/poller.go:260 > no collectors initialized, stopping Poller=WUIT-A-11B
12:41PM INF command-line-arguments/poller.go:489 > cleaning up and stopping [pid=1] Poller=WUIT-A-11B

**Comment by survive-wustl** [comment]
I can ping & ssh to the filer from the host vm.

**Comment by rahulguptajss** [comment]
Let's see current permissions. Can you paste the output of below command from ONTAP

security login role show -role netapp-harvest

**Comment by survive-wustl** [comment]
WUIT-A-01A::> security login role show -role netapp-harvest-role
           Role          Command/                                      Access
Vserver    Name          Directory                               Query Level
---------- ------------- --------- ----------------------------------- --------
WUIT-A-01A netapp-harvest-role 
                         DEFAULT                                       none
                         cluster identity modify                       readonly
                         cluster identity show                         readonly
                         cluster modify                                readonly
                         cluster show                                  readonly
                         lun create                                    readonly
                         lun modify                                    readonly
                         lun show                                      readonly
                         network interface create                      readonly
                         network interface delete                      readonly
                         network interface modify                      readonly
                         network interface show                        readonly
                         qos workload delete                           readonly
                         qos workload modify                           readonly
                         qos workload show                             readonly
                         statistics                                    readonly
                         system node modify                            readonly
                         system node show                              readonly
                         version                                       readonly
19 entries were displayed.

**Comment by survive-wustl** [comment]
can you give me an explicit list of what I need to add to my "netapp-harvest-role" role that I need to add via the 

security login role modify -role netapp-harvest-role -cmddirname

command?

**Comment by survive-wustl** [comment]
Looking better:

4:10PM INF command-line-arguments/poller.go:496 > caught signal [terminated] Poller=WUIT-A-01A
4:10PM INF command-line-arguments/poller.go:489 > cleaning up and stopping [pid=1] Poller=WUIT-A-01A
4:10PM INF command-line-arguments/poller.go:156 > log level used: info Poller=WUIT-A-01A
4:10PM INF command-line-arguments/poller.go:157 > options config: /opt/harvest.yml Poller=WUIT-A-01A
4:10PM INF command-line-arguments/poller.go:182 > started in foreground [pid=1] Poller=WUIT-A-01A
4:10PM WRN command-line-arguments/poller.go:550 > Unable to load template. Poller=WUIT-A-01A err="open conf/zapi/custom.yaml: no such file or directory"
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Node
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/aggr.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Aggregate
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/volume.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Volume
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/snapmirror.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:SnapMirror
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/disk.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Disk
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/shelf.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Shelf
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/status.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Status
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/subsystem.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Subsystem
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapi/cdot/9.8.0/lun.yaml] for [9.7.0] Poller=WUIT-A-01A collector=Zapi:Lun
4:10PM WRN command-line-arguments/poller.go:550 > Unable to load template. Poller=WUIT-A-01A err="open conf/zapiperf/custom.yaml: no such file or directory"
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/system_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:SystemNode
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/hostadapter.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:HostAdapter
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/path.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Path
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/disk.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Disk
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/fcvi.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:FCVI
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/ext_cache_obj.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:ExtCacheObj
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/wafl.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:WAFL
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/wafl_hya_per_aggr.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:WAFLAggr
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/wafl_hya_sizer.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:WAFLSizer
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nic_common.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NicCommon
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.10.1/namespace.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Namespace
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.10.1/nvmf_lif.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NVMfLif
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/fcp.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:FcpPort
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/object_store_client_op.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:ObjectStoreClient
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/volume_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:VolumeNode
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/token_manager.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:TokenManager
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/resource_headroom_cpu.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:HeadroomCPU
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/resource_headroom_aggr.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:HeadroomAggr
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/processor.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Processor
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/cifs_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:CIFSNode
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv3_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv3Node
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv4_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv4Node
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv4_1_node.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv41Node
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/qtree.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Qtree
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/volume.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:Volume
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/lun.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:LUN
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv3.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv3
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv4.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv4
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/nfsv4_1.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:NFSv41
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/cifs_vserver.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:CIFSvserver
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/lif.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:LIF
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/iscsi_lif.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:ISCSI
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/fcp_lif.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:FcpLif
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/copy_manager.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:CopyManager
4:10PM INF goharvest2/cmd/poller/collector/helpers.go:114 > best-fit template [conf/zapiperf/cdot/9.8.0/wafl_comp_aggr_vol_bin.yaml] for [9.7.0] Poller=WUIT-A-01A collector=ZapiPerf:WAFLCompBin
4:10PM INF command-line-arguments/poller.go:318 > Autosupport scheduled. Poller=WUIT-A-01A asupSchedule=24h
4:10PM INF command-line-arguments/poller.go:327 > poller start-up complete Poller=WUIT-A-01A
4:10PM INF command-line-arguments/poller.go:472 > updated status, up collectors: 44 (of 44), up exporters: 1 (of 1) Poller=WUIT-A-01A
4:10PM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="api request rejected => Insufficient privileges: user 'netapp-harvest' does not have read access to this resource" Poller=WUIT-A-01A collector=Zapi:Status stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"422","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"292","source":"client.go"},{"func":"(*Zapi).PollData","line":"358","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}] task=data
4:10PM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="api request rejected => Insufficient privileges: user 'netapp-harvest' does not have read access to this resource" Poller=WUIT-A-01A collector=Zapi:Subsystem stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"422","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"292","source":"client.go"},{"func":"(*Client).InvokeBatchRequest","line":"265","source":"client.go"},{"func":"(*Zapi).PollInstance","line":"243","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}] task=instance
4:10PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:WAFLCompBin object=WAFLCompBin task=instance
4:10PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:WAFLCompBin task=data
4:10PM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="api request rejected => Insufficient privileges: user 'netapp-harvest' does not have read access to this resource" Poller=WUIT-A-01A collector=Zapi:Subsystem stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"422","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"292","source":"client.go"},{"func":"(*Zapi).PollData","line":"358","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}] task=data
4:10PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=Zapi:Lun object=Lun task=instance
4:10PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:ISCSI object=ISCSI task=instance
4:10PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:ISCSI task=data
4:10PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:WAFLSizer object=WAFLSizer task=instance
4:10PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:WAFLSizer task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=Zapi:Lun object=Lun task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:LUN object=LUN task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:LUN task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:Path object=Path task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:Path task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:NVMfLif object=NVMfLif task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:NVMfLif task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:ObjectStoreClient object=ObjectStoreClient task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:ObjectStoreClient task=data
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:Namespace object=Namespace task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:Namespace task=data
4:11PM ERR goharvest2/cmd/collectors/zapiperf/zapiperf.go:1170 > instance request error="api request rejected => Counter collection is disabled" Poller=WUIT-A-01A collector=ZapiPerf:FCVI stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"422","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"292","source":"client.go"},{"func":"(*Client).InvokeBatchRequest","line":"265","source":"client.go"},{"func":"(*ZapiPerf).PollInstance","line":"1169","source":"zapiperf.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]
4:11PM INF goharvest2/cmd/poller/collector/collector.go:329 > no instances of object on system, entering standby mode Poller=WUIT-A-01A collector=ZapiPerf:FCVI object=FCVI task=instance
4:11PM INF goharvest2/cmd/poller/collector/collector.go:355 > recovered from standby mode, back to normal schedule Poller=WUIT-A-01A collector=ZapiPerf:FCVI task=data

still got some api request rejected errors. Is there a definitive list of what apis need access?

-Will

**Comment by rahulguptajss** [comment]
@survive-wustl Could you share permissions for that system where you get subsystem information?

**Comment by survive-wustl** [comment]
It's different that the rest, I don't have a "netapp-harvest-role" defined on the box where the subsystem information is working. I would assume it just has default readonly access to the whole api. If you can tell me how to map roles to a user I'll report back.

Is there a definitive list of what API's are needed for harvest to collect all the required info?

**Comment by survive-wustl** [comment]
I certainly could, but that seems to defeat the whole purpose of defining the role & all that.

Surely you can tell me what permissions this thing actually needs & not just dump a "default all" rule on it & call it good?

**Comment by cgrinds** [comment]
Closed by #564
