### ISSUE TITLE
Dashboard Harvest 2.0 - cDOT/NetApp Detail: Network - Details is broken

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#562]
**Describe the bug**
DS_PROMETHEUS not found in dashboard Harvest 2.0 - cDOT/NetApp Detail: Network - Details

**Environment**
Checked in docker but must be same for other environments

- Harvest version: [copy paste output of `harvest --version`]
I could see it in latest main and also 21.08 version

**To Reproduce**
Run docker deployment

**Expected behavior**
Dashboard should load

**Actual behavior**
![image](https://user-images.githubusercontent.com/25551691/137091591-b03d243d-3f3b-4349-a79f-cee3e45fabd2.png)

**Possible solution, workaround, fix**
Tell us if there is a workaround or fix

**Additional context**
Add any other context about the problem here. Share logs, error output, etc

**Comment by cgrinds** [comment]
Verified dashboards have Prometheus variable defined
Commit `f7be2f8`

- Harvest 21.11 - cDOT / NetApp Detail: Network - Details
- Harvest 21.11 - 7-mode / NetApp Detail: Disk 7 mode
- Harvest 21.11 - cDOT / NetApp Detail: Disk
- Harvest 21.11 - cDOT / NetApp Detail: Network with NVMe/FC
- Harvest 21.11 - cDOT / NetApp Detail: Network - Details
- Harvest 21.11 - 7-mode / NetApp Detail: Network with NVMe/FC 7 mode
