### ISSUE TITLE
docker generate command enhancement

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#584]
Below command should support configurable prometheus, grafana port. Currently they are hardcoded in prom-stack.yml.
```sh
bin/harvest generate docker full --port --output harvest-compose.yml
```

**Comment by rahulguptajss** [comment]
pending doc changes

**Comment by cgrinds** [comment]
Verified `release/22.02.0` bae2dc8 that `bin/harvest generate docker full --port --output harvest-compose2.yml --grafanaPort 3333 --promPort 191919` creates a `prom-stack.yml` with those exposed ports
