### ISSUE TITLE
Harvest restart changes instance causing some 7mode graphs to show extra entries.

### ISSUE THREAD

**Issue by cordelster** [NetApp/harvest#590]
**Describe the bug**
Affects 7-mode Dashboards only.
When harvest is restarted the ports for the pollers may change causing a differing instance.
The 7-mode queries as set, in aggregate, volume, and Network dashboards, will show multiple entries for the same object and create separate graph colors for the time span covered when a restart is within that time frame.
Minor annoyance. 

**Environment**
CentOS7, Harvest latest nightly build, Grafana 8.2.1-1

- Harvest version: harvest version 21.10.2000-nightly (commit 7334f11) (build date 2021-10-20T00:22:28-0400) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: CentOS 7
- Install method: yum rpm
- ONTAP Version: [7mode]
- Other:

**To Reproduce**
Open any of the following Dashboards: 
Aggregate 7 mode
Network 7 mode
volume 7 mode

Restart Harvest:
systemctl restart harvest

**Expected behavior**
Appearance in graphs shouldn't change with duplicate or more items. 

**Actual behavior**
Items in graphs add extra entries for each restart within viewed time period.

**Possible solution, workaround, fix**
Add sum by(node,[appropreate_label])
Pull request on its way.

**Additional context**
Feel free to contact me directly by PM for direct access to my lab.
Legal Docs signed

**Comment by cgrinds** [comment]
Verified on `f7be2f8`

Setup six pollers to use port_range. Ran this script

```fish
for i in (seq 1 10);bin/harvest restart;sleep 30s;end
```

Each time Harvest was restarted, verified that all six pollers are assigned their respective port numbers. Validated there were no color changes in Disk dashboard.

![image](https://user-images.githubusercontent.com/242252/139725972-32b393d0-c4d1-42f8-9b12-1a4b78b7585e.png)
