### ISSUE TITLE
Error in logs while importing zapi template

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#592]
When harvest zapi collector starts, it throws below error. We should check for any functional issue and fix this error.

```
7:01PM ERR goharvest2/cmd/collectors/zapi/collector/zapi.go:108 > Error importing subtemplate: status_7.yaml error="No best-fit template found" Poller=umeng_aff300 collector=Zapi:Status_7mode

**Comment by cgrinds** [comment]
Verified these are logged as structured warnings `Unable to import template`
Commit `f7be2f8`
