### ISSUE TITLE
Is there a way to get 7-mode flexscale status details?

### ISSUE THREAD

**Issue by jmg011** [NetApp/harvest#623]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Want to get some information on how to get some details about flexscale on 7-mode.

I understand that it would be part of node level metrics. But when I look at the node level apis, I do not see this field. 

system node run -node node_name|local} options flexscale.enable

**Describe alternatives you've considered**
No alternatives considered yet. 

**Additional context**
When I query data with system-get-info api, I do not see an attribute for this field.

**Comment by jmg011** [comment]
Hi @cgrinds, Just checking if you were able to get more information on this.

**Comment by cgrinds** [comment]
hi @jmg011 I've asked a few people, as has @ruanruijuan, and nothing yet. I'm trying to get access to a 7-mode cluster to run `system node run -node node_name|local} options flexscale.enable` and then check if anything flexscale related comes back in the `ext_cache_obj` zapi.

By chance, have you checked the `ext_cache_obj` zapi?
```
bin/zapi -p <poller-name> show counters --object ext_cache_obj
```

**Comment by jmg011** [comment]
@cgrinds Found it as part of options-list-info. I could make it work. The only problem is I have to exclude lot of options. Is there a way to include specific ones instead of excluding many? just like exclude_contains, include_contains does not work. 

plugins:
  LabelAgent:
    value_mapping: version status up 0
    **exclude_contains:**
      - option_name `nfs`

**Comment by rahulguptajss** [comment]
@jmg011 we are building include plugin as part of https://github.com/NetApp/harvest/issues/730

**Comment by jmg011** [comment]
@rahulguptajss Thank you!
