### ISSUE TITLE
Grafana dashboards should match release version

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#631]
These files need to match the release. Update build process to modify or generate based on release.
- `cmd/tools/grafana/grafana.go:32`
- `grafana/dashboards/dashboard.yml` 
- `grafana/dashboards/dashboard7.yml`

**Comment by rahulguptajss** [comment]
is this done with folder specific dashboards?

**Comment by rahulguptajss** [comment]
- [ ] Support dashboard versioning with cli. Handled in #818 
- [ ] Support dashboard versioningin docker-compose workflow
