### ISSUE TITLE
Grafana 7-mode shelf module status is inverted.

### ISSUE THREAD

**Issue by cordelster** [NetApp/harvest#635]
**Describe the bug**
7-mode Grafana  shelf dashboard shows shelves modules down when they are UP.

**Environment**
7-mode systems, All OS, 
Version 8.2.1 (commit: 88622d7f09, branch: HEAD)
rometheus, version 2.24.1 

- Harvest version: harvest version 21.10.3100-nightly (commit f7be2f8)
- Command line arguments used: systemd
- OS: CentOS Linux release 7.9.2009 (Core)
- Install method: yum
- ONTAP Version: 7Mode
- Other:

**To Reproduce**
Configure a 7mode system and view the 7Mode shelf dashboard.

**Expected behavior**
Online modules should show online - offline modules should show offline.

**Actual behavior**
Shelf module status is inverted, online modules show offline status, offline modules show online.

**Possible solution, workaround, fix**
Pull request created.

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

![Screenshot 2021-11-02 at 11-41-39 NetApp Detail Shelf 7 mode - Grafana](https://user-images.githubusercontent.com/4791031/139925793-63c89ec0-0a03-460f-b6c5-e67e6d938bb7.png)

**Comment by cgrinds** [comment]
`bin/harvest start ntap-is-awesome -f -l1 --collectors Zapi --objects Shelf`

Showed:
- the plugin is correctly defined and read
- the filer is returning a status that is not `normal`

```
7:24PM DBG goharvest2/cmd/poller/plugin/label_agent/parse_rules.go:464 > (value_to_num) parsed rule [{new_status state 0 true map[normal:1 ok:1]}] Poller=ntap-is-awesome plugin=Zapi:LabelAgent

7:24PM DBG goharvest2/cmd/collectors/zapi/collector/zapi.go:330 >  > label (shelf-environ-channel-info.shelf-environ-shelf-list.shelf-environ-shelf-info.shelf-status) [state] set value (non-critical) Poller=ntap-is-awesome collector=Zapi:Shelf
```

Harvest only maps green / online to a status of `normal`. In this case, the filer is returning `non-critical` which causes `new_status` to be set to `0`.

Possible enum values for shelf-status are:
```
 *	@element	shelf-status
 *	@type		string
 *	@desc		Current shelf status. Possible values: "unrecoverable",
 *			"critical", "non_critical", "informational", "normal".
```

Please reopen @cordelster if I've missed anything or you see another problem with these and thanks for reporting and helping chase this down.
