### ISSUE TITLE
No data on several panels

### ISSUE THREAD

**Issue by MrObvious** [NetApp/harvest#639]
**Describe the bug**
No data on multiple panels

**Environment**
NAbox 3.0_beta7 (2021-10-02) - Alpine Linux 3.14.2
Grafana8.1.5
Graphite1.2.0
NetApp Harvest21.08.0-6
NetApp NMSDK 9.8P2

**To Reproduce**
Go to SVM details dashboard and get no data such as under Highlights

**Expected behavior**
Tell us what should happen

**Actual behavior**
Tell us what happens instead

**Possible solution, workaround, fix**
No

**Additional context**
Internal system, if you want I can give access as it is on corporate network.

-Paul Stejskal

**Comment by rahulguptajss** [comment]
@MrObvious Yes send us an email with system details and we'll check.

**Comment by MrObvious** [comment]
Rahul,

What e-mail is best? ng-harvest-maintainers?

Feel free to hit me up on Teams as well.

**Comment by cgrinds** [comment]
@MrObvious's Grafana was setup with a default `Graphite` datasource
![image](https://user-images.githubusercontent.com/242252/140173079-2bcee1a6-17ea-45c5-bcc5-410598116f97.png)

and the SVM details dashboard panels do not define a datasource
```
"datasource": null,
```
which means the default (Graphite) will be used. I changed all these to
```
"datasource": "${DS_PROMETHEUS}",
```
and boom, beautiful SVM stats.
![image](https://user-images.githubusercontent.com/242252/140173519-1fab1c3e-d86e-485f-a538-e2eccfc42d25.png)

**Comment by cgrinds** [comment]
Fixed by #640
