### ISSUE TITLE
Minor edits to "improved systemd integration"

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#643]
**Is your feature request related to a problem? Please describe.**
Monitoring poller instance health via systemd units. The provided solution can be improved further.

**Describe the solution you'd like**
- The description of the improved systemd integration should be linked into the README (https://github.com/NetApp/harvest/tree/main/service/contrib)
- Poller service Unit file should be modified
  1. improve description
  2. change path to default
  2. add user/group to avoid unix poller /proc issue and improve security
  3. add "WantedBy" to correctly stop when harvest.target is stopped
 Suggestion:
```
[Unit]
Description="Netapp Harvest Poller instance %I"
PartOf=harvest.target

[Service]
User=harvest
Group=harvest
Type=simple
Restart=on-failure
WorkingDirectory=/opt/harvest
ExecStart=/opt/harvest/bin/harvest --config /opt/harvest/harvest.yml start -f %i

[Install]
WantedBy=harvest.target
```
-~~`harvest generate systemd` output should be modified to allow piping directly to unit file~~
- harvest.target unit file should use `Requires` instead of `Wants`. That way the target will fail if any poller fails to start.
- harvest.target unit file should reference unix poller as last unit to avoid instance discovery error messages. (`skip instance [ontap], process: process not found`)
Suggestion
```
[Unit]
Description="NetApp Harvest Meta Service"
Wants=poller@ontap1.service poller@ontap2.service poller@ontap3.service poller@ontap4.service poller@ontap5.service poller@ontap6.service poller@ontap7.service poller@ontap8.service poller@ontap9.service poller@unix.service

[Install]
WantedBy=multi-user.target' | sudo tee /etc/systemd/system/harvest.target
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cgrinds** [comment]
Verified on `release/22.02.0` 727e0b5 :
- documentation was updated
- description was improved
- default path printed to console is standard service location
- harvest user and group are included in service file
- service file includes `WantedBy` clause. Pollers are stopped when harvest.target is stopped
- unix poller is added last in the service list
