### ISSUE TITLE
Include systemd start/stop routine for admin service

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#654]
**Is your feature request related to a problem? Please describe.**
The admin service for HTTP service discovery is not started automatically by the included systemd unit and also not documented for the instantiated configuration.

**Describe the solution you'd like**
Include auto startup and instance documentation

**Comment by cgrinds** [comment]
Closed by #644

**Comment by cgrinds** [comment]
Verified on `release/22.02.0` 3d038fe

Used harvest generate to create admin node service.
start, stop, status all work as expected
