### ISSUE TITLE
Dashboard issues"NetApp Detail: Network - Details"

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#673]
**Describe the bug**
- all Variables have sorting disabled
- Ethernet Receive & Ethernet Send have Value Mappings defined that makes the timeseries show "UP" when there is 0 traffic
- Port Utilization uses wrong unit, Percent 0-100 instead 0-1
- Top Resources variable is not used
- Ethernet drilldown panels do not use Eth variable
- FC panels do not use the FCP variable
- Speed is shown in Gbyte instead of Gbit

**Environment**
Dashboard imported from Github Master branch

**Comment by mamoep** [comment]
Please consider getting the Dashboard "NetApp Detail: Network" &  "NetApp Detail: Network - Details" more diversed. Currently they show mostly the same.

**Comment by mamoep** [comment]
"Ethernet Drilldown" Panel "Port Utilization %" still uses Percent 0-100 instead 0-1

**Comment by cgrinds** [comment]
Verified on `release/22.02.0` 3d038fe
