### ISSUE TITLE
Volume dashboard does not display volume names 

### ISSUE THREAD

**Issue by JerryCurl** [NetApp/harvest#69]
Kicking the tires on 2.0.  The Netpp Detail: Volume dashboard does not display volume names on any of the charts, except the "volumes in cluster" table.  All other charts on the dashboard display data but no volume labels

<img width="1524" alt="Screen Shot 2021-05-26 at 11 17 02 AM" src="https://user-images.githubusercontent.com/13382445/119695609-f93b4800-be13-11eb-97d8-7435bc6d671f.png">
.

**Comment by cgrinds** [comment]
Thanks for reporting. It's a nnown issue, fixed in https://github.com/NetApp/harvest/issues/40.
We'll push this out in a point release in another week or two.
If you need it sooner, pull the latest and rebuild
