### ISSUE TITLE
7 mode shelf plugin issue

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#692]
7 mode, shelf plugin instance key generation logic needs to take into account of channel-name. Multiple channel names can have same shelf ids. Currently it fails with below exception.

7:18AM DBG goharvest2/cmd/collectors/zapi/plugins/shelf/shelf.go:204 > add (temp-sensor-list) instance: duplicate instance key => 5.1 Poller=fla1-arc-ash2-cloudsys plugin=Zapi:Shelf

Thaks @pilot7777 for reporting it over slack.

**Comment by cgrinds** [comment]
Verified on `release/22.02.0` 727e0b5

- no errors from shelf.go plugin
- 7mode dashboards includes channel in panel expressions
- cdot dashboards include shelf in panel expressions
