### ISSUE TITLE
Improve custom ZAPI template instructions

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#72]
See [wiki](https://github.com/NetApp/harvest/wiki/FAQ#ontap-counters-are-missing)
- [ ] Add examples to [subtemplates](https://github.com/NetApp/harvest/blob/main/cmd/collectors/zapiperf/README.md#creatingediting-subtemplates)

**Comment by vgratian** [comment]
This is related to #124

**Comment by rajeshl8** [comment]
![image](https://user-images.githubusercontent.com/5583674/121733950-20f00880-cac2-11eb-8eef-468a84a866f3.png)

**Comment by rajeshl8** [comment]
verified build version:
[root@scspa2398581002 harvest]# ./bin/harvest -v
harvest version 21.06.1121-nightly (commit 1524ebb) (build date 2021-06-11T21:11:15+0530) linux/amd64
[root@scspa2398581002 harvest]#

**Comment by cgrinds** [comment]
_Copy screenshot to text to make it easier to copy/paste_

validated the document steps and everything worked as expected.
Steps covered:
1. Deploy Harvest and add pollers
2. Now comment all the objects except node object in the conf/zapi/default. yam! file
3. Restart pollers and observe the metrics are generated only for node object
curl - http://localhost:12991/metrics
4. Now copy the default. yaml to custom.yaml file and uncomment all objects in the custom. yam! file
except node object
cp conf/zapi/default.yaml conf/zapi/custom.yaml
5. restart pollers
6. Observe the poller will now collect metrics for all objects
Note the collector will merge config data from both default and custom. yam| files.
