### ISSUE TITLE
Docs: Reorganize container docs

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#722]
- [ ] Consolidate Docker sections
- [ ] Make upgrade clearer
- [ ] Mention Podman
- [ ] K8
- [ ] [Rancher Desktop](https://github.com/NetApp/harvest/blob/main/docker/containerd/README.md) and [Lima](https://github.com/lima-vm/lima)

**Comment by cgrinds** [comment]
From Slack

> darthVIkes was asking earlier also about if the *.tar should also be downloaded first, and sounded like it should be?

> via Riaul " better to have new tar in case harvest-compose.yaml generation has some new stuff. Though we try to maintain backward compatibility"

> darthVIkes so not sure if that also should be added to the readme?

**Comment by darthVikes** [comment]
Thanks for creating the ticket,  was noticing the main README.MD dosn't link to the main docker README.MD ?
