### ISSUE TITLE
Cert directory needs to be included in container volume mounts

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#725]
Commit `4b98d26`

# Steps to reproduce
1. Enabled HTTP SD in `harvest.yml` and enable TLS support.
2. Generate compose `bin/harvest generate docker full --output harvest-compose.yml --image rahulguptajss/harvest:nightly`
3. Start containers `docker-compose -f prom-stack.yml -f harvest-compose.yml up -d --remove-orphans`

Poller fails to start
```
3:02PM INF ./poller.go:178 > log level used: info Poller=simple1
3:02PM INF ./poller.go:179 > options config: /opt/harvest.yml Poller=simple1
3:02PM FTL goharvest2/pkg/util/util.go:230 > TLS is enabled but cert path is invalid. Poller=simple1 config=/opt/harvest.yml ssl_cert=admin-cert.pem
```

**Comment by cgrinds** [comment]
This will also effect client certificate auth

**Comment by rahulguptajss** [comment]
commitid doesn't seem correct. rest zapi diff PR doesn't touch this code.

**Comment by rahulguptajss** [comment]
Let's discuss it today. We may need to change admin to generate cert in a folder rather than in root.

**Comment by cgrinds** [comment]
We should mount the `cert` directory. That's needed for client certificate auth. After that we can update the documentation or generate in the cert directory.

**Comment by rahulguptajss** [comment]
- [ ] change admin cli to generate cert in ```cert``` folder
