### ISSUE TITLE
Review default set of counters gathered

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#73]
With an eye towards adding any that are missing and removing redundant or rarely used ones

**Comment by schmots1** [comment]
I would caution against removing collections for data currently gathered.  Someone might be using it and its a huge headache when someone has been using X and suddenly its gone.

**Comment by ruanruijuan** [comment]
> I would caution against removing collections for data currently gathered. Someone might be using it and its a huge headache when someone has been using X and suddenly its gone.

Agreed, David.

**Comment by cgrinds** [comment]
Done
