### ISSUE TITLE
Insufficient privileges: user 'fsxadmin' does not have read access to this resource

### ISSUE THREAD

**Issue by baronichj** [NetApp/harvest#744]
**Describe the bug**
Insufficient privileges: user 'fsxadmin' does not have read access to this resource"

**Environment**
I deployed resource on AWS following:
- FSX cluster: Quick create
- Harvest: https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/monitoring-harvest-grafana.html

- Harvest version: harvest version 21.11.0-1 (commit 66c5ce1) (build date 2021-11-08T13:34:34+0000) linux/amd64
- Command line arguments used:`bin/harvest start --config /etc/harvest/harvest.yml -p cluster-1 --promPort 25001`
- OS: Docker version 20.10.7, build f0df350
- Install method: docker

**To Reproduce**
Fresh install

**Expected behavior**
Harvest should collect data

**Actual behavior**
Data not showing

**Possible solution, workaround, fix**
N/A

**Additional context**
`4:46AM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="api request rejected => Insufficient privileges: user 'fsxadmin' does not have read access to this resource" Poller=cluster-1 collector=Zapi:Disk stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Client).invoke","line":"428","source":"client.go"},{"func":"(*Client).InvokeBatchWithTimers","line":"298","source":"client.go"},{"func":"(*Zapi).PollData","line":"373","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}] task=data
4:46AM ERR goharvest2/cmd/poller/collector/collector.go:368 > plugin [Qtree]:  error="no instances => no quota instances found" Poller=cluster-1 collector=Zapi:Qtree stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*Quota).Run","line":"150","source":"quota.go"},{"func":"(*AbstractCollector).Start","line":"367","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}]
4:46AM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="configuration error => missing timestamp metric" Poller=cluster-1 collector=ZapiPerf:Disk stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*ZapiPerf).PollData","line":"174","source":"zapiperf.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}] task=data
4:46AM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="configuration error => missing timestamp metric" Poller=cluster-1 collector=ZapiPerf:CIFSvserver stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*ZapiPerf).PollData","line":"174","source":"zapiperf.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}] task=data
4:46AM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="configuration error => missing timestamp metric" Poller=cluster-1 collector=ZapiPerf:CIFSNode stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*ZapiPerf).PollData","line":"174","source":"zapiperf.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"293","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}] task=data
4:46AM ERR goharvest2/cmd/poller/collector/collector.go:340 >  error="configuration error => missing timestamp metric" Poller=cluster-1 collector=ZapiPerf:CopyManager stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*ZapiPerf).PollData","line":"174","source":"zapi`

**Comment by rahulguptajss** [comment]
@baronichj You will need to give relevant object permissions for fsxadmin user. More information @ https://github.com/NetApp/harvest/blob/f2b545cfa68922d5b5c3c54d2372cdeb5a95cfe9/docs/AuthAndPermissions.md#ontap-cli

**Comment by baronichj** [comment]
Thank you for you help @rahulguptajss 

But unfortunately its seem no way to execute command to grant permissions for fsxadmin user.
There are 2 user created when deploy fsx cluster on using AWS console "fsxadmin", "vsadmin"
- User "fsxadmin", "vsadmin" cannot perform most NetApp ONTAP CLI cluster commands. 
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-resources-ontap-apps.html

**Comment by cgrinds** [comment]
hi @baronichj thanks for the report. As you noted, there are several underlying objects that are not exposed. Harvest won't be able to collect those objects until they're visible.

**Comment by cgrinds** [comment]
Closing for now. Harvest only collects what's available. We'll update the documentation to make this clear for FSx
