### ISSUE TITLE
Shelf metrics appear to only collect metrics for one shelf

### ISSUE THREAD

**Issue by hashi825** [NetApp/harvest#75]
**Describe the bug**
Shelf metrics appear to only be collected for one shelf 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: `harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64`
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: RHEL 7.9
- Install method: yum
- ONTAP Version: 9.7
- Other:

**To Reproduce**
N/A

**Expected behavior**
metrics such as `shelf_temperature_reading` `shelf_psu_power_drawn` should report metrics for each shelf id.

**Actual behavior**
One time series is returned per cluster for what appears to be a shelf id at random.

**Possible solution, workaround, fix**
N/A

**Additional context**
Appears to be related to the Shelf plugin used at `/conf/zapi/cdot/9.8.0/shelf.yaml`, `shelf_labels` appears to correctly collect data for each shelf.

**Comment by cgrinds** [comment]
Thanks for the issue - I've confirmed this is a bug

**Comment by sridevimm** [comment]
Validated this fix in below build.
harvest version 21.06.0801-nightly (commit 5dd80cc) (build date 2021-06-08T01:08:56+0530) linux/amd64

shelf_temperature_labels{datacenter="fas8060-39-239-241",cluster="fas8060-39-239-241",shelf="1.2",sensor_id="7",high_critical="60",high_warning="55",temp_is_ambient="false",low_critical="5",low_warning="10"} 1.0
shelf_temperature_reading{datacenter="fas8060-39-239-241",cluster="fas8060-39-239-241",shelf="1.2",sensor_id="7"} 29
shelf_temperature_labels{datacenter="fas8060-39-239-241",cluster="fas8060-39-239-241",shelf="1.1",sensor_id="3",high_critical="55",high_warning="50",temp_is_ambient="false",low_critical="5",low_warning="10"} 1.0
shelf_temperature_reading{datacenter="fas8060-39-239-241",cluster="fas8060-39-239-241",shelf="1.1",sensor_id="3"} 28

shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.3",psu_id="3",enabled="false",location="-",part_number="-",serial="-",type="-"} 1.0
shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.4",psu_id="4",enabled="true",location="rear of the shelf at the bottom right",part_number="114-00087+C0",serial="PSD057141108360",type="9E"} 1.0
shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.2",psu_id="1",enabled="true",location="rear of the shelf at the bottom left",part_number="114-00065+A2",serial="XXT142311202",type="9C"} 1.0
shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.1",psu_id="1",enabled="true",location="rear of the shelf at the bottom left",part_number="114-00065+A2",serial="XXT142098878",type="9C"} 1.0
shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.3",psu_id="1",enabled="true",location="rear of the shelf at the top left",part_number="0082562-21",serial="PMW825620154EAF",type="9C"} 1.0
shelf_psu_labels{cluster="fas8060-39-239-241",datacenter="fas8060-39-239-241",shelf="1.3",psu_id="2",enabled="false",location="-",part_number="-",serial="-",type="-"} 1.0
