### ISSUE TITLE
NFSv3 Latency and Ops returning Negative numbers

### ISSUE THREAD

**Issue by rodenj1** [NetApp/harvest#762]
**Describe the bug**
I have been researching some negative number results being returned by Harvest.  For me this is happening when polling "nfsv3" performance stats.  It is happing for all most all the stats under "nfsv3", but I decided to focus on "rename_avg_latency".  Based on the documentation it seem this metric would be calculated by "x = (xi - xi-1) / (yi - yi-1)" formula.

I ran the collector with --objects=NFSv3 --trace and dug through the logs to see the values returned.

```
 Timestamp	 read_avg_latency	 read_total (base metric)	 
  2021-12-20T10:29:33-08:00	 2926258448149980	 355221042059	 
  2021-12-20T10:31:33-08:00	 2926259006592690	 355222583248	 
  2021-12-20T10:33:33-08:00	 2824022066864320	 333261794519	 
  2021-12-20T10:35:33-08:00	 2926261954769390	 355225048243	 
  2021-12-20T10:37:33-08:00	 2926264078486220	 355228639931	 
  2021-12-20T10:39:33-08:00	 2926265051561770	 355230169668	 
```

This resulted in the following values being recorded in Prometheus...
819
772
-102238130902524
4655
591

Now clearly there is some oddness with the filer returning 2926259006592690 the returning 2824022066864320 then going back up to 2926261954769390.  But overall if you apply the formula, you shouldnt get a negative value.  Please let me know what else you need to research this further.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.11.1-1 (commit 41d7780) (build date 2021-12-10T11:01:52-0500) linux/amd64
- Command line arguments used: bin/harvest start --objects NFSv3 --trace
- OS: rhel7-9
- Install method: yum
- ONTAP Version: 9.6P7
- Other:

**To Reproduce**
Running NFSv3 collections and getting erroneous drop-in counter values

**Expected behavior**
Should Not return a negative value

**Actual behavior**
Return no value or previous value

**Possible solution, workaround, fix**
Looking into ways to capture this in Prometheus rules to force a NaN value

**Comment by rahulguptajss** [comment]
@Hardikl could you check this.

**Comment by rodenj1** [comment]
Yes, I am still getting the negative values.  Here is what it looks like in Prometheus.  In Grafana, I filter out all negative values, so you at least have something usable.  But that just means I am getting gaps in data reporting.  I am currently running Harvest 22.05.0
![negative latency numbers](https://user-images.githubusercontent.com/8315258/183780197-42dbfbc1-e529-4661-8ba8-0d58543cde16.png)

**Comment by rodenj1** [comment]
It was happening on multiple clusters, but now it is only happening on one.  it will take me a day or so to get the diag output.

**Comment by rodenj1** [comment]
Here is what Prometheus looked like during a 20 min period.
![image](https://user-images.githubusercontent.com/8315258/184010711-9c9fdae3-6029-42b0-942d-af180844c1da.png)

Here is the Diag from that same timeframe.

```
    Complete    Number of
  latency Aggregation Constituents
 -------- ----------- ------------
      0us      Yes      20
      0us      Yes      20
  30620us      Yes      20
      0us      Yes      20
    583us      Yes      20
   1249us      Yes      20
    417us      Yes      20
  13632us      Yes      20
  30619us      Yes      20
    261us      Yes      20
    254us      Yes      20
      0us      Yes      20
  15381us      Yes      20
      0us      Yes      20
  30619us      Yes      20
      0us      Yes      20
  30619us      Yes      20
      0us      Yes      20
    479us      Yes      20
    968us      Yes      20

    Complete    Number of
  latency Aggregation Constituents
 -------- ----------- ------------
Minimums:
      0us       -       -
Averages for 20 samples:
   7785us       -       -
Maximums:
  30620us       -       -
```
