### ISSUE TITLE
caught signal [terminated]

### ISSUE THREAD

**Issue by eselvam** [NetApp/harvest#784]
**Describe the bug**
the systemd service for harvest latest release failing to start poller. when we start using command line harvest start it is working fine.

**Environment**
Production

- Harvest version: harvest version 21.11.1-1 (commit 41d7780) (build date 2021-12-10T11:01:52-0500) linux/amd64
bin/harvest start
Rhel 8
Yum

**To Reproduce**
systemctl start harvest

**Expected behavior**
poller should be running

**Actual behavior**
caught signal [terminated]

**Possible solution, workaround, fix**
start it manually

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by cgrinds** [comment]
hi @eselvam few questions:

1. Can you paste the contents of your Harvest service file that's failing? 
2. Did you generate the systemd service file via `bin/harvest generate systemd`
3. Can you paste the relevant journal entries for the failing service `journalctl -u <name-of-service>`
4. Any more details in `systemctl status <name-of-service>`

**Comment by eselvam** [comment]
1.
[Unit]
Description=Harvest
Wants=network-online.target
After=network-online.target

[Service]
User=harvest
Group=harvest
WorkingDirectory=/opt/harvest
ExecStart=/opt/harvest/bin/harvest  \
    restart \
    --config /opt/harvest/harvest.yml
ExecStop=/opt/harvest/bin/harvest \
    stop \
    --config /opt/harvest/harvest.yml
IgnoreSIGPIPE=no
KillMode=process
Restart=on-failure
RestartSec=30
TimeoutSec=60min
Type=forking

[Install]
WantedBy=multi-user.target
2.  as it is rpm based, the systemd file automatically installed  under systemd
3. version is:harvest version 21.11.1-1 (commit 41d7780) (build date 2021-12-10T11:01:52-0500) linux/amd64
4. ● harvest.service - Harvest
   Loaded: loaded (/etc/systemd/system/harvest.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2022-01-19 12:03:22 UTC; 2min 15s ago
  Process: 869830 ExecStop=/opt/harvest/bin/harvest stop --config /opt/harvest/harvest.yml (code=exited, status=0/SUCCESS)
  Process: 869820 ExecStart=/opt/harvest/bin/harvest restart --config /opt/harvest/harvest.yml (code=exited, status=0/SUCCESS)
 Main PID: 869827 (code=exited, status=0/SUCCESS)

Jan 19 12:03:22 example.com systemd[1]: Starting Harvest...
Jan 19 12:03:22 example.com systemd[1]: Started Harvest.
Jan 19 12:03:22 example.com harvest[869830]: os: process already finished
Jan 19 12:03:22 example.com harvest[869830]:   Datacenter | Poller | PID | PromPort |   Status
Jan 19 12:03:22 example.com harvest[869830]: -------------+--------+-----+----------+--------------
Jan 19 12:03:22 example.com harvest[869830]:   local      | unix   |     |          | not running
Jan 19 12:03:22 example.com systemd[1]: harvest.service: Succeeded.
5. it is same as above in journactl
6. poller log:
{"level":"info","Poller":"unix","caller":"./poller.go:178","time":"2022-01-19T12:03:22Z","message":"log level used: info"}
{"level":"info","Poller":"unix","caller":"./poller.go:179","time":"2022-01-19T12:03:22Z","message":"options config: /opt/harvest/harvest.yml"}
{"level":"info","Poller":"unix","caller":"./poller.go:214","time":"2022-01-19T12:03:22Z","message":"started as daemon [pid=869829]"}
{"level":"info","Poller":"unix","caller":"./poller.go:520","time":"2022-01-19T12:03:22Z","message":"caught signal [terminated]"}
{"level":"info","Poller":"unix","caller":"./poller.go:513","time":"2022-01-19T12:03:22Z","message":"cleaning up and stopping [pid=869829]"}

**Comment by cgrinds** [comment]
thanks @eselvam if I understood correctly, Harvest runs fine when started manually. It's only went started via systemctl that you hit this issue, correct?

I grabbed the same version of Harvest you are using and yum installed on a RHEL instance. Do you have SELinux enabled?

```
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)

sestatus
SELinux status:                 disabled
```

The `/etc/systemd/system/harvest.service` file is created and started correctly so it doesn't seem to be a general problem with Harvest or RHEL.

## Permissions
We've seen this before when Harvest was first run as root and then later a non-root user. Running as root can sometimes create a permission problem. Can you double check via `ls -la` that the following are owned by the `harvest` user?

```
ls -la /var/log/
drwxr-xr-x   2 harvest harvest         55 Jan 19 11:24 harvest/
```

```
ls -la /var/log/harvest/
total 16
drwxr-xr-x   2 harvest harvest   55 Jan 19 11:24 ./
drwxr-xr-x. 15 root    root    4096 Jan 16 03:07 ../
-rw-r--r--   1 harvest harvest 1622 Nov 25 08:23 poller_u2-cert.log
-rw-r--r--   1 harvest harvest  897 Jan 19 11:24 poller_unix.log
```

```
ls -la /opt/harvest
total 128
drwxr-xr-x  16 harvest harvest  4096 Jan 19 11:24 ./
drwxr-xr-x.  8 root    root      115 Jan 19 11:24 ../
drwxr-xr-x   2 harvest harvest     6 Dec 10 11:02 asup/
drwxr-xr-x   2 harvest harvest    57 Jan 19 11:24 autosupport/
drwsr-sr-x   2 harvest harvest    91 Jan 19 11:24 bin/
drwxr-xr-x   8 harvest harvest    96 Jan 19 11:24 cmd/
drwxr-xr-x   7 harvest harvest    89 Jan 19 11:24 conf/
drwxr-xr-x   4 harvest harvest    70 Jan 19 11:24 docker/
drwxr-xr-x   3 harvest harvest   164 Jan 19 11:24 docs/
drwxr-xr-x   8 harvest harvest   163 Jan 19 11:24 .git/
drwxr-xr-x   4 harvest harvest    81 Jan 19 11:24 .github/
-rw-r--r--   1 harvest harvest  1693 Dec 10 11:01 go.mod
-rw-r--r--   1 harvest harvest 64302 Dec 10 11:01 go.sum
drwxr-xr-x   4 harvest harvest    43 Jan 19 11:24 grafana/
-rw-r--r--   1 harvest harvest  1071 Dec 10 11:01 harvest.cue
-rw-r--r--   1 harvest harvest  1822 Jan 19 11:24 harvest.example.yml
-rw-r--r--   1 harvest harvest  1822 Dec 10 11:01 harvest.yml
-rw-r--r--   1 harvest harvest 11558 Dec 10 11:01 LICENSE
-rw-r--r--   1 harvest harvest  5827 Dec 10 11:01 Makefile
drwxr-xr-x  16 harvest harvest   187 Jan 19 11:24 pkg/
-rw-r--r--   1 harvest harvest  1292 Dec 10 11:01 prom-stack.yml
-rw-r--r--   1 harvest harvest 16555 Dec 10 11:01 README.md
drwxr-xr-x   3 harvest harvest    52 Jan 19 11:24 rpm/
drwxr-xr-x   3 harvest harvest    44 Jan 19 11:24 service/
drwxr-xr-x   5 harvest harvest    77 Jan 19 11:24 vendor/
```

**Comment by eselvam** [comment]
Thanks for quick information.  Yes. Selinux enabled. is it mandatory to disable it? please clarify.
The permissions are looks good.  Thanks.

**Comment by eselvam** [comment]
We disabled the selinux however still same issue:

{"level":"info","Poller":"unix","caller":"./poller.go:178","time":"2022-01-20T05:10:22Z","message":"log level used: info"}
{"level":"info","Poller":"unix","caller":"./poller.go:179","time":"2022-01-20T05:10:22Z","message":"options config: /opt/harvest/harvest.yml"}
{"level":"info","Poller":"unix","caller":"./poller.go:214","time":"2022-01-20T05:10:22Z","message":"started as daemon [pid=1761]"}
{"level":"info","Poller":"unix","poller":"unix","caller":"./poller.go:344","time":"2022-01-20T05:10:22Z","message":"Autosupport disabled since poller not connected to ONTAP."}
{"level":"info","Poller":"unix","caller":"./poller.go:349","time":"2022-01-20T05:10:22Z","message":"poller start-up complete"}
{"level":"info","Poller":"unix","caller":"./poller.go:496","time":"2022-01-20T05:10:22Z","message":"updated status, up collectors: 1 (of 1), up exporters: 1 (of 1)"}
{"level":"info","Poller":"unix","caller":"./poller.go:520","time":"2022-01-20T10:50:46Z","message":"caught signal [terminated]"}
{"level":"info","Poller":"unix","caller":"./poller.go:513","time":"2022-01-20T10:50:46Z","message":"cleaning up and stopping [pid=1761]"}
{"level":"info","Poller":"unix","caller":"./poller.go:178","time":"2022-01-20T10:50:59Z","message":"log level used: info"}
{"level":"info","Poller":"unix","caller":"./poller.go:179","time":"2022-01-20T10:50:59Z","message":"options config: /opt/harvest/harvest.yml"}
{"level":"info","Poller":"unix","caller":"./poller.go:214","time":"2022-01-20T10:50:59Z","message":"started as daemon [pid=5541]"}
{"level":"info","Poller":"unix","poller":"unix","caller":"./poller.go:344","time":"2022-01-20T10:50:59Z","message":"Autosupport disabled since poller not connected to ONTAP."}
{"level":"info","Poller":"unix","caller":"./poller.go:349","time":"2022-01-20T10:50:59Z","message":"poller start-up complete"}
{"level":"info","Poller":"unix","caller":"./poller.go:520","time":"2022-01-20T10:50:59Z","message":"caught signal [terminated]"}
{"level":"info","Poller":"unix","caller":"./poller.go:513","time":"2022-01-20T10:50:59Z","message":"cleaning up and stopping [pid=5541]"}

**Comment by eselvam** [comment]
Shall you check the /var/log/harvest/pooler.log to see if you are getting same message as above? is it expected behavior? 

can you please share the below from working server:
1. cat  /etc/systemd/system/harvest.service
2. cat /var/log/harvest/poller.log after systemctl start harvest
3. systemctl status harvest.service
4. ps -ef |grep -i poller
Thanks.

**Comment by cgrinds** [comment]
hi @eselvam no errors on the RHEL8 machine I used yesterday, everything works as expected.

Looks like something on your system is killing the poller process. 
Do you see any messages in journalctl about some other process killing the poller?


```
ps aux | grep poller
root         108  0.0  0.0      0     0 ?        I<    2021   0:00 [edac-poller]
root     1484824  0.0  0.0  12136  1156 pts/0    S+   08:13   0:00 grep --color=auto poller

ll /var/log/harvest/
total 0
```

Start Harvest
```
root@rhel8-ads-13 ~ [3]# systemctl start harvest
root@rhel8-ads-13 ~# ps aux | grep poller
root         108  0.0  0.0      0     0 ?        I<    2021   0:00 [edac-poller]
harvest  1493604  0.0  0.0 1384384 16824 ?       Sl   08:15   0:00 bin/poller --poller unix --loglevel 2 --promPort 12990 --config /opt/harvest/harvest.yml --daemon
root     1494042  0.0  0.0  12136  1196 pts/0    S+   08:15   0:00 grep --color=auto poller
root@rhel8-ads-13 ~# systemctl status harvest
● harvest.service - Harvest
   Loaded: loaded (/etc/systemd/system/harvest.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-01-20 08:15:11 EST; 8s ago
  Process: 1483916 ExecStop=/opt/harvest/bin/harvest stop --config /opt/harvest/harvest.yml (code=exited, status=0/SUCCESS)
  Process: 1493569 ExecStart=/opt/harvest/bin/harvest restart --config /opt/harvest/harvest.yml (code=exited, status=0/SUCCESS)
 Main PID: 1493604 (poller)
    Tasks: 10 (limit: 230117)
   Memory: 8.6M
   CGroup: /system.slice/harvest.service
           └─1493604 bin/poller --poller unix --loglevel 2 --promPort 12990 --config /opt/harvest/harvest.yml --daemon

Jan 20 08:15:11 rhel8-ads-13 systemd[1]: Starting Harvest...
Jan 20 08:15:11 rhel8-ads-13 systemd[1]: Started Harvest.
root@rhel8-ads-13 ~# ll /var/log/harvest/
total 4.0K
-rw-r--r-- 1 harvest harvest 899 Jan 20 08:15 poller_unix.log
root@rhel8-ads-13 ~# cat /var/log/harvest/poller_unix.log
{"level":"info","Poller":"unix","caller":"./poller.go:178","time":"2022-01-20T08:15:11-05:00","message":"log level used: info"}
{"level":"info","Poller":"unix","caller":"./poller.go:179","time":"2022-01-20T08:15:11-05:00","message":"options config: /opt/harvest/harvest.yml"}
{"level":"info","Poller":"unix","caller":"./poller.go:214","time":"2022-01-20T08:15:11-05:00","message":"started as daemon [pid=1493604]"}
{"level":"info","Poller":"unix","poller":"unix","caller":"./poller.go:344","time":"2022-01-20T08:15:11-05:00","message":"Autosupport disabled since poller not connected to ONTAP."}
{"level":"info","Poller":"unix","caller":"./poller.go:349","time":"2022-01-20T08:15:11-05:00","message":"poller start-up complete"}
{"level":"info","Poller":"unix","caller":"./poller.go:496","time":"2022-01-20T08:15:11-05:00","message":"updated status, up collectors: 1 (of 1), up exporters: 1 (of 1)"}

root@rhel8-ads-13 ~ [23|0]# curl -s http://localhost:12990/metrics | head -10
metadata_collector_poll_time{hostname="rhel8-ads-13",version="21.11.1",poller="unix",collector="Unix",object="poller",task="instance",interval="20.0000"} 13742
metadata_collector_task_time{hostname="rhel8-ads-13",version="21.11.1",poller="unix",collector="Unix",object="poller",task="instance",interval="20.0000"} 13741
metadata_collector_task_time{hostname="rhel8-ads-13",version="21.11.1",poller="unix",collector="Unix",object="poller",task="data",interval="10.0000"} 1924
metadata_collector_plugin_time{hostname="rhel8-ads-13",version="21.11.1",poller="unix",collector="Unix",object="poller",task="data",interval="10.0000"} 0
metadata_collector_poll_time{hostname="rhel8-ads-13",version="21.11.1",poller="unix",collector="Unix",object="poller",task="data",interval="10.0000"} 1930
poller_io{datacenter="local",hostname="rhel8-ads-13",poller="unix",pid="1493604",metric="read_bytes"} 0
poller_io{datacenter="local",hostname="rhel8-ads-13",poller="unix",pid="1493604",metric="write_bytes"} 4096
poller_net{datacenter="local",hostname="rhel8-ads-13",poller="unix",pid="1493604",metric="sent_packets"} 3898579815
poller_ctx{datacenter="local",hostname="rhel8-ads-13",poller="unix",pid="1493604",metric="involuntary"} 2
poller_cpu{datacenter="local",hostname="rhel8-ads-13",poller="unix",pid="1493604",metric="system"} 0.01
```

harvest.service is the one installed by rpm

```
cat /etc/systemd/system/harvest.service
[Unit]
Description=Harvest
Wants=network-online.target
After=network-online.target

[Service]
User=harvest
Group=harvest
WorkingDirectory=/opt/harvest
ExecStart=/opt/harvest/bin/harvest \
    restart \
    --config /opt/harvest/harvest.yml
ExecStop=/opt/harvest/bin/harvest \
    stop \
    --config /opt/harvest/harvest.yml
IgnoreSIGPIPE=no
KillMode=process
Restart=on-failure
RestartSec=30
TimeoutSec=60min
Type=forking

[Install]
WantedBy=multi-user.target⏎
```

**Comment by eselvam** [comment]
Closed.
