### ISSUE TITLE
FabricPool engine performance dashboard

### ISSUE THREAD

**Issue by matthieu-sudo** [NetApp/harvest#788]
**Is your feature request related to a problem? Please describe.**
Customer and ISP should have a better look inside FabricPool engine metrics

**Describe the solution you'd like**
Harvest could come with a dashboard about:
- S3 put/get performance (objects/sec, MB/sec bandwidth)
- latency from bucket
- breakout to show % of get size from 4 to 256 KB.
- unreferenced blocks rate for a given volume
- reclamation performance

all metrics you could have with storage object profiler from Ontap.

**Describe alternatives you've considered**

**Additional context**

**Comment by cgrinds** [comment]
Including the cli command matthieu-sudo sent earlier, apparently this is a `diag` only command

```
storage aggregate object-store profiler show
```

**Comment by cgrinds** [comment]
REST private cli may be an option
```
curl -k -uharvestnew "https://10.193.48.11/api/private/cli/storage/aggregate/object-store/profiler"
```

**Comment by cgrinds** [comment]
Discussed with @shubhammer and he confirmed that Harvest 1.6 included Fabric Pool panels

**Comment by cgrinds** [comment]
Harvest 1.6

![image](https://user-images.githubusercontent.com/242252/186667926-ede0a8f5-d22a-4cf7-bba3-abcfd2b86607.png)
