### ISSUE TITLE
Support file logging for instantiated units

### ISSUE THREAD

**Issue by mamoep** [NetApp/harvest#810]
**Is your feature request related to a problem? Please describe.**
Currently the use of instantiated units makes harvest poller run in "foreground" mode and log everything to standard out. Due to extensive logging my /var/log/messages grows heavily.

**Describe the solution you'd like**
Please make use of Harvests standard file logging feature with automatic rotation for instantiated units.

**Describe alternatives you've considered**
Difficult reconfiguration of rsyslog would be necessary.

**Comment by cgrinds** [comment]
hi @mamoep, the expectation with Systemd instantiated units was they would only run on OSes were logging was handled by `journalctl`. The systemd team recommendation is to log to stdout and let `journalctl` handle it. `/var/log/messages` shouldn't be used in that case and only `journalctl`. Sounds like that's not the case for you?

- What OS and version are you using? 
- If you remove `-f` from the instantiated unit does that solve your logging issue?

**Comment by mamoep** [comment]
Hi @cgrinds ,

I am using RHEL7. I don't know if this is specific to our company configuration, but basically all systemd journal-entries are replicated to /var/log/messages. This could be changed via rsyslog configuration to be re-routed to a different log. But I am unsure if I can reach the per-poller granularity with this approach. Also I would need additional logrotate configuration. All this to get the functionality that is already available in Harvest.

If I remove the `-f` then Harvest spawns a background process. Systemd doesn't like that without `Type=forking` and doesn't start the unit. Also we would be back to square one with this behavior because `Type=forking` doesn't recognize when the forked process fails. This would make the instantiated units pointless.

I thought it couldn't be to hard to get the non-forking foreground behavior while writing to the poller log instead of standard out.

**Comment by mamoep** [comment]
PR looks good. I can test a nightly build when it is merged.

**Comment by mamoep** [comment]
I tested the nightly now but see the following error:
```
#/opt/harvest/bin/harvest --config /opt/harvest/harvest.yml  start -f clustername --logtofile
zerolog: could not write event: can't rename log file: rename /var/log/harvest /var/log/harvest-2022-02-02T08-33-22.477: permission denied
```

**Comment by cgrinds** [comment]
Good catch. I think you're right. 

Since the instantiated service runs as user `harvest`, group `harvest`. Can you also double check that the permissions for `/var/log/harvest` allow the harvest user to create and write files there?

`ls -la /var/log` and `ls -la /var/log/harvest` should tell you.

Pushed a fix for the poller name and will kick-off a nightly

**Comment by mamoep** [comment]
Starting with default parameters works fine and writes to the log files. So it's not a permission issue per se.

**Comment by cgrinds** [comment]
Thanks for confirming

**Comment by mamoep** [comment]
Test with latest nightly is successful. Thank you, keep up the good work!
