### ISSUE TITLE
qtree/quota report dashboard

### ISSUE THREAD

**Issue by ev1963** [NetApp/harvest#812]
I am looking for a dashboard for reporting qtree/quota reports for cdot volumes

**Comment by KlausHub** [comment]
is there **an easy way** to disable qtree/Quota harvestor, as after updating to 22.08 on the 1st of our Harvest Servers the utilization (especially on Diskspace and Querys) went up very high.
![Harvest_Metadata_Average_time_per_Exporter](https://user-images.githubusercontent.com/97510878/189348445-455b6c2e-f3b6-4152-a85c-de2b5d74c7a6.PNG)

**Comment by cgrinds** [comment]
hi @KlausHub there are two options.
1. You can completely disable the `Qtree` collector
2. You can tell the `Qtree` collector to collect less data - in `22.08` we started collecting `user` and `group` quota information, in addition to `tree` info we've always gathered. 

Some customers have many quota `user`s and that may be causing the higher utilization you mentioned above.

If you want to disable `qtree` altogether, remove or comment out these two lines
- https://github.com/NetApp/harvest/blob/main/conf/zapi/default.yaml#L18
- https://github.com/NetApp/harvest/blob/main/conf/zapiperf/default.yaml#L29

If you'd rather keep the `qtree` collector, but not collect anything but `tree`s, edit your `conf/zapi/cdot/9.8.0/qtree.yaml` file and comment out or remove the `-user` and `-group` lines.

**Comment by KlausHub** [comment]
Chris Grindstaff ***@***.***> schrieb am Fr. 9. Sep. 2022 um
16:39:
