### ISSUE TITLE
Make the shared-tooltip option default for dashboards

### ISSUE THREAD

**Issue by florianmulatz** [NetApp/harvest#842]
**Describe the solution you'd like**
From my point of perspective it would be good to activate the shared-tooltip option for all dashboard since this is really handy in cases of troubleshooting
![image](https://user-images.githubusercontent.com/33655308/153213830-fe1f3cb9-e180-4407-a1b9-4cad0eea9280.png)

It was enabled for old harvest_1 dashboards per default from my knowledge

**Comment by cgrinds** [comment]
hi @florianmulatz that setting can make it difficult to see info, for example when I enable `Shared Tooltip`, many of my panels are obscured.

![image](https://user-images.githubusercontent.com/242252/153239468-030f72c9-0e82-4f13-86d3-eccd4eb613d7.png)

We could address that by reducing the density of panels but that's a more sweeping change. You may already know this, but what I typically do is use the keyboard shortcut `Ctrl-o` (Windows/Linux) `Cmd-o` (Mac) to cycle between the three tooltip options.

**Comment by cgrinds** [comment]
Looks like 1.6 dashboards shipped with `Shared crosshair` for most of the dashboards, which does address the obscuring problem a bit better. Would that be a better option for your scenario?

```
rg -I graphTooltip | tr -d ' ' | sort | uniq -c
   4 "graphTooltip":0,
  20 "graphTooltip":1,
```

**Comment by florianmulatz** [comment]
Hi, I aggree with your contraints about this. I didn't know the shortcut to be honest - that's really handy!
Thx for that - I'll close this request!
BR Florian
