### ISSUE TITLE
wrong metrics and values in mcc dashboard

### ISSUE THREAD

**Issue by chris4789** [NetApp/harvest#846]
**Describe the bug**
i get wrong metrics ans Values displayed in mcc dashboard

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: 21.11.1-1
- Hardware: AFF A800 / NVME / MCC-IP (internal disks)
- ONTAP Version: 9.9.1P6

**Expected behavior**
- user Reads per Disk per Plex
µs are displayed instead of iops
- Disk and Tape Adapter Drilldown
µs/s are displayed instead of MB/s
- User Read Latency per 4KB IO per Plex
values are in seconds range, via cli I get µs values!?

![2022-02-11 09_12_53-Grafana_MCC_Latency](https://user-images.githubusercontent.com/99468302/153564593-19ab9b04-6f90-4072-8807-2c589abd9550.png)

**Comment by cgrinds** [comment]
thanks @chris4789 this was fixed in #685 and will be included in the next Harvest release. You can grab a [nightly](https://github.com/NetApp/harvest/releases/tag/nightly) if you want to try it out sooner

**Comment by Hardikl** [comment]
Next Harvest release would show the graphs like this:

<img width="1990" alt="image" src="https://user-images.githubusercontent.com/83282894/153617816-aadaaee8-3ac1-41b7-bab2-0a78e053aba4.png">

**Comment by rahulguptajss** [comment]
> Hi, thanks for the quick adjustment, I have imported the last nightly on my system, but still get the wrong (old) data displayed. I have restarted the system several times but unfortunately without success... am I possibly doing something wrong?
> 
> greetings Chris

@chris4789 Could you confirm if you have imported dashboards from nightly? Also if you check your import json for mcc is similiar to https://github.com/NetApp/harvest/blob/main/grafana/dashboards/cmode/harvest_dashboard_mcc_cluster.json

**Comment by chris4789** [comment]
Yes, i can confirm that i have impoted the dashboards fom the nightly output.. see screenshots. how can i check the import over the grafana gui? when i compare the files manually /opt/harvest2-conf/grafana/dashboards/cmode/harvest_dashboard_mcc_cluster.json i think it is the right file
![2022-02-14 16_54_54-Nabox](https://user-images.githubusercontent.com/99468302/153906862-93764645-caa6-4685-95ad-fe86b1cf2ab8.png)
![2022-02-11 09_12_53-Grafana_MCC_Latency](https://user-images.githubusercontent.com/99468302/153907103-7afeaf59-3f49-447b-a151-97a1c6c29fc1.png)
.

**Comment by cgrinds** [comment]
hi @chris4789 thanks for the screenshot! Looks like you're using nabox, that's not written by the Harvest dev team. Let's see if @ybizeul can chime in on whether he's tested this upgrade workflow. I know he was making some changes here recently

**Comment by chris4789** [comment]
i deleted the existing harvest_dashboard_mcc_cluster.json file and imported it manually from the last nightly.. now it looks much better :-) .. Thank you for the support! greetings chris

![2022-02-11 09_12_53-Grafana_MCC_Latency_fixed](https://user-images.githubusercontent.com/99468302/154015730-88f01c2a-91b0-484c-b71b-3a2c2aa1c539.png)

**Comment by ybizeul** [comment]
Interesting. I'll take a look at dashboard imports in the current version of NAbox.

**Comment by cgrinds** [comment]
glad it's working for you @chris4789 and thanks for taking a look @ybizeul
