### ISSUE TITLE
Poller with influxdb exporter are reported not running and stop/start or restart with systemd do not kill processes

### ISSUE THREAD

**Issue by figeac888** [NetApp/harvest#853]
**Describe the bug**
Poller with influxdb exporter are reported not running and stop/start or restart with systemd do not kill processes

**Environment**

- Harvest version: harvest-21.11.1-1.x86_64.rpm
- Command line arguments used: 
ps -ef |grep harvest
harvest     9744       1  0 17:49 ?        00:00:00 bin/poller --poller unix --loglevel 2 --config /opt/harvest/harvest.yml --daemon
harvest     9749       1 13 17:49 ?        00:00:01 bin/poller --poller cluster-vdr --loglevel 2 --config /opt/harvest/harvest.yml --daemon
- OS: RHEL 8.4
- Install method: DNF
- ONTAP Version: 9.5

**To Reproduce**
[root@xxx harvest]# systemctl restart harvest
[root@xxx harvest]# ps -ef |grep harvest
harvest     8518       1  0 15:40 ?        00:00:04 bin/poller --poller unix --loglevel 2 --config /opt/harvest/harvest.yml --daemon
harvest     8520       1  1 15:40 ?        00:01:30 bin/poller --poller cluster-vdr --loglevel 2 --config /opt/harvest/harvest.yml --daemon
harvest     9744       1  0 17:49 ?        00:00:00 bin/poller --poller unix --loglevel 2 --config /opt/harvest/harvest.yml --daemon
harvest     9749       1 34 17:49 ?        00:00:01 bin/poller --poller cluster-vdr --loglevel 2 --config /opt/harvest/harvest.yml --daemon

Systemd logs :

Feb 14 17:49:59 XXXXXX systemd[1]: harvest.service: Found left-over process 8518 (poller) in control group while starting unit. Ignoring.
Feb 14 17:49:59 XXXXXX systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 17:49:59 XXXXXX systemd[1]: harvest.service: Found left-over process 8520 (poller) in control group while starting unit. Ignoring.
Feb 14 17:49:59 XXXXXX systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 17:49:59 XXXXXX systemd[1]: Starting Harvest...
Feb 14 17:49:59 XXXXXX harvest[9733]:   Datacenter  |   Poller    | PID | PromPort |   Status
Feb 14 17:49:59 XXXXXX harvest[9733]: --------------+-------------+-----+----------+--------------
Feb 14 17:49:59 XXXXXX harvest[9733]:   local       | unix        |     |          | not running
Feb 14 17:49:59 XXXXXX harvest[9733]:   opme1nasnd1 | cluster-vdr |     |          | not running
Feb 14 17:49:59 XXXXXX systemd[1]: Started Harvest.

ps -ef |grep harvest
harvest     9744       1  0 17:49 ?        00:00:00 bin/poller --poller unix --loglevel 2 --config /opt/harvest/harvest.yml --daemon
harvest     9749       1  1 17:49 ?        00:00:04 bin/poller --poller cluster-vdr --loglevel 2 --config /opt/harvest/harvest.yml --daemon

On dashboard NetApp Harvest: Pollers, there is no data and it appear down whereas data are correctly collecting for unix & netapp cluster.

**Expected behavior**
Processes should be correctly cleaned and poller should appear running

**Actual behavior**
Poller with influxdb exporter are reported not running and stop/start or restart with systemd do not kill processes

**Comment by figeac888** [comment]
> hi @figeac888 thanks for reporting, the "not running" problem was fixed recently in #837
> 
> We'll take a look at the systemd warnings - it looks like it correctly restarted the processes, but the "not running" problem makes it appear as if they aren't running.

Thanks for your feedback.
Do you know when the version containing the fix will be release ?

Regards, Kevin

**Comment by cgrinds** [comment]
It should be [available](https://github.com/NetApp/harvest/releases/tag/v.22.02.0) now. Let us know if the latest drop fixes you problem

**Comment by figeac888** [comment]
> The reported issue seems to be correctly fixed :
> 
> [root@XXXX# /opt/harvest/bin/harvest status Datacenter | Poller | PID | PromPort | Status --------------+-------------+-------+----------+---------- local | unix | 34322 | | running opme1nasnd1 | cluster-vdr | 34324 | | running
> 
> However dashboard Netapp Harvest : Pollers still containing empty datas

My bad, dashboard Netapp Harvest : Pollers is containing data correctly.
You can close this issue.

Thank you !

**Comment by cgrinds** [comment]
Awesome! Glad you're all set and appreciate the confirmation
