### ISSUE TITLE
Field access-time returned by snapshot-get-iter should be creation-time

### ISSUE THREAD

**Issue by pilot7777** [NetApp/harvest#861]
**Describe the bug**
Field access-time returned by snapshot-get-iter is confusing. It is actually the time the sanpshot is created. IMHO, creation-time is more appropriated. 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:09:54-0500) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS:  RHEL 7.9
- Install method: yum
- ONTAP Version: 9.8
- Other:

**To Reproduce**

**Expected behavior**
Tell us what should happen

**Actual behavior**
Tell us what happens instead

**Possible solution, workaround, fix**
Tell us if there is a workaround or fix

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by rahulguptajss** [comment]
@pilot7777 That naming is on Ontap side though with Harvest, you can map it to any name within templates using symbol =>
Does that work for you?

**Comment by cgrinds** [comment]
hi @pilot7777 i don't think Harvest currently sends the `snapshot-get-iter` ZAPI. It is not in any of our templates. Maybe it's in one of your custom templates?

I agree that creation-time looks more appropriate. As Rahul mentioned, you can change that mapping in your template file.

**Comment by cgrinds** [comment]
We'll make sure there are no issues with your template and then close. Thanks!

**Comment by cgrinds** [comment]
We'll close this one and continue in #862
