### ISSUE TITLE
wrong object name used in conf/zapi/cdot/9.8.0/snapshot.yaml

### ISSUE THREAD

**Issue by pilot7777** [NetApp/harvest#862]
**Describe the bug**
Seems a new template was added, conf/zapi/cdot/9.8.0/snapshot.yaml. The query it uses is "snapshot-policy-get-iter". It names object as "snapshot". But the object should be snapshot-policy. This causes conflict with our custom template using query "snapshot-get-iter" which specified object as snapshot.

The error message is 
{"level":"error","Poller":"flc1-sys-ash0-cloudsys","collector":"Zapi:Snapshot","stack":[{"func":"New","line":"35","source":"errors.go"},{"func":"(*AbstractCollector).Start.func1","line":"259","source":"collector.go"},{"func":"gopanic","line":"1038","source":"panic.go"},{"func":"goPanicIndex","line":"90","source":"panic.go"},{"func":"(*Node).SearchChildren.func1","line":"448","source":"node.go"},{"func":"(*Node).SearchChildren","line":"462","source":"node.go"},{"func":"(*Zapi).PollInstance","line":"260","source":"zapi.go"},{"func":"(*task).Run","line":"61","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"300","source":"collector.go"},{"func":"goexit","line":"1581","source":"asm_amd64.s"}],"error":"goroutine panic => goroutine 625 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start.func1()\n\tgoharvest2/cmd/poller/collector/collector.go:259 +0x85\npanic({0x9a9e80, 0xc0010bb800})\n\truntime/panic.go:1038 +0x215\ngoharvest2/pkg/tree/node.(*Node).SearchChildren.func1(0xc000e3e090, {0xe73ff8, 0x0, 0x0})\n\tgoharvest2/pkg/tree/node/node.go:448 +0x485\ngoharvest2/pkg/tree/node.(*Node).SearchChildren(0x9cf880, {0xe73ff8, 0x0, 0x0})\n\tgoharvest2/pkg/tree/node/node.go:462 +0xd9\ngoharvest2/cmd/collectors/zapi/collector.(*Zapi).PollInstance(0xc0002a4820)\n\tgoharvest2/cmd/collectors/zapi/collector/zapi.go:260 +0x4e5\ngoharvest2/cmd/poller/schedule.(*task).Run(0xc00031b310)\n\tgoharvest2/cmd/poller/schedule/schedule.go:61 +0x4e\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start(0xc000236460, 0xc00058e630)\n\tgoharvest2/cmd/poller/collector/collector.go:300 +0x4d3\ncreated by main.(*Poller).Start\n\t./poller.go:398 +0x2e5\n","caller":"goharvest2/cmd/poller/collector/collector.go:259","time":"2022-02-16T12:47:12-08:00","message":"Collector panicked runtime error: index out of range [0] with length 0"}

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: [harvest version 22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:09:54-0500) linux/amd64]
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: [RHEL 7.9]
- Install method: [yum]
- ONTAP Version: [9.8]
- Other:

**To Reproduce**

**Expected behavior**
The template should be renamed to conf/zapi/cdot/9.8.0/snapshot-policy.yaml

name:                     SnapshotPolicy
query:                    snapshot-policy-get-iter
object:                   snapshot-policy

counters:
  snapshot-policy-info:
    - ^^vserver-name     =>  svm
    - ^^policy           =>  snapshot_policy
    - ^comment           =>  comment
    - total-schedules    =>  total_schedules

export_options:
  instance_keys:
    - svm
    - snapshot_policy
    - comment

**Actual behavior**
Tell us what happens instead

**Possible solution, workaround, fix**
Remove snapshot.yaml from conf/zapi/default.yaml

**Additional context**
Add any other context about the problem here. Share logs, error output, etc.

**Comment by rahulguptajss** [comment]
@pilot7777 Could you share your custom snapshot template. We want to reproduce it to see if there are any other template merge issues in general.

**Comment by pilot7777** [comment]
> @pilot7777 Could you share your custom snapshot template. We want to reproduce it to see if there are any other template merge issues in general.

Here is our custom snapshot template.
name:                     Snapshot
query:  		  snapshot-get-iter                  
object:                   snapshot

counters:
  snapshot-info:
    - access-time 		=> creation_time
    - ^^vserver			=> svm
    - ^^volume
    - ^^name			=> snapshot
export_options:
  include_all_labels: true

**Comment by rahulguptajss** [comment]
Thanks. We are able to reproduce it and will take a look.
