### ISSUE TITLE
dashboards with `volume_labels` metric in variables are not working, because there is not such metric in Prometheus

### ISSUE THREAD

**Issue by unbreakabl3** [NetApp/harvest#864]
**Describe the bug**
We have 2 Datacenters running ONTAP 9.8 clusters. For some reason, one of them doesn't have a metrics called `volume_labels` in Prometheus. Means all dashboards, which using this metric in their variables (like Volumes dashboard for example) are not working

**Environment**
- Harvest version: harvest version 22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:09:54-0500) linux/amd64
- Command line arguments used:  `bin/harvest start --config=foo.yml`
- OS: CentOS 7.9
- Install method: yum
- ONTAP Version: 9.8

**To Reproduce**
Don't know how to reproduce it , because don't know why there is not such metric on the second NetApp

**Expected behavior**
All dashboards will work

**Actual behavior**
metric called `volume_labels` doesn't exists. Half of the dashboards are not working

**Possible solution, workaround, fix**
Maybe to use another metric with is 100% will be exists on any NetApp

**Comment by cgrinds** [comment]
hi @unbreakabl3 can you post your poller logs for the poller monitoring the cluster that does not have volume_labels. This is likely due to [timeout](https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#some-of-my-clusters-are-not-showing-up-in-grafana) trying to collect the volume ZAPIs.

**Comment by unbreakabl3** [comment]
Hey, @cgrinds. Thank you for your reply. We already found a bug in a slack channel. Hope it will be fixed in the next release.
