### ISSUE TITLE
Support global_prefix on Grafana import

### ISSUE THREAD

**Issue by Matthias-Beck** [NetApp/harvest#87]
**Is your feature request related to a problem? Please describe.**
Support exporter global_prefix for Grafana dashboard import. If a prefix is defined today, all queries on the dashboards have to be updated manually

**Describe the solution you'd like**
While importing the dashboards via the Grafana tool, the exporter section should be checked for global_prefix entries.

**Describe alternatives you've considered**
Add a command parameter (e.g. --db-prefix) to the Grafana tool like the --datasource parameter for naming the prefix and updating the queries in the dashboards.

**Comment by vgratian** [comment]
Hi Matthias, good point. 

This issue is loosely related to #22
