### ISSUE TITLE
Cannot See the FabricPool Dashboards in  Grafana Panels.

### ISSUE THREAD

**Issue by shubhammer** [NetApp/harvest#872]
volume Detail Dashboard show zero Fabricpool Panels in Grafana.

![image](https://user-images.githubusercontent.com/59341297/155146307-e8a6d77c-47cd-4bf9-965b-24f358582c99.png)

**Comment by cgrinds** [comment]
@shubhammer Thanks for the feature request. 

You're right there are no panels. What you highlighted is a placeholder for the drilldown. Harvest 2 hasn't ever shipped with FabricPool dashboards, but this is an area we want to add.

See also https://github.com/NetApp/harvest/issues/788

**Comment by cgrinds** [comment]
Closing since this request is covered by #788
