### ISSUE TITLE
Role creation CLI for Harvest user with 7-mode

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#891]
When looking at https://github.com/NetApp/harvest/blob/main/docs/AuthAndPermissions.md, I see the procedure well documented regarding required permissions for the Harvest user with cDOT, but nothing about 7-mode.

A user just sent me a notice on that topic with the following _fix_ he applied :

```
useradmin role modify netapp-harvest-role -a login-http-admin,api-system-get-version,api-system-get-info,api-perf-object-*,api-ems-autosupport-log,api-diagnosis-status-get,api-lun-list-info,api-diagnosis-subsystem-config-get-iter,api-disk-list-info,api-diagnosis-config-get-iter,api-aggr-list-info,api-volume-list-info,api-storage-shelf-environment-list-info,api-qtree-list,api-quota-report
```

**Comment by cgrinds** [comment]
thanks @ybizeul I'll update the docs to include that
