### ISSUE TITLE
Add workload counters in ZapiPerf

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#9]
Work is done, but didn't make the 21.05 release. Merge after 21.05 is cut

**Comment by vgratian** [comment]
I did not re-open the pull request, since I reconsidering if I should change the initial implementation with a more efficient one.

The key issue here:
Counter of object `workload_detail` require the counter `ops` from object `workload` for final calculations. Since collectors/objects are fully isolated from each other, there is easy solution for this.

My solution was: The collector for `workload_detail` will do an additional and redundant poll to collect `ops` from object `workload`.

What I am thinking about now: combine objects `workload` and `workload_detail` into one single collector. (Same issue goes for the objects `workload_volume` and `workload_detail_volume`).

**Comment by rajeshl8** [comment]
verified the issue using below build version and observed qos data present.
Build : harvest version 21.06.0801-nightly (commit 5dd80cc) (build date 2021-06-08T01:08:56+0530) linux/amd64

[root@scspa2385980005 ~]# curl -s http://localhost:12992/metrics | grep qos
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="hya_cache"} 0
qos_write_latency{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="fc_miss"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="cloud"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="bamboo_ssd"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="hya_non_cache"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="pmem"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="ext_cache"} 0
qos_write_ops{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="disk"} 0
qos_read_latency{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_sequential_writes{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_sequential_reads{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_read_data{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_ops{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0.1666804821816199
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="cloud_s2c"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="cache"} 0
qos_total_data{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_write_data{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0",metric="hya_hdd"} 0
qos_read_ops{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 0
qos_latency{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="19804",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol3",policy_group="harvest_pg0"} 54.6
qos_total_data{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="15173",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol4",policy_group="harvest_pg0"} 0
qos_write_data{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="15173",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol4",policy_group="harvest_pg0"} 0
qos_read_io_type{datacenter="umeng_aff300",cluster="umeng-aff300-05-06",wid="15173",svm="umeng-aff300-05-svm1",volume="harvest_IO_vol4",policy_group="harvest_pg0",metric="hya_hdd"} 0
qos_read_ops{datacenter="umeng_aff300",cluster
