### ISSUE TITLE
Harvest should include power consumed in existing shelf and cluster dashboards

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#903]
We already include fan speed and temperature and in a few cases power.
We should improve the power consumption metrics.

**Comment by rahulguptajss** [comment]
- [ ] Zapi plugin implementation
- [ ] Rest Plugin implementation
- [ ] Dashboard changes

**Comment by cgrinds** [comment]
verified power dashboard, cluster and shelf power panels in `22.05`
