### ISSUE TITLE
Ignore FlexClone volumes related to backup

### ISSUE THREAD

**Issue by ybizeul** [NetApp/harvest#929]
**Is your feature request related to a problem? Please describe.**
Transient volumes tend to pollute volumes list with elements that only exists during backup windows. Those clones are then deleted so shouldn't be collected from a performance or capacity standpoint. This was a default in Harvest 1.x

**Describe the solution you'd like**
A list of volume name patterns should be ignored by default :
```
   - volume `.+_CVclone`
   - volume `.+(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[012])\d\d[0-9]{6}`
   - volume `cl_.+_(19|20)\d\d(0[1-9]|1[012])( 0[1-9]|[12][0-9]|3[01])[0-9]{6}`
   - volume `sdw_cl_.+`
   - volume `MDV_CRS_.+`
   - volume `MDV_aud_.+`
```

**Comment by ybizeul** [comment]
Errata : as Harvest didn't alter in any way Graphite configuration, it was not a *default* as I stated earlier. It was just documented for people to implement the blacklist in graphite configuration. Apologies for the misleading phrasing !

**Comment by cgrinds** [comment]
No worries. We'll document how to do the same in Harvest 2 via this PR #984
