### ISSUE TITLE
After upgrade harvest I can't see information in grafana with the default dashboards

### ISSUE THREAD

**Issue by faguayot** [NetApp/harvest#931]
**Describe the bug**
Since we upgraded from **21.11** version to harvest version **22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:09:54-0500) linux/amd64** we can't see information in the grafana dashboards defined but If we created new customized dashboards we have the information on the database. I think that our harvest is missing some important information which it is used for built the variables in grafana's dashboards. I was thinking that the problem be related with the current version of grafana 8.3.4 but this is not the problem since I tried with grafana 7 and the problem continues.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: 22.02.0-4 (commit 9484df6) (build date 2022-02-15T09:09:54-0500) linux/amd64
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS:  Red Hat Enterprise Linux release 8.2 (Ootpa)
- Install method: yum
- ONTAP Version: 9.7

**Expected behavior**
We should able to see the dashboards in grafana like we do in previous versions.

**Actual behavior**
We can't find the metrics `node_labels` in our metrics (counter, objetc), this parameter is used for built the variable "_Datacenter_" in many dashboards. This is an example but this happens with other metrics, for example checking the ### **`NetApp Detail: Cluster`** we don't find `node_new_status` too in the **metrics browser.**

**Comment by cgrinds** [comment]
hi @faguayot sounds like something may be wrong with your dashboard variables. If I understand correctly, newly created dashboards work fine, but older versions (upgraded from earlier versions) do not work. Is that correct?

## Dashboards

Let's focus on one of the upgraded dashboards that doesn't work. Can you open the dashboard settings by clicking the gear icon? I'm using the `node details` dashboard below, but pick whichever one isn't working for you.

![image](https://user-images.githubusercontent.com/242252/160648536-7d575c2a-9f66-4802-ad30-5a356523ec7c.png)

and then click Variables
![image](https://user-images.githubusercontent.com/242252/160648770-65bf1f21-bec0-4cce-b170-d16ebf06fa7d.png)

and double check that your variables look correct? 

## Prometheus Queries
If you go to Prometheus directly, you do not see `node_labels`? If so that would explain the problem.

![image](https://user-images.githubusercontent.com/242252/160649883-dba841c6-45c6-4c4b-bac5-57a5b4864180.png)

Can you double check that the poller is collecting and exporting the node information by starting Harvest, finding the Prometheus port via `bin/harvest status` or 
```bash
ps aux | grep poller
```

and then curling that endpoint

```bash
curl -s http://localhost:12990/metrics | grep -E "node_labels"
```

**Comment by faguayot** [comment]
> hi @faguayot sounds like something may be wrong with your dashboard variables. If I understand correctly, newly created dashboards work fine, but older versions (upgraded from earlier versions) do not work. Is that correct?
> 
> ## Dashboards
> Let's focus on one of the upgraded dashboards that doesn't work. Can you open the dashboard settings by clicking the gear icon? I'm using the `node details` dashboard below, but pick whichever one isn't working for you.
> 
> ![image](https://user-images.githubusercontent.com/242252/160648536-7d575c2a-9f66-4802-ad30-5a356523ec7c.png)
> 
> and then click Variables ![image](https://user-images.githubusercontent.com/242252/160648770-65bf1f21-bec0-4cce-b170-d16ebf06fa7d.png)
> 
> and double check that your variables look correct?
> 
> ## Prometheus Queries
> If you go to Prometheus directly, you do not see `node_labels`? If so that would explain the problem.
> 
> ![image](https://user-images.githubusercontent.com/242252/160649883-dba841c6-45c6-4c4b-bac5-57a5b4864180.png)
> 
> Can you double check that the poller is collecting and exporting the node information by starting Harvest, finding the Prometheus port via `bin/harvest status` or
> 
> ```shell
> ps aux | grep poller
> ```
> 
> and then curling that endpoint
> 
> ```shell
> curl -s http://localhost:12990/metrics | grep -E "node_labels"
> ```

Hello @cgrinds,

Sorry I wanted to add some screenshots after the creation of the issue but I miss them.

Here an example of dashboards (Aggregate):

![image](https://user-images.githubusercontent.com/85484449/160653745-50688a80-eb32-40f5-8ba3-ac11aa791f78.png)

Those are the variables for this dashboards:

![image](https://user-images.githubusercontent.com/85484449/160654145-9eb5e19e-0977-4d69-ab64-be87ba3ad40d.png)

In this last you can see that there isn't any result for the variable Datacenter.

![image](https://user-images.githubusercontent.com/85484449/160654283-0ac4cfa1-c8f3-49ff-809d-53fea0d1b80e.png)

If I use the command for checking the labels `curl -s http://localhost:12990/metrics | grep -E "node_labels"` I don't have results. Even trying with the different other ports which use the other pollers.

### The prometheus query
![image](https://user-images.githubusercontent.com/85484449/160655408-d7e1ce08-ffd6-4fb0-8780-d485d3cfc7c8.png)

And the process:

![image](https://user-images.githubusercontent.com/85484449/160655978-bd6a61e4-5646-4ed8-a7d2-7525912d24ec.png)

![image](https://user-images.githubusercontent.com/85484449/160656153-f4f3c6c3-9a46-44da-a6d3-1e35ddad17ce.png)

Thanks for your quick answer. I don't know why I don't have those metrics and how can I check it. I review the log but maybe I have to change the loglevel to see more and detail information.

**Comment by faguayot** [comment]
Hello @cgrinds 

The problems seems to be related with permissions. When I launched the command for the Node objects, I received an error with the 

> node.yaml

. Then I realized the permissions for zapi, zapiperf and rest were wrong with **_644_**. Then I changed them and the process still to gather information, so the next step was restarted the harvest service and now I can see the node_labels.

![image](https://user-images.githubusercontent.com/85484449/160873172-c0cb2c62-2c4e-4b35-a0f3-c74b7ca97593.png)

Where should I put the custom.yaml for configure new collectors which I don't want to lose with the upgrade of harvest.Do you have a manual to configure this? I don't use **`Rest`** for collecting metrics but I would like to use. Do you have information about this collectors? I try to add `Rest` as collectors in the **`harvest.yml`** but I don't know if I have gathered information using this collectors or not.

Thanks.

**Comment by cgrinds** [comment]
awesome! glad you figured out the permissions issue and you're back in business

Take a look at these links for your questions and let us know if they need clarification
[Configuring templates](https://github.com/NetApp/harvest/blob/main/conf/README.md)

Rest is still beta quality. We have some [notes](https://github.com/NetApp/harvest/blob/main/docs/architecture/rest-collector.md) captured here about when/how we're going to enable it, although this may change as we get more test time with it.

**Comment by kbhalaki** [comment]
Hi @faguayot , i am facing the same issue. 
Can you please describe what was wrong with permission 644 and how did you change them? Do you mean changing the file permissions of the poller files? 

In my case all metrics are visible except the labels which are being in variables in the dashboads.

**Comment by cgrinds** [comment]
hi @kbhalaki what version of Harvest are you using and can you [email](https://github.com/NetApp/harvest/wiki/FAQ#how-do-i-share-sensitive-log-files-with-netapp) us the log files for one of the pollers that are missing data?

**Comment by faguayot** [comment]
hello @kbhalaki,

My problem If I remember correctly was related with the owner of some files like **custom.yaml** which I created with the root user but I forget to change the ownership to harvest user. 

If you check with the curl the metrics and the information is on the database, the problem won't be in the harvest itself and maybe your issue is with your grafana and the configuration of your database.

I am sure @cgrinds can help you with the issue (he helped me with other problems), if you provide the information required.

Good luck with your issue.
