### ISSUE TITLE
Add multiple cluster viewing as in previous version of harvest

### ISSUE THREAD

**Issue by bcase303** [NetApp/harvest#939]
When using the previous version I would be able to look at multiple clusters at once.  For example in the Cluster dashboard, I would be able to select two clusters at once.  This is useful since I am running MCC and can look at both sides of the cluster in one view. 

I would like the ability to view two clusters at once in the same view.  

I tried toggling the multi-value and include all in the variable section without success for the Cluster dashboard.

If there is a way to create my own dashboard that works too. The previous version being able to show multiple clusters was useful in graphing out problems.

**Comment by rahulguptajss** [comment]
@bcase303 Harvest ```22.02 release``` supports this with below command (addition ```--multi``` argument)

```bin/grafana import --addr localhost:3000 --multi```

In case you wish to overwrite existing version dashboard , you need to pass ```--overwrite``` flag to this command

**Comment by cgrinds** [comment]
@rahulguptajss's right, this was added in `22.02`, but it was reverted shortly before release. This feature will be in the May release of Harvest. 

If you want to try it out sooner, grab a [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly) and let us know what you think.

a `--multi` option was added to `bin/grafana import`. When this option is specified, on the command line during import, the dashboards will be modified to include multi-select drop-downs for each variable and all expressions are rewritten to use these multi-select variables.

Details #815
