### ISSUE TITLE
Grafana Dashboards panels getting 404

### ISSUE THREAD

**Issue by unbreakabl3** [NetApp/harvest#96]
**Describe the bug**
Some metrics in some Grafana dashboards panels getting an error code 404

**Environment**

- Harvest version: harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64
- OS: CentOS Linux release 7.9.2009 (Core)
- Install method: rhel
- ONTAP Version: 9.7

**To Reproduce**
Just open any dashboard

**Expected behavior**
all panels should return values

**Actual behavior**
some of them returns error code 404

**Possible solution, workaround, fix**
Disable `Exemplars` feature

**Additional context**
I did notice that only a panels with that feature enabled getting 404. I did some tests and looks like the issue coming from that query - `query_exemplars`. When I disabled `Exemplars` feature in each panel in each dashboard, all panels started to get a metrics and all looks good.

**Comment by vgratian** [comment]
hi, any chance you can provide a screenshot?

seems like datasource is not properly set, but might be something else

**Comment by vgratian** [comment]
what ontap model and version do you have?

**Comment by unbreakabl3** [comment]
> hi, any chance you can provide a screenshot?
> 
> seems like datasource is not properly set, but might be something else

Please. This is when `Exemplars` is disabled.

![image](https://user-images.githubusercontent.com/13556249/120313392-2d15e200-c2da-11eb-88fa-fe61bdb6520a.png)

**Comment by unbreakabl3** [comment]
> what ontap model and version do you have?

We have a lot. For example 8060,8300,8200...
ONTAP is 9.7P4

**Comment by vgratian** [comment]
thanks a lot, I don't believe I have seen this specific message earlier

can you provide the version of your grafana?

**Comment by unbreakabl3** [comment]
> thanks a lot, I don't believe I have seen this specific message earlier
> 
> can you provide the version of your grafana?

You're very welcome

Please:  v7.4.5 (8a2c78d3f8)

**Comment by sevenval-admins** [comment]
We also had the problem. The only workaround for us was to set exemplars to false in all json files before importing the dashboards. The error occurs because in Prometheus the Exemplars Storage Backend is switched off by default, see https://prometheus.io/docs/prometheus/latest/disabled_features/#exemplars-storage.

**Comment by cgrinds** [comment]
@sevenval-admins is there a changed needed in Harvest's Grafana dashboards to help? We don't currently include anything about `exemplars` in our dashboards.

**Comment by florianmulatz** [comment]
Hi,
from my point of understanding - (untested) - it's enough to change the option 
```
"exemplar": true,
```
to
```
"exemplar": false,
```

cheers

**Comment by unbreakabl3** [comment]
> Hi,
> from my point of understanding - (untested) - it's enough to change the option
> 
> ```
> "exemplar": true,
> ```
> 
> to
> 
> ```
> "exemplar": false,
> ```
> 
> cheers
> EDIT: tested - works as sevenval-admins told!

Exactly. That's what I did. Maybe this should it be a default value...

**Comment by cgrinds** [comment]
Thanks all
